feat(ssi): add administration endpoints
eclipse-tractusx/portal-backend pull request #100
Opened 2023-06-23 09:32 UTC by Phil91

## Description

add endpoint to get the certificates
add endpoint to approve a ssi request
add endpoint to reject a ssi request

## Why

To be able to display all ssi requests as an administrator and either approve or reject them.

## Issue

N/A - Jira Issue: CPLP-2855

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally (currently the /dismantler endpoint isn't working)
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2023-06-27 21:28 UTC, ntruchsess requested changes

2023-06-27 21:28 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanySsiDetailsRepository.cs
> +                .GroupBy(c => c.CompanyId),
this ain't work. The grouping is being used to allow counting the whole resultset and selection of data in a single sql statement. It's therefore mandatory the grouping will result in a single group containing the whole resultset. (That would be the case if the where-condition would filter a single companyId). As the where-condition is optional the grouping-style paginationSource cannot be used. This query will fail as soon more than a single company has assigned CompanySsiDetail data. Use Pagination.CreateResponseAsync<T>(int page, int size, int maxSize, Func<int, int, AsyncSource<T>> getSource) instead.

2023-06-27 21:28 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanySsiDetailsRepository.cs
> +                Detail = x,
as all properties being referenced are direct properties of 'x' there is no point in using this intermediate select. While not causing any incorrect data being selected the subsequent select is not being simplified at all (it's just the property-names being shorter).

2023-06-27 21:28 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanySsiDetailsRepository.cs
> +            .Select(x => new ValueTuple<bool, CompanySsiDetailStatusId, VerifiedCredentialTypeId, Guid, string?, string?, string?>(true, x.CompanySsiDetailStatusId, x.VerifiedCredentialTypeId, x.Crea
to improve readability please put all the constructor-arguments on a separate line. (The valuetuple type-declaration may stay on a single line as it is guaranteed to just re-declare the returntype of the signature)

2023-06-27 21:28 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanySsiDetailsRepository.cs
> +    public void AttachAndModify(Guid id, Action<CompanySsiDetail>? initialize, Action<CompanySsiDetail> updateFields)
to avoid any ambiguity rename to 'AttachAndModifyCompanySsiDetails'

2023-06-27 21:30 UTC, ntruchsess commented
please rebase on dev to resolve the conflicts

2023-06-28 08:37 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanySsiDetailsRepository.cs
> +                .GroupBy(c => c.CompanyId),
changed

2023-06-29 18:11 UTC, ntruchsess requested changes

2023-06-29 18:11 UTC, ntruchsess commented on src/externalsystems/Custodian.Library/CustodianService.cs
> +        await httpClient.PostAsync("/api/credentials/issuer/framework", stringContent, cancellationToken)
Use 'PostAsJson' instead

2023-06-29 18:11 UTC, ntruchsess commented on src/framework/Framework.Models/EnumMemberConverter.cs
> +        Enum.TryParse(reader.GetString(), out T enumValue) ?
The converter should work both ways.

2023-06-29 18:11 UTC, ntruchsess commented on src/framework/Framework.Models/EnumMemberConverter.cs
> +    public override T Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
There should be a unit-test for the converter.

2023-06-30 09:12 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
> +                query.CountAsync(),
adjusted

2023-06-30 09:12 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
> +using System.Linq.Expressions;
removed

2023-06-30 09:12 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
> +using Org.Eclipse.TractusX.Portal.Backend.PortalBackend.PortalEntities.Entities;
removed

2023-06-30 09:12 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanySsiDetailsRepository.cs
> +using Microsoft.EntityFrameworkCore.Infrastructure.Internal;
removed

2023-06-30 09:12 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanySsiDetailsRepository.cs
> +using Org.Eclipse.TractusX.Portal.Backend.Framework.Models;
removed

2023-06-30 09:12 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanySsiDetailsRepository.cs
> +using System.Linq.Expressions;
removed

2023-06-30 09:13 UTC, Phil91 commented on src/framework/Framework.Models/EnumExtensions.cs
> +
adjusted

2023-06-30 09:13 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
> +        if (data.Kind == VerifiedCredentialTypeKindId.USE_CASE)
changed

2023-06-30 09:13 UTC, Phil91 commented on src/externalsystems/Custodian.Library/CustodianService.cs
> +using Org.Eclipse.TractusX.Portal.Backend.Framework.Models;
removed

2023-06-30 09:13 UTC, Phil91 commented on src/externalsystems/Custodian.Library/CustodianService.cs
> +        await httpClient.PostAsync("/api/credentials/issuer/framework", stringContent, cancellationToken)
adjusted

2023-06-30 09:13 UTC, Phil91 commented on src/framework/Framework.Models/EnumMemberConverter.cs
> +        Enum.TryParse(reader.GetString(), out T enumValue) ?
adjusted the logic

2023-06-30 09:13 UTC, Phil91 commented on src/framework/Framework.Models/EnumMemberConverter.cs
> +    public override T Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
added unit tests for both methods

2023-07-03 18:30 UTC, ntruchsess requested changes
I did some cleanup. Please get those changes before proceeding

2023-07-03 18:30 UTC, ntruchsess commented on tests/externalsystems/Custodian.Library.Tests/CustodianServiceTests.cs
> +        true.Should().BeTrue(); // One Assert is needed - just checking for no exception
please do a real assert (like the one I did add at line 299)

2023-07-03 18:30 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
> +        var sortedQuery = pageSorting switch
the mapping of the default-value may be included in the switch-expression
```
        var sortedQuery = sorting switch
        {
            CompanySsiDetailSorting.CompanyAsc or null => query.OrderBy(c => c.Company!.Name),
            CompanySsiDetailSorting.CompanyDesc => query.OrderByDescending(c => c.Company!.Name),
            _ => query
        };

```

2023-07-03 20:24 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
> +        var sortedQuery = pageSorting switch
added

2023-07-03 20:24 UTC, Phil91 commented on tests/externalsystems/Custodian.Library.Tests/CustodianServiceTests.cs
> +        true.Should().BeTrue(); // One Assert is needed - just checking for no exception
added the assert.

2023-07-03 20:33 UTC, ntruchsess approved these changes

2023-07-03 20:37 UTC, ntruchsess requested changes
what about the Entity-class UseCaseParticipationStatus? It doesn't have any references. Either remove or add to DbContext and create a Migration

2023-07-04 06:35 UTC, Phil91 commented
> UseCaseParticipationStatus

i removed it hear, to be on the side side and don't have any odd behavior while rebasing again

2023-07-04 16:51 UTC, ntruchsess requested changes
please fix those smells: https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&pullRequest=403&id=catenax-ng_tx-portal-backend&open=AYkhyeXfOARWWsrJSHRX
(I did remove two obsolete files, so please first pull)

2023-07-04 20:10 UTC, Phil91 commented
> please fix those smells: https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&sinceLeakPeriod=true&pullRequest=403&id=catenax-ng_tx-portal-backend (I did remove two obsolete files, so please first pull)

removed the code smells.

2023-07-04 21:18 UTC, ntruchsess approved these changes

2023-07-04 21:22 UTC, ntruchsess approved these changes

2023-07-04 21:25 UTC, merged