feat(tech user): add internal invitation tech user
eclipse-tractusx/portal-backend pull request #1002
Opened 2024-09-17 09:20 UTC by typecastcloud

Refs: eclipse-tractusx/portal-backend#932

## Description

Add `Registration Internal` as new technical user that can be created in portal.

New `technical_roles_management` composite role with name `Registration Internal` with:
- `invite_new_partner`
- `view_submitted_applications`
is also being added as new client role in eclipse-tractusx/portal-iam#189

## Why

Operator company wants to integrate 3rd party service to send out invites. Allows inviting and reviewing status via API.

## Issue

Refs: eclipse-tractusx/portal-backend#932
Related: eclipse-tractusx/portal-iam#189

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [ ] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-09-17 10:57 UTC, ntruchsess requested changes
@typecastcloud technically this looks fine, but you do not declare to have tested the change (together with iam-data in https://github.com/eclipse-tractusx/portal-iam/pull/189) at least locally?

2024-09-17 11:09 UTC, typecastcloud commented
> @typecastcloud technically this looks fine, but you do not declare to have tested the change (together with iam-data in [eclipse-tractusx/portal-iam#189](https://github.com/eclipse-tractusx/portal-iam/pull/189)) at least locally? (I can see the unit-tests in CI are failing, but that seems to be unrelated to your change. I'll look into that)

Hi Norbert, I converted this back to draft until I have fully tested this. I only ran dotnet test until now and was trying to find the reason for the failing test in pipeline and I first requested initial review from internal developers.

Thank you for the quick reply anyway.

2024-09-23 15:19 UTC, evegufy submitted a review, later dismissed

2024-09-24 05:31 UTC, Phil91 submitted a review, later dismissed

2024-09-24 05:32 UTC, Phil91 commented
@typecastcloud could you please resolve the conflicts? In my opinion everything else looks good

2024-09-24 07:01 UTC, ntruchsess approved these changes

2024-09-24 07:10 UTC, ntruchsess requested changes
@typecastcloud : please resolve the conflict in CHANGELOG.md by doing a rebase on latest main.

2024-09-24 07:30 UTC, typecastcloud commented
@Phil91 @ntruchsess rebased and changelog is adjusted.

New line was missing at the end of the changelog too.

2024-09-24 08:08 UTC, typecastcloud commented on CHANGELOG.md
> +  * add Registration Internal as Operator technical user for invite API [#1002](https://github.com/eclipse-tractusx/portal-backend/pull/1002)
My mistake. Done.

2024-09-24 08:23 UTC, evegufy approved these changes

2024-09-25 10:15 UTC, ntruchsess requested changes
@typecastcloud : unit-test GetServiceAccountRolesAsync_WithValidData_ReturnsExpected is failing. An additional assert has been added on main that needs to be adjusted as well (see my suggested change)

2024-09-25 10:15 UTC, ntruchsess commented on tests/portalbackend/PortalBackend.DBAccess.Tests/UserRolesRepositoryTests.cs
>          data.Where(x => x.RoleType == UserRoleType.Internal).Should().HaveCount(12);
```suggestion
        data.Should().HaveCount(14);
        data.Should().OnlyHaveUniqueItems();
        data.Where(x => x.RoleType == UserRoleType.Internal).Should().HaveCount(13);
```

2024-09-26 07:37 UTC, typecastcloud commented on tests/portalbackend/PortalBackend.DBAccess.Tests/UserRolesRepositoryTests.cs
>          data.Where(x => x.RoleType == UserRoleType.Internal).Should().HaveCount(12);
I accepted your suggestions and tests are running green now.

2024-09-26 11:39 UTC, ntruchsess approved these changes

2024-09-26 11:42 UTC, merged