fix(registration): fixed the company name change in IDP
eclipse-tractusx/portal-backend pull request #1010
Opened 2024-09-19 12:22 UTC by dhiren-singh-007

## Description

Added method to update display name and organisation attribute value in Identity provider in keycloak

## Why

This was causing mismatch issue in login screen for company name and also in the user profile menu after  login in portal

## Issue

#942 

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes

2024-09-19 19:50 UTC, ntruchsess requested changes
see comments

2024-09-19 19:50 UTC, ntruchsess commented on src/provisioning/Provisioning.Library/ProvisioningManager.cs
> +        var organisationMapperId = mappers.FirstOrDefault(z => z.Name == $"{_settings.MappedCompanyAttribute}-mapper")?.Id ?? string.Empty;
from my understanding the update will fail if organisationMapperId is not a valid id but an empty string. If the mapper is not found the method should delegate to the existing CreateCentralIdentityProviderOrganisationMapperAsync

2024-09-19 19:50 UTC, ntruchsess commented on src/provisioning/Provisioning.Library/ProvisioningManager.cs
> +    public async ValueTask UpdateCentralIdentityProviderMapperAsync(string alias, string displayName)
this method should be relocated to class IdentityProviderMapper right after method CreateCentralIdentityProviderOrganisationMapperAsync and the name should be changed to indicate it is specific for the organisation-mapper (like UpdateCentralIdentityProviderOrganisationMapperAsync(string alias, string organisationName)
(private UpdateAttributeInIdentityProvider should be relocated as well)

2024-09-23 14:43 UTC, dhiren-singh-007 commented on src/provisioning/Provisioning.Library/ProvisioningManager.cs
> +        var organisationMapperId = mappers.FirstOrDefault(z => z.Name == $"{_settings.MappedCompanyAttribute}-mapper")?.Id ?? string.Empty;
@ntruchsess Thanks for reviewing it . Can you please tell me which `CreateCentralIdentityProviderOrganisationMapperAsync` should i use as it exist in two file i.e 
```
src/provisioning/Provisioning.Library/Extensions/IdentityProviderManager.cs
src/externalsystems/Provisioning.Library/IdpManagement.cs
```

2024-10-01 11:15 UTC, dhiren-singh-007 commented on src/provisioning/Provisioning.Library/ProvisioningManager.cs
> +        var organisationMapperId = mappers.FirstOrDefault(z => z.Name == $"{_settings.MappedCompanyAttribute}-mapper")?.Id ?? string.Empty;
Hi @ntruchsess , i started this change today and got some issues , can you please clarify .
Issue : If i move this method`UpdateCentralIdentityProviderMapperAsync ` in `src/externalsystems/Provisioning.Library/IdpManagement.cs` then i have to move its parent method `UpdateCompanyNameInIdentityProvider` from `src/provisioning/Provisioning.Library/Service/UserProvisioningService.cs` to `src/externalsystems/Provisioning.Library/IdpManagement.cs` because currently `externalsystems/Provisioning.Library`  is referencing the  `provisioning/Provisioning.Library` .

If its ok then i can move all these methods in `src/externalsystems/Provisioning.Library/IdpManagement.cs` then I would like to double check with you if i can reference this project in Registration.Service ?

2024-10-23 13:23 UTC, dhiren-singh-007 commented on src/provisioning/Provisioning.Library/ProvisioningManager.cs
> +        var organisationMapperId = mappers.FirstOrDefault(z => z.Name == $"{_settings.MappedCompanyAttribute}-mapper")?.Id ?? string.Empty;
I think i did mistake in putting the above comment as it is part of different comment so i moved it in bottom.
otherwise delegate thing is fixed

2024-10-23 13:25 UTC, dhiren-singh-007 commented on src/provisioning/Provisioning.Library/ProvisioningManager.cs
> +    public async ValueTask UpdateCentralIdentityProviderMapperAsync(string alias, string displayName)
Regarding the moving the method I commented here https://github.com/eclipse-tractusx/portal-backend/pull/1010#issuecomment-2432133484
Renaming is fixed

2024-11-05 08:21 UTC, ntruchsess approved these changes

2024-11-05 08:44 UTC, Phil91 approved these changes

2024-11-05 09:10 UTC, merged