feat(api-hub): adjust ms build to generate swagger file
eclipse-tractusx/portal-backend pull request #1030
Opened 2024-09-23 12:16 UTC by Phil91

## Description

* update the swagger nuget package to be able to create the swagger documentation while building the project
* adjust ms build processes to generate an openApi file and copy it to the docs/api folder

## Why

To align with [TRG 1.08](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-08/)

## Issue

Refs: #1021

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-09-23 14:04 UTC, evegufy requested changes

2024-09-23 14:04 UTC, evegufy commented on docs/api/Org.Eclipse.TractusX.Portal.Backend.Administration.Service.yaml
> +  version: v2.3.0
the version suffix isn't considered: https://github.com/eclipse-tractusx/portal-backend/blob/feature/1021-api-hub/src/Directory.Build.props#L23
could you please adjust this?
(applies to all services)

2024-09-23 16:10 UTC, Phil91 commented on docs/api/Org.Eclipse.TractusX.Portal.Backend.Administration.Service.yaml
> +  version: v2.3.0
it's adjusted :) actually the assembly version don't include the prefixes.

2024-09-24 15:17 UTC, evegufy requested changes
Build is failing, maybe due to the implementation of the skip config validation

2024-09-24 15:17 UTC, evegufy commented on .tractusx
> +- "https://github.com/eclipse-tractusx/portal-backend/tree/v2.2.0/docs/api/Org.Eclipse.TractusX.Portal.Backend.Services.Service.yaml"
Please change to next/upcoming version:
```suggestion
openApiSpecs:
- "https://github.com/eclipse-tractusx/portal-backend/tree/v2.3.0-alpha.2/docs/api/Org.Eclipse.TractusX.Portal.Backend.Administration.Service.yaml"
- "https://github.com/eclipse-tractusx/portal-backend/tree/v2.3.0-alpha.2/docs/api/Org.Eclipse.TractusX.Portal.Backend.Apps.Service.yaml"
- "https://github.com/eclipse-tractusx/portal-backend/tree/v2.3.0-alpha.2/docs/api/Org.Eclipse.TractusX.Portal.Backend.Notifications.Service.yaml"
- "https://github.com/eclipse-tractusx/portal-backend/tree/v2.3.0-alpha.2/docs/api/Org.Eclipse.TractusX.Portal.Backend.Registration.Service.yaml"
- "https://github.com/eclipse-tractusx/portal-backend/tree/v2.3.0-alpha.2/docs/api/Org.Eclipse.TractusX.Portal.Backend.Services.Service.yaml"
```

2024-09-25 07:33 UTC, evegufy commented on .tractusx
> +- "https://github.com/eclipse-tractusx/portal-backend/tree/v2.3.0-alpha.2/docs/api/Org.Eclipse.TractusX.Portal.Backend.Services.Service.yaml"
```suggestion
- "https://github.com/eclipse-tractusx/portal-backend/tree/v2.3.0-alpha.2/docs/api/administration-service.yaml"
- "https://github.com/eclipse-tractusx/portal-backend/tree/v2.3.0-alpha.2/docs/api/apps-service.yaml"
- "https://github.com/eclipse-tractusx/portal-backend/tree/v2.3.0-alpha.2/docs/api/notifications-service.yaml"
- "https://github.com/eclipse-tractusx/portal-backend/tree/v2.3.0-alpha.2/docs/api/registration-service.yaml"
- "https://github.com/eclipse-tractusx/portal-backend/tree/v2.3.0-alpha.2/docs/api/services-service.yaml"
```

2024-09-25 07:55 UTC, Phil91 commented on .tractusx
> +- "https://github.com/eclipse-tractusx/portal-backend/tree/v2.3.0-alpha.2/docs/api/Org.Eclipse.TractusX.Portal.Backend.Services.Service.yaml"
did do the rebase and adjusted the links

2024-09-25 13:28 UTC, Phil91 commented on .tractusx
> +- "https://github.com/eclipse-tractusx/portal-backend/tree/v2.3.0-alpha.2/docs/api/services-service.yaml"
adjusted

2024-09-25 13:39 UTC, evegufy submitted a review, later dismissed

2024-09-26 18:34 UTC, ntruchsess approved these changes

2024-09-26 18:51 UTC, ntruchsess approved these changes

2024-09-27 07:26 UTC, evegufy approved these changes

2024-09-27 07:30 UTC, merged