fix(leadPictureId): responding image id for service offer type
eclipse-tractusx/portal-backend pull request #1042
Opened 2024-09-27 09:02 UTC by tfjanjua

## Description

Responding `leadPictureId` for services and updated the response of following APIs, including test cases:
- /api/services/active
- /api/services/{serviceId}

## Why

Default/hard coded service images displaying on “Service Marketplace“ but actual service image should display.

## Issue

[Ref: 1040](https://github.com/eclipse-tractusx/portal-backend/issues/1040)

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes

2024-09-27 10:11 UTC, tfjanjua commented on src/marketplace/Services.Service/ViewModels/ServiceDetailResponse.cs
> +/// <param name="LeadPictureId">Lead pircture Id.</param>
Done

2024-09-30 07:01 UTC, Phil91 submitted a review, later dismissed

2024-09-30 08:46 UTC, tfjanjua commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
> +                service.Documents.Where(document => document.DocumentTypeId == DocumentTypeId.SERVICE_LEADIMAGE && document.DocumentStatusId != DocumentStatusId.INACTIVE).Select(document => document.
@Phil91 , I think this is what is expected because service picture is not a required field from frontend so, LeadPictureId would be Guid.Empty if there is no image exist.

But still lets wait for @ntruchsess's response.

2024-10-01 17:07 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
> +                service.Documents.Where(document => document.DocumentTypeId == DocumentTypeId.SERVICE_LEADIMAGE && document.DocumentStatusId != DocumentStatusId.INACTIVE).Select(document => document.
I think LeadPictureId in the response-class should be declared as nullable,
The preexisting occurrences that declare LeadPictureId as non-nullable Guid should be changed as well, but - as we first need to check the frontend-code - that can also be done in a followup-PR

2024-10-01 17:21 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
> +                offer.Documents.Where(document => document.DocumentTypeId == DocumentTypeId.SERVICE_LEADIMAGE && document.DocumentStatusId != DocumentStatusId.INACTIVE).Select(document => document.Id
@Phil91: Technically I agree with you. From what I can see we have preexisting code that also returns first leadpictureid (or default) - so I assume it's not making things worse to do the same here. But it's worth to evaluate whether it's possible to upload multiple leadpictures per service (there is no code in the backend that ensures this cannot be done, but there might be code in the frontend).

2024-10-01 17:24 UTC, ntruchsess requested changes
see comments

2024-10-02 10:09 UTC, tfjanjua commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
> +                service.Documents.Where(document => document.DocumentTypeId == DocumentTypeId.SERVICE_LEADIMAGE && document.DocumentStatusId != DocumentStatusId.INACTIVE).Select(document => document.
I have declared `LeadPictureId` as nullable where its been used only for Service offer type because picture is mandatory for App offer type from frontend.

I have informed our frontend staff (@Usmanfee) as well that he should also accommodate the “LeadPictureId” param for the “Service” offer type in the frontend so, he will raise ticket and PR for this as soon as possible but still, only BE implementation will not cause any error on UI or frontend right now, if this PR gets merged without frontend implementation.

2024-10-02 10:16 UTC, tfjanjua commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
> +                offer.Documents.Where(document => document.DocumentTypeId == DocumentTypeId.SERVICE_LEADIMAGE && document.DocumentStatusId != DocumentStatusId.INACTIVE).Select(document => document.Id
At the moment I can see that only one image can be uploaded for the type service offer in the frontend.

LeadPictureId has been declared as nullable for Service offer type only.

2024-10-02 10:16 UTC, tfjanjua commented on src/marketplace/Services.Service/ViewModels/ServiceDetailResponse.cs
>      string? ContactEmail,
Thanks for the suggestion, its done

2024-10-04 15:52 UTC, Usmanfee commented
@tfjanjua  here is the FE draft PR FYI : https://github.com/eclipse-tractusx/portal-frontend/pull/1197
upstream issue: https://github.com/eclipse-tractusx/portal-frontend/issues/1195. :)

2024-10-07 20:41 UTC, ntruchsess approved these changes

2024-10-08 08:36 UTC, tfjanjua commented
Thanks for the review @ntruchsess 
I see @MaximilianHauer has added FE-ticket (https://github.com/eclipse-tractusx/portal-frontend/issues/1195) into Backlog but we need this change as part of our release because this hard coded or static image of Service offer type would be a bad user experience for our customers.

cc: @ybidois | @Usmanfee

2024-10-09 07:35 UTC, tfjanjua commented
> @tfjanjua backlog does not mean that you are not allowed to contribute ;) :D
> 
> what i dont understand is that you contribute two times the same issue with different PR. can you align on what we should focus on ?
> 
> [eclipse-tractusx/portal-frontend#1195](https://github.com/eclipse-tractusx/portal-frontend/issues/1195) #1040

Thanks for the feedback @MaximilianHauer 
The links of tickets you have mentioned are two different tickets from two different repositories but for same functionality because I have added one param in response of API and frontend supposed to accommodate that new param in frontend UI.

Please let me know if you have any question.

2024-10-10 08:53 UTC, ntruchsess commented
@tfjanjua @MaximilianHauer As discussed I'm merging this PR as it's save to add those urls to the api-response - please discuss on how to proceed with the corresponding FE-changes in the respective tickets.

2024-10-10 08:53 UTC, merged