feat(bpdm): 1020 bpdm orchestrator roles and svc acc
eclipse-tractusx/portal-backend pull request #1048
Opened 2024-09-30 09:03 UTC by typecastcloud

## Description

Add following BPDM technical user roles for CX Operator:

- BPDM Orchestrator Admin
- BPDM Orchestrator Task Creator
- BPDM Orchestrator Processor Clean
- BPDM Orchestrator Processor CleanAndSync
- BPDM Orchestrator Processor PoolSync

Add BPDM service accounts for CX Operator:

- sa-cl7-cx-1
- sa-cl7-cx-7
- sa-cl25-cx-1
- sa-cl25-cx-2
- sa-cl25-cx-3

## Why

eclipse-tractusx/portal-iam#155 added new BPDM roles and service accounts. Adding these in seeding data allows for configuration via portal.

## Issue

eclipse-tractusx/portal-backend#1020

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [ ] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-09-30 10:03 UTC, typecastcloud commented
Added test cases in issue:
https://github.com/eclipse-tractusx/portal-backend/issues/1020#issuecomment-2382674257

2024-10-01 16:25 UTC, ntruchsess requested changes

2024-10-01 16:25 UTC, ntruchsess commented on src/portalbackend/PortalBackend.Migrations/Seeder/Data/identities.json
> +    "identity_type_id": 2
UserEntityId is nullable:
```suggestion
    "user_status_id": 1,
    "user_entity_id": null,
    "identity_type_id": 2
```

2024-10-01 16:25 UTC, ntruchsess commented on src/framework/Framework.Async/Directory.Build.props
> +    <VersionPrefix>2.11.0</VersionPrefix>
this change seems to be redundant. There seem to be no code-changes in framework modules

2024-10-02 07:19 UTC, typecastcloud commented on src/framework/Framework.Async/Directory.Build.props
> +    <VersionPrefix>2.11.0</VersionPrefix>
Hi @ntruchsess, how do I use the update script to only update relevant versions?

2024-10-02 07:27 UTC, typecastcloud commented on src/framework/Framework.Async/Directory.Build.props
> +    <VersionPrefix>2.11.0</VersionPrefix>
Reverted. Mixed up PR.

2024-10-02 10:27 UTC, evegufy requested changes
Hi @typecastcloud thank you for the PR, awesome!
could you please rebase to main? IMO, that will solve the issue with the currently failing build https://github.com/eclipse-tractusx/portal-backend/actions/runs/11139606243/job/30956625767?pr=1048
could you please also change the PR title to `feat(bpdm): add bpdm orchestrator roles and svc acc` to follow conventional commits?

2024-10-02 10:27 UTC, evegufy commented on src/portalbackend/PortalBackend.Migrations/Seeder/Data/company_service_accounts.json
> +    "description": "Client for the BPDM Portal Gate to consume golden record data from the Pool.",
```suggestion
    "description": "Technical User for the BPDM Portal Gate to consume golden record data from the Pool.",
```

I'll make sure to also update the description for all new service accounts in portal-iam, didn't notice it during the review of https://github.com/eclipse-tractusx/portal-iam/pull/155

2024-10-02 10:27 UTC, evegufy commented on src/portalbackend/PortalBackend.Migrations/Seeder/Data/company_service_accounts.json
> +    "description": "Client for the BPDM cleaning service dummy component to process golden record tasks from the Orchestrator.",
```suggestion
    "description": "Technical User for the BPDM cleaning service dummy component to process golden record tasks from the Orchestrator.",
```

2024-10-02 10:27 UTC, evegufy commented on src/portalbackend/PortalBackend.Migrations/Seeder/Data/company_service_accounts.json
> +    "description": "Client for the BPDM Pool component to process golden record tasks from the Orchestrator.",
```suggestion
    "description": "Technical User for the BPDM Pool component to process golden record tasks from the Orchestrator.",
```

2024-10-02 10:27 UTC, evegufy commented on src/portalbackend/PortalBackend.Migrations/Seeder/Data/company_service_accounts.json
> +    "description": "Client for the BPDM Portal Gate to create and monitor golden record tasks inside the Orchestrator.",
```suggestion
    "description": "Technical User for the BPDM Portal Gate to create and monitor golden record tasks inside the Orchestrator.",
```

2024-10-02 11:35 UTC, typecastcloud commented
> Hi @typecastcloud thank you for the PR, awesome! could you please rebase to main? IMO, that will solve the issue with the currently failing build https://github.com/eclipse-tractusx/portal-backend/actions/runs/11139606243/job/30956625767?pr=1048 could you please also change the PR title to `feat(bpdm): add bpdm orchestrator roles and svc acc` to follow conventional commits?

Title renamed and rebased. Still the same build issue.

When I run tests, order for `/api/administration/registration/Network/companies` in `docs/api/administration-service.yaml` changes.

2024-10-02 12:39 UTC, evegufy approved these changes
lgtm
@ntruchsess could you please review again?

2024-10-07 12:33 UTC, ntruchsess approved these changes

2024-10-07 12:34 UTC, merged