fix(config): extend validation to all properties
eclipse-tractusx/portal-backend pull request #105
Opened 2023-06-26 10:47 UTC by Phil91

## Description

validation for custom attributes EnumEnumerable and DistinctValues extended to validate Properties of properties as well added base implementation for custom enumerable validators

## Why

The current validatio implmentation only validates properties within the given class, but doesn't validate properties of properties.

## Issue

N/A - Jira Issue: CPLP-2698

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2023-06-27 18:53 UTC, ntruchsess requested changes

2023-06-27 18:53 UTC, ntruchsess commented on src/framework/Framework.Models/Validation/BaseOptionEnumerableValidation.cs
> +        var validationResults = new List<ValidationResult>();
same here:
```
        if (property.PropertyType.IsClass)
        {
            foreach (var result in GetValidationErrors(property.PropertyType, configSection.GetSection(propertyName)))
            {
                yield return result;
            }
        }
        else if (property.PropertyType.GetInterfaces().Contains(typeof(IEnumerable)))
        {
            var propertyType = property.PropertyType.GetGenericArguments().FirstOrDefault();
            if (propertyType == null || IgnoreTypes.Contains(propertyType) || propertyType.IsEnum)
                yield break;

            // Validate each item of the enumerable
            var listValues = (IEnumerable)configSection.GetSection(propertyName).Get(property.PropertyType);
            if (listValues != null)
            {
                foreach (var result in Enumerable.Range(0, listValues.ToIEnumerable().Count())
                    .SelectMany(i => GetValidationErrors(propertyType, configSection.GetSection($"{propertyName}:{i}"))))
                {
                    yield return result;
                }
            }
        }
```
or using pure LINQ:
```
    private IEnumerable<ValidationResult> CheckPropertiesOfProperty(IConfiguration configSection, PropertyInfo property, string propertyName) =>
        property.PropertyType switch
        {
            var x when x.IsClass => GetValidationErrors(property.PropertyType, configSection.GetSection(propertyName)),
            var x when x.GetInterfaces().Contains(typeof(IEnumerable)) &&
                    x.GetGenericArguments()
                        .Where(genericType => !genericType.IsEnum)
                        .Except(IgnoreTypes)
                        .IfAny(genericTypes => genericTypes.First(), out var genericType) =>
                            (configSection.GetSection(propertyName).Get(property.PropertyType) as IEnumerable)
                                ?.ToIEnumerable()
                                .Select((_, i) => configSection.GetSection($"{propertyName}:{i}"))
                                .SelectMany(section => GetValidationErrors(genericType!, section)),
            _ => null
        } ?? Enumerable.Empty<ValidationResult>();
```

2023-06-27 18:53 UTC, ntruchsess commented on src/framework/Framework.Web/WebApplicationBuildRunner.cs
> +            LoggingExtensions.EnsureInitialized();
I guess I'm missing something here. Please shed some light on why the LoggingExtensions need to be initialized a second time.

2023-06-27 18:53 UTC, ntruchsess commented on tests/framework/Framework.Models.Tests/ValidationTests.cs
> +        const string configuration = @"
some tests that validates the recursive validation of nested properties would be great. So far those tests were also passed by the previous validator implementation

2023-06-28 08:45 UTC, ntruchsess requested changes

2023-06-28 08:45 UTC, ntruchsess commented on src/framework/Framework.Models/Validation/BaseOptionEnumerableValidation.cs
> +                var errors = Enumerable.Range(0, listValues.ToIEnumerable().Count())
This 'Enumerable.Range(0...Count()) is a cumbersome way to generate index values that are implicitly provided by Select and SelectMany (both are overloaded, see my previous remark where I use it in the pure linq implementation)

2023-06-28 11:04 UTC, Phil91 commented on tests/framework/Framework.Models.Tests/ValidationTests.cs
> +        const string configuration = @"
added some test cases for invalid properties within a property

2023-06-28 11:04 UTC, Phil91 commented on src/framework/Framework.Models/Validation/BaseOptionEnumerableValidation.cs
> +    protected ImmutableArray<Type> IgnoreTypes = new List<Type>
changed.

2023-06-28 11:04 UTC, Phil91 commented on src/framework/Framework.Models/Validation/BaseOptionEnumerableValidation.cs
> +    private IEnumerable<ValidationResult> GetValidationErrors(Type type, IConfiguration configSection)
really like the LINQ implementation!

2023-06-28 11:04 UTC, Phil91 commented on src/framework/Framework.Models/Validation/BaseOptionEnumerableValidation.cs
> +        var validationResults = new List<ValidationResult>();
changed as well.

2023-06-28 11:04 UTC, Phil91 commented on src/framework/Framework.Models/Validation/BaseOptionEnumerableValidation.cs
> +                var errors = Enumerable.Range(0, listValues.ToIEnumerable().Count())
somehow i missed the .select part to get the index

2023-06-28 11:04 UTC, Phil91 commented on src/framework/Framework.Web/WebApplicationBuildRunner.cs
> +            LoggingExtensions.EnsureInitialized();
need to look deeper into that as well. just saw that if we don't have this line, the logger won't write any logs when an error occurs and we'll hit the catch

2023-06-28 13:00 UTC, ntruchsess submitted a review, later dismissed

2023-06-28 13:21 UTC, ntruchsess approved these changes

2023-06-28 13:22 UTC, merged