build(deps): upgrade flurl
eclipse-tractusx/portal-backend pull request #1053
Opened 2024-10-02 08:58 UTC by Phil91

## Description

* upgrade Flurl packages to the latest major
* remove Newtonsoft.Json references from all non test projects

## Why

To upgrade the project dependencies and remove newtonsoft json from non test projects

## Issue

Refs: #1052

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-10-02 09:11 UTC, Phil91 commented on src/keycloak/Keycloak.ErrorHandling/FlurlUntrustedCertExceptionHandler.cs
> +                .ConfigureInnerHandler(chc => chc.ServerCertificateCustomValidationCallback = (_, _, _, _) => true);
This is only enabled on development environments

2024-10-02 09:12 UTC, Phil91 commented
IP Issues are created

[nuget/nuget/-/Flurl.Http.Signed/4.0.2](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/16447)
[nuget/nuget/-/Flurl.Signed/4.0.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/16448)

2024-10-07 21:44 UTC, ntruchsess requested changes
see comments

2024-10-07 21:44 UTC, ntruchsess commented on src/keycloak/Keycloak.Factory/KeycloakFactory.cs
> -        {
did you validate Dictionaries are deserialized preserving the keys? (preserving the case of dictionary-keys was added in https://github.com/eclipse-tractusx/portal-backend/pull/910 and is required to correctly deserialize configuration-data that is not defined as model-class but deserializes into a dictionary. Not preserving the case does break keycloak-seeding).

2024-10-08 11:58 UTC, Phil91 commented on src/keycloak/Keycloak.Factory/KeycloakFactory.cs
> -        {
I've added the test GetIdentityProviderMappers_WithFilledDictionary_ReturnsExpected to check if the keys are preserved which is the case

2024-10-15 19:52 UTC, ntruchsess approved these changes

2024-10-15 20:13 UTC, merged