feat(selfDescription)!: selfDescriptionDocument can be send as json
eclipse-tractusx/portal-backend pull request #107
Opened 2023-06-27 08:04 UTC by Phil91

## Description

the data structure for the endpoints

/api/administration/connectors/clearinghouse/selfDescription 
/api/administration/registration/clearinghouse/selfDescription

have been changed for selfDescriptionDocument from string to JsonDocument

BREAKING CHANGE: data structure for endpoints changed

## Why

The external requests are sending the selfDescription document as json, it's easier to take it as it is and don't have the external services convert the json to a string

## Issue

N/A - Jira Issue: CPLP-2847

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2023-06-28 07:49 UTC, ntruchsess requested changes

2023-06-28 07:49 UTC, ntruchsess commented on src/externalsystems/SdFactory.Library/BusinessLogic/SdFactoryBusinessLogic.cs
> +        data.Content!.WriteTo(writer);
to avoid using the '!'-operator without having locally verified the value is actually non-null please pass data.Content as non-nullable parameter to the method and apply the !-operator on the calling side.

2023-06-28 09:38 UTC, Phil91 commented on src/externalsystems/SdFactory.Library/BusinessLogic/SdFactoryBusinessLogic.cs
> +        data.Content!.WriteTo(writer);
changed

2023-06-29 08:09 UTC, ntruchsess submitted a review, later dismissed

2023-07-14 08:10 UTC, ntruchsess approved these changes

2023-07-14 16:11 UTC, ntruchsess submitted a review, later dismissed

2024-07-31 08:10 UTC, closed without merging