feat(check): additional checks for OPERATOR and confirmed status added in document request endpoint
eclipse-tractusx/portal-backend pull request #1075
Opened 2024-10-15 06:11 UTC by AnuragNagpure

## Description

Currently the endpoint GET: /api/registration/documents/{documentId} only response the document for the user which has uploaded the document. This check should be adjusted with adding check of OPERATOR and company application status confirmed.

## Why

These additional check required for getting document to particular user satisfies the check condition.

## Issue

Link to Github issue.

#1070 

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-10-15 07:31 UTC, Phil91 requested changes
Please add unit tests for `GetDocumentIdWithCompanyUserCheckAsync`

2024-10-15 07:31 UTC, Phil91 commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        if (!documentDetails.IsStatusConfirmed)
It should only throw errors if an application is in status confirmed. Because than the company is onboarded and the operator shouldn't be able to access the companies documents.

2024-10-15 07:31 UTC, Phil91 commented on tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
> +    public async Task GetDocumentAsync_WithConfirmedApplicationStatus_ThrowsForbiddenException()
The title says if status confirmed it should throw an error but currently the test setup is that confirmed is false, please adjust the setup and the business logic afterwards.

2024-10-15 11:04 UTC, AnuragNagpure commented on tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
> +    public async Task GetDocumentAsync_WithConfirmedApplicationStatus_ThrowsForbiddenException()
Adjusted and setup changed

2024-10-15 11:04 UTC, AnuragNagpure commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        if (!documentDetails.IsStatusConfirmed)
changed

2024-10-16 06:37 UTC, Phil91 approved these changes

2024-10-16 06:38 UTC, merged