feat(seeding): add configurable path for seeding data
eclipse-tractusx/portal-backend pull request #108
Opened 2023-06-27 09:04 UTC by Phil91

## Description

The path of the seeding data is now configurable

## Why

To be able to seed ones own data and don't have the need to edit the json files within the Seeder/Data directory one can now mount a directory which than can be configured to be used for the seeding as well.

## Issue

N/A - Jira Issue:  CPLP-2788

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2023-06-27 19:22 UTC, ntruchsess requested changes

2023-06-27 19:22 UTC, ntruchsess commented on src/framework/Framework.Seeding/SeederHelper.cs
> +        var options = new JsonSerializerOptions
this might be declared as static readonly to be shared across multiple invocations. To initialize use the static constructor:
```
    private static readonly JsonSerializerOptions Options = new JsonSerializerOptions
        {
            PropertyNamingPolicy = new SnakeCaseNamingPolicy()
        };

    static SeederHelper()
    {
        Options.Converters.Add(new JsonDateTimeOffsetConverter());
    }
```
(GetDataFile then might access Options directly without parameter)

2023-06-28 09:01 UTC, Phil91 commented on src/framework/Framework.Seeding/SeederHelper.cs
> +        var options = new JsonSerializerOptions
done :)

2023-06-29 07:49 UTC, ntruchsess requested changes

2023-06-29 07:49 UTC, ntruchsess commented on src/framework/Framework.Seeding/SeederSettings.cs
> +    public List<string> DataPaths { get; set; } = new();
use IEnumerable instead of List.
A List allows to dynamically add elements at runtime which has some disadvantages (e.g. it's not threadsafe)
First rule of thumb: If possible declare using the interface not the concrete type.
Second rule of thumb: If a concrete type must be used but dynamic behavior is not explicitly required choose an immutable variant.

2023-06-29 07:49 UTC, ntruchsess commented on tests/portalbackend/PortalBackend.DBAccess.Tests/Setup/TestDbFixture.cs
> +            TestDataEnvironments = new List<string> { "test" },
use new [] { "test" } instead of List. Choosing List is a way to express 'I intend to later add items to this' (which is misleading)

2023-06-29 09:02 UTC, Phil91 commented on src/framework/Framework.Seeding/SeederSettings.cs
> +    public List<string> DataPaths { get; set; } = new();
changed and added.

If additionally added a check within the `CustomSeederRunner` if no paths are set the seeding won't be executed

2023-06-29 09:02 UTC, Phil91 commented on tests/portalbackend/PortalBackend.DBAccess.Tests/Setup/TestDbFixture.cs
> +            TestDataEnvironments = new List<string> { "test" },
done

2023-06-29 20:31 UTC, Phil91 commented on src/framework/Framework.Seeding/CustomSeederRunner.cs
> +    public CustomSeederRunner(IServiceProvider serviceProvider, ILogger<CustomSeederRunner> logger, IOptions<SeederSettings> options) =>
absolutly right. moved.

2023-06-30 06:58 UTC, ntruchsess approved these changes

2023-06-30 06:59 UTC, merged