fix(connector): only provider should update connector
eclipse-tractusx/portal-backend pull request #1086
Opened 2024-10-21 14:13 UTC by dhiren-singh-007

## Description

Updated the validation on update connector api so that only provider can update the connector

## Why

Currently it was not possible for provider to update the connector url which provided be themself only

## Issue

#1085 

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes

2024-10-24 06:33 UTC, Phil91 approved these changes

2024-11-13 13:05 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ConnectorsRepository.cs
> -                c.HostId == companyId,
Since there seems to be no unit tests, please add a unit test to check that the correct value is set.

2024-11-14 15:45 UTC, dhiren-singh-007 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ConnectorsRepository.cs
> -                c.HostId == companyId,
added

2024-11-14 15:46 UTC, ntruchsess requested changes
please see my comment in https://github.com/eclipse-tractusx/portal-backend/issues/1085#issuecomment-2476753684

2024-11-14 16:14 UTC, ntruchsess requested changes

2024-11-14 16:14 UTC, ntruchsess commented on tests/portalbackend/PortalBackend.DBAccess.Tests/ConnectorRepositoryTests.cs
> +        }
the null check is redundant as there's a NotBeNull assert right above. As this is a unit-test the use of '!' operator is more than justified in such cases.
```suggestion
        result!.IsProviderCompany.Should().BeTrue();
```

2024-11-14 16:14 UTC, ntruchsess commented on tests/portalbackend/PortalBackend.DBAccess.Tests/ConnectorRepositoryTests.cs
> +        }
```suggestion
        result.!IsProviderCompany.Should().BeFalse();
```

2024-11-15 08:51 UTC, dhiren-singh-007 commented on tests/portalbackend/PortalBackend.DBAccess.Tests/ConnectorRepositoryTests.cs
> +        }
Thanks @ntruchsess ,Fixed

2024-12-13 10:01 UTC, Phil91 approved these changes
lgtm

2025-02-06 14:01 UTC, ntruchsess approved these changes

2025-02-06 14:23 UTC, merged