bugfix(mailing template): fix additional space
eclipse-tractusx/portal-backend pull request #109
Opened 2023-06-28 05:42 UTC by manojava-gk

## Description

Fix additional space at the end of the password text by adding display property

## Why

extra space at the end of the text

## Issue

NA

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally

2023-06-28 07:16 UTC, ntruchsess approved these changes

2023-06-28 08:20 UTC, evegufy requested changes
unfortunately, I still have the space at the end in my mail client:
![image](https://github.com/eclipse-tractusx/portal-backend/assets/46191613/c5bd6995-a581-4b7f-8e2e-3a70a27593c5)

2023-06-30 10:00 UTC, evegufy approved these changes

2023-06-30 10:00 UTC, evegufy commented
successfully tested:
![image](https://github.com/eclipse-tractusx/portal-backend/assets/46191613/95458f6f-d844-45b2-9359-2d9b0deab3fd)

2023-06-30 10:01 UTC, merged