feat(connector): connector controller change url added
eclipse-tractusx/portal-backend pull request #1094
Opened 2024-10-22 05:24 UTC by AnuragNagpure

## Description

in endpoint api/administration/Connectors/{connectorId}/connectorUrl
open the table portal.documents, search for the connectors.self_description_document_id inside the field id and set the status to "INACTIVE"
now trigger the SD factory endpoint 

## Why

The backend logic will set the current connector assigned self-description to "INACTIVE" - no matter which status the document has currently (retrieve via the table portal.connectors the linked self-description document from the attribute connectors.self_description_document_id.

## Issue

#549 

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-10-24 06:32 UTC, Phil91 requested changes

2024-10-24 06:32 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
> +            documentRepository.AttachAndModifyDocument((Guid)connector.SelfDescriptionDocumentId!, null, doc =>
Please change to .Value for easier readability

```suggestion
            documentRepository.AttachAndModifyDocument(connector.SelfDescriptionDocumentId.Value, null, doc =>
```

2024-10-24 06:32 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
> +        var selfDescriptionDocumentUrl = $"{_settings.SelfDescriptionDocumentUrl}/{connector.SelfDescriptionCompanyDocumentId}";
Since the `connector.SelfDescriptionCompanyDocumentId` is nullable this should be checked... otherwise the callback from the sdFactory will always fail... If it is null you can throw a conflict exception

2024-10-24 06:32 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
> +            .RegisterConnectorAsync(connectorId, selfDescriptionDocumentUrl, connector.Bpn!, cancellationToken)
The bpn should be checked for null as well.

2024-10-24 06:32 UTC, Phil91 commented on tests/administration/Administration.Service.Tests/BusinessLogic/ConnectorsBusinessLogicTests.cs
>      }
Please also check that the sdFactory was called as expected

2024-10-24 06:32 UTC, Phil91 commented on tests/administration/Administration.Service.Tests/BusinessLogic/ConnectorsBusinessLogicTests.cs
After you added the null checks for bpn and CompanySelfDescriptionDocument please provide unit tests as well

2024-10-24 11:05 UTC, AnuragNagpure commented on src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
> +            documentRepository.AttachAndModifyDocument((Guid)connector.SelfDescriptionDocumentId!, null, doc =>
Changed

2024-10-24 11:05 UTC, AnuragNagpure commented on src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
> +        var selfDescriptionDocumentUrl = $"{_settings.SelfDescriptionDocumentUrl}/{connector.SelfDescriptionCompanyDocumentId}";
Added the check

2024-10-24 11:06 UTC, AnuragNagpure commented on src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
> +            .RegisterConnectorAsync(connectorId, selfDescriptionDocumentUrl, connector.Bpn!, cancellationToken)
there is already check for bpn with error msg

2024-10-24 11:06 UTC, AnuragNagpure commented on tests/administration/Administration.Service.Tests/BusinessLogic/ConnectorsBusinessLogicTests.cs
>      }
added

2024-11-05 08:21 UTC, Phil91 approved these changes

2024-11-05 08:23 UTC, merged