Tests/cplp 2513/GitHub actions
eclipse-tractusx/portal-backend pull request #110
Opened 2023-06-28 07:16 UTC by irinamesh

## Description

Please include a summary of the change.

## Why

Please include an explanation of why this change is necessary as well as relevant motivation and context. List any dependencies that are required for this change.

## Issue

Link to Github issue.

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [ ] I have created and linked IP issues or requested their creation by a committer
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

2023-07-03 11:08 UTC, jjeroch commented
I suggest to add a link to the pr of the "assets" repo

2023-07-04 09:11 UTC, evegufy requested changes
@aaschmid @irinamesh Contrary to what I said in todays daily, I didn't create directly license review requests at the EF IP team for the new dependencies in this PR, but I did pre-vet them, and did find some significant issues:
nuget/nuget/-/RestAssured.Net/2.8.1 --> not OK because tagged or release sources are missing in source code repo, can you please find an alternative (also necessary due to next line)?
nuget/nuget/-/Newtonsoft.Json.Schema/3.0.15 --> (dependency of RestAssured.Net) not OK: GNU Affero General Public License or Commercial License. This is incompatible with our project.
nuget/nuget/-/Bitmap.Net/1.0.1 --> not OK because tagged or release sources are missing in source code repo, but 1.0.1 appears at least to be the latest version so it COULD be OK for the team IP to upload the current state from master to the IP issue. But that's just could, is there an easy alternative?
nuget/nuget/-/HtmlAgilityPack/1.11.46 --> OK
nuget/nuget/-/SixLabors.ImageSharp/3.0.1 --> OK
nuget/nuget/-/Stubble.Core/1.10.8 (dependency of RestAssured.Net) --> OK

2023-07-04 09:52 UTC, aaschmid commented
@evegufy: Thanks for the hints. `nuget/nuget/-/Bitmap.Net/1.0.1` is not required anymore such that we will remove it.

For `nuget/nuget/-/RestAssured.Net/2.8.1` the case is much more difficult. `RestAssured` is the base library for all the tests and I haven't found an easy alternative with similar syntax. However, we could ask the repo owner to create the required tags.

For `nuget/nuget/-/Newtonsoft.Json.Schema/3.0.15`, would it be an option to exclude the dependency from being transitively excluded? (might also cause `RestAssured` to not work properly anymore) @irinamesh @chaupkatng or do we need JSON schema functionality?

2023-07-05 12:33 UTC, evegufy requested changes
@irinamesh I just ran dotnet format and there are a couple of issues:
https://github.com/eclipse-tractusx/portal-backend/actions/runs/5461453783/jobs/9945408008
Could you please solve those issues?
You could try solving those issues by running:
`dotnet format .\src --no-restore`
If that doesn't work, you could investigate with:
`dotnet format .\src --verify-no-changes --no-restore`

Sonarcloud also revealed 2 Code Smells, could you please solve them as well?:
https://sonarcloud.io/project/issues?id=eclipse-tractusx_portal-backend&pullRequest=110&resolved=false&types=CODE_SMELL

2023-07-05 15:18 UTC, evegufy commented
@irinamesh good! there are now much less findings from dotnet format. Could you please take care of the remaining ones?:
https://github.com/eclipse-tractusx/portal-backend/actions/runs/5465127825/jobs/9950217213?pr=110

2023-07-05 16:09 UTC, evegufy requested changes
Please move the entire EndToEnd Testing Project out of the src and into the tests directory, ideally into a 'endtoend' directory.

Please also comply with our namespace naming convention, which in this case would be something like 'Org.Eclipse.TractusX.Portal.Backend.EndToEnd.Tests'

2023-07-05 16:17 UTC, evegufy requested changes

2023-07-05 16:17 UTC, evegufy commented on .github/workflows/unit.tests-formatting.yml
> +        run: dotnet test src --filter FullyQualifiedName!~EndToEnd --no-restore --verbosity normal
I tested this locally (as the workflow doesn't current get to this step due to the dotnet format issue) and I'm generally a bit skeptical if this filter will work, but I think it won't work for sure without escaping of '!'  https://learn.microsoft.com/en-us/dotnet/core/testing/selective-unit-tests?pivots=mstest#character-escaping and without defining the proper namespace.

I'd suggest to change to this:
`dotnet test src --filter FullyQualifiedName\!~EndToEnd.Tests --no-restore --verbosity normal
`
Or respectively to `dotnet test src --filter FullyQualifiedName\!~Org.Eclipse.TractusX.Portal.Backend.EndToEnd.Tests --no-restore --verbosity normal` once the proper namespace naming convention is used.

2023-07-06 14:03 UTC, evegufy requested changes

2023-07-06 14:03 UTC, evegufy commented on tests/endtoend/EndToEnd.Tests.csproj
> +    <PackageReference Include="RestAssured.Net" Version="2.8.1"/>
@irinamesh could you please update to '4.0.0-beta.1'? 
The maintainer to the library provider a version without `Newtonsoft.Json.Schema` :)

2023-07-06 14:15 UTC, evegufy requested changes

2023-07-06 14:15 UTC, evegufy commented on tests/endtoend/EndToEnd.Tests.csproj
> +    <PackageReference Include="HtmlAgilityPack" Version="1.11.46" />
@irinamesh thanks for the quick change! The restore and build fails now with:
https://github.com/eclipse-tractusx/portal-backend/actions/runs/5476443089/jobs/9974024047#step:5:46
maybe you also need to update to 1.11.49 here.

2023-07-07 08:08 UTC, evegufy commented
I created the following IP issues:
[main] INFO A review is required for nuget/nuget/-/HtmlAgilityPack/1.11.49.
[main] INFO A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9293 .
[main] INFO A review is required for nuget/nuget/-/RestAssured.Net/4.0.0-beta.1.
[main] INFO A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9294 .
[main] INFO A review is required for nuget/nuget/-/SixLabors.ImageSharp/3.0.1.
[main] INFO A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9295 .
[main] INFO A review is required for nuget/nuget/-/ReportPortal.XUnit/2.4.5.
[main] INFO A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9296 .
[main] INFO A review is required for nuget/nuget/-/Stubble.Core/1.10.8.
[main] INFO A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9297 .
[main] INFO A review is required for nuget/nuget/-/ReportPortal.Client/3.4.0.
[main] INFO A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9298 .
[main] INFO A review is required for nuget/nuget/-/NHamcrest/3.2.0.
[main] INFO A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9299 .
[main] INFO A review is required for nuget/nuget/-/NJsonSchema/10.9.0.
[main] INFO A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9300 .
[main] INFO A review is required for nuget/nuget/-/ReportPortal.Shared/3.5.0.
[main] INFO A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9301 .

The IP Issue for [nuget/nuget/-/Namotion.Reflection/2.1.2](https://github.com/eclipse-tractusx/portal-backend/actions/runs/5476589240/jobs/9974356102#step:9:16) wasn't created yet due to open issue for the source: https://github.com/RicoSuter/Namotion.Reflection/issues/131
If the source isn't provided with a tag, I'll create the IP issue anyways and upload the current state from the master branch to the issue as we're using the latest version and in the hopes that the IP Team is fine with that.

2023-07-07 12:24 UTC, evegufy commented
@irinamesh Here is the first workflow run from the fork: https://github.com/catenax-ng/tx-portal-backend/actions/runs/5486098873
I didn't look into it more deeply, could you please check out the issues?
IMO the connection to the reportportal didn't work among other.

cc: @jjeroch

2023-07-10 10:10 UTC, aaschmid commented
I adjusted the ReportPortal config stuff, but cannot retrigger the test case. Even though, most tests run successfully, I think 2-4 should not fail normally. Irina and I will have a look at them tomorrow.

2023-07-10 15:51 UTC, evegufy commented
@aaschmid just fyi, I created the IP Issue for [nuget/nuget/-/Namotion.Reflection/2.1.2](https://github.com/eclipse-tractusx/portal-backend/actions/runs/5476589240/jobs/9974356102#step:9:16) and uploaded to current state of the release branch as tag wasn't pushed up to now.
https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9320#note_1178543

2023-07-11 08:39 UTC, evegufy commented
@aaschmid @irinamesh I did a test run with the current state https://github.com/catenax-ng/tx-portal-backend/actions/runs/5517320395
could you please check?
the connection to reportportal is working now.

2023-07-11 08:40 UTC, aaschmid commented
Thanks for the run, we will have a look tomorrow.

2023-07-11 13:31 UTC, basdijkstra commented
Just an FYI for @aaschmid and @evegufy: RestAssured .Net now has an official 4.0.0 release, so you won't need to use a beta anymore: https://www.nuget.org/packages/RestAssured.Net/4.0.0

2023-07-11 14:48 UTC, evegufy commented
@irinamesh I was able to check regarding assertions, could you please change to fluent assertion? as this appears to be our mainstream

2023-07-12 09:23 UTC, evegufy requested changes
@irinamesh as just discussed, we do have license issue

2023-07-12 09:23 UTC, evegufy commented on tests/endtoend/EndToEnd.Tests.csproj
> +    <PackageReference Include="SixLabors.ImageSharp" Version="3.0.1" />
@irinamesh as just discussed, could you please remove the SixLabors.ImageSharp library?
A license issue was discovered and due to that the library just got a bad effort-benefit ratio.
https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9295#note_1179559

2023-07-12 09:28 UTC, irinamesh commented on tests/endtoend/EndToEnd.Tests.csproj
> +    <PackageReference Include="SixLabors.ImageSharp" Version="3.0.1" />
Yes, thanks for the info. I'll remove it and give you update.

2023-07-12 09:29 UTC, evegufy requested changes

2023-07-12 09:29 UTC, evegufy commented on tests/endtoend/EndToEnd.Tests.csproj
> +    <PackageReference Include="RestAssured.Net" Version="4.0.0-beta.1" />
@irinamesh could you please also change to the newly released 4.0.0 version?

2023-07-12 09:37 UTC, irinamesh commented
Regarding connection to the ReportPortal and test results in it it works as expected, but i need to check why registration scenarios fail. I'll be back with an update on this issue till Friday.

2023-07-12 09:44 UTC, irinamesh commented on tests/endtoend/EndToEnd.Tests.csproj
> +    <PackageReference Include="RestAssured.Net" Version="4.0.0-beta.1" />
done!

2023-07-13 11:01 UTC, basdijkstra commented
@irinamesh is there a reason you extracted the deserialization of response payloads in the E2E tests into a separate class in https://github.com/eclipse-tractusx/portal-backend/pull/110/commits/f1a1b7ff2d12f2f67019a805c6dd9dea58b980da and https://github.com/eclipse-tractusx/portal-backend/pull/110/commits/84ff27e12c9806d08e4e779a66e3d11f246a3cfd ?

Not because I want to question your decision, but because RestAssured does support (de-)serialization using `DeserializeTo()`, and you can even pass in custom `Newtonsoft.Json.JsonSerializerSettings`. `DeserializeTo()` replaces `As()` and works the same, I see you used `As()` before.

See also https://github.com/basdijkstra/rest-assured-net/wiki/Usage-Guide#deserializing-a-response-payload-into-a-c-object

Just curious to see if there's anything that you think should be improved in RestAssured .Net, that's all! Thanks :)

2023-07-13 14:38 UTC, evegufy commented
Tag for Namotion.Reflection/2.1.2 has been pushed and IP issue has been updated https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9320#note_1181119

2023-07-14 06:35 UTC, irinamesh commented
@basdijkstra hi and first thank you for a great framework! I really enjoy working with it as it covers a lot of functionality and really straight forward for understanding!

```As<type>()``` seems not to work appropriate for us as System.Text.Json.Serialization is used for data models. In this case json property names seem to be not parsed correctly. So we make a workaround:

````
private static readonly JsonSerializerOptions JsonSerializerOptions = new()
    {
        PropertyNameCaseInsensitive = true, Converters = { new JsonStringEnumConverter() }
    };

    public static T? DeserializeData<T>(string jsonString)
    {
        var deserializedData = JsonSerializer.Deserialize<T>(jsonString, JsonSerializerOptions);
        return deserializedData;
    }
```
If you have a better solution, I would appreciate information on it.

2023-07-14 06:44 UTC, irinamesh commented
@evegufy @aaschmid @jjeroch 

As discussed yesterday I implement the following changes:
 - remove SixLabors.ImageSharp library -> only documents and images from test data directory are now used for the tests;
 - fix registration scenarios: it seems that there was an update in the structure of the invitation email. I adjust search of password in that way that we search for the password in the first paragraph after the paragraph with the phrase "Below you can find your password". I hope that it will be a sustainable solution against possible adjustments in the invitation email;
 - partly fix registration scenario with bpn and add test data file for it - it seems that the endpoint for getting application detail by company name doesn't provide the information if company name contains a special character, for example "&" (i provide more information per email);
 - add a separate step to workflow to run all tests;
 - update documentation (s. link to PR).

2023-07-14 09:21 UTC, basdijkstra commented
> @basdijkstra hi and first thank you for a great framework! I really enjoy working with it as it covers a lot of functionality and really straight forward for understanding!
> 
> `As<type>()` seems not to work appropriate for us as System.Text.Json.Serialization is used for data models. In this case json property names seem to be not parsed correctly. So we make a workaround:
> 
> ```
> private static readonly JsonSerializerOptions JsonSerializerOptions = new()
>     {
>         PropertyNameCaseInsensitive = true, Converters = { new JsonStringEnumConverter() }
>     };
> 
>     public static T? DeserializeData<T>(string jsonString)
>     {
>         var deserializedData = JsonSerializer.Deserialize<T>(jsonString, JsonSerializerOptions);
>         return deserializedData;
>     }
> ```
> If you have a better solution, I would appreciate information on it.
> ```

Hey @irinamesh, the challenge here is that you're using `System.Text.Json` for (de-)serialization while RestAssured.Net uses `Newtonsoft.Json` :)

I think `Newtonsoft.Json` use case insensitive (de-)serialization by default, but I don't know exactly how it handles converting enum values to strings and vice versa. If you can configure that using `JsonSerializerSettings` in `Newtonsoft.Json` you can set those using `UsingJsonSerializerSettings()`, see https://github.com/basdijkstra/rest-assured-net/wiki/Usage-Guide#deserializing-a-response-payload-into-a-c-object

But I can't guarantee that you'll be able to do exactly what you want with `Newtonsoft.Json`, so I think your safest bet is to keep things as they are right now.

I'll raise an issue on the RestAssured.Net repo to remind myself to dive deeper into this when I return from my holidays.

Maybe at some point I'll switch from `Newtonsoft.Json` to `System.Text.Json`, as that's built into .NET instead of being an external dependency. Even better would be if I can find a way to support both, but that might make things a little more complex.

Thank you so much for your explanation, gives me some food for thought. And thank you, too, for the kind words. It means a lot to me seeing people use this library in their projects.

2023-07-17 05:23 UTC, jjeroch requested changes
**CHANGE REQUEST**
Report Portal - Test Execution run names are not sufficient. We should use a human readable name
Current implementation:
<img width="491" alt="image" src="https://github.com/eclipse-tractusx/portal-backend/assets/94133633/053ecd0c-851b-4355-9794-b8d91f59a054">

Expectation: easy, human readable name where the test scope is understood.

Information such as used test data (which seem to currently be located in the test name) should be stored in the logs (see screenshot below)

<img width="1401" alt="image" src="https://github.com/eclipse-tractusx/portal-backend/assets/94133633/1d6910aa-25b0-41aa-b113-cd473ad2f762">

2023-07-17 05:24 UTC, jjeroch reviewed
**BUG**

Please check the report portal - https://portal-reportportal.dev.demo.catena-x.net/ui/#superadmin_personal/launches/all/12/330/332/log

Looks broken: 
<img width="1383" alt="image" src="https://github.com/eclipse-tractusx/portal-backend/assets/94133633/4e8e634e-1a92-4b4c-9495-f2f7d5074175">

2023-07-17 07:29 UTC, aaschmid commented
@jjeroch due to test names, I can create something like `$CHOOSEN_NAME(testEntry: $SOME_VALUE_FROM_TEST_DATA)`, e.g. `Scenario Create New App(testEntry: TestAutomation - MyTestApp)` whereas `"TestAutomation - MyTestApp"` is the `title` in `TestDataCreateApp.json`.

![grafik](https://github.com/eclipse-tractusx/portal-backend/assets/567653/3fee6773-14d6-450a-b54d-0da8e6d78a08)

I also might have found a solution for not prefixing by namespace and test class names (here `Org.Eclipse.TractusX.Portal.Backend.EndToEnd.Tests` and `CreateNewTestAppSzenario`), but this needs further investigation if affecting also unit test cases ...

Would this satisfy your requirements? And if yes, do you have any preference of the names?

2023-07-17 07:30 UTC, Phil91 requested changes

2023-07-17 07:30 UTC, Phil91 commented on tests/endtoend/InterfacePartnerHealthCheck/SdFactoryEndPointTests.cs
> +                "{\"externalId\": \"TestAutomation\",\"type\": \"LegalPerson\",\"holder\": \"BPNL000000000000\",\"issuer\": \"CAXSDUMMYCATENAZZ\",\"registrationNumber\": [{\"type\": \"local\",\"value
Please use the `SdFactoryRequestModel` and serialize it

2023-07-17 07:30 UTC, Phil91 commented on tests/endtoend/NotificationInitScenario/ModifyCoreUserRoleScenario.cs
> +public class ModifyCoreUserRoleScenario : EndToEndTestBase
Please add proper null handling

2023-07-17 07:30 UTC, Phil91 commented on tests/endtoend/NotificationInitScenario/NotificationContent.cs
> +    string offerId, string coreOfferName, string username, string removedRoles, string addedRoles);
Please use uppercase naming for record properties and add line breaks for readability

2023-07-17 07:30 UTC, Phil91 commented on tests/endtoend/RegistrationScenarios/BpdmContent.cs
> +public record BpdmContent(float score, BpdmLegalEntityDto legalEntity);
Please use uppercase for record properties

2023-07-17 07:30 UTC, Phil91 commented on tests/endtoend/RegistrationScenarios/RegistrationEndpointHelper.cs
> +public static class RegistrationEndpointHelper
Please add proper null checks for properties that could be null.
Some methods define a return type as non nullable but return a nullable value instead.

2023-07-17 07:30 UTC, Phil91 commented on tests/endtoend/RegistrationScenarios/RegistrationScenarios.cs
> +    public async Task Scenario1_HappyPathRegistrationWithoutBpn(TestDataRegistrationModel testEntry)
Some properties could be null, please add a proper null handling

2023-07-18 12:13 UTC, evegufy commented
@irinamesh as discussed this morning here a new workflow run: https://github.com/catenax-ng/tx-portal-backend/actions/runs/5587068138

All dependencies are approved now :) could you please download the updated DEPENDENCIES file from the workflow artifact here and commit it (replace of existing DEPENDENCIES file on root level)?
https://github.com/catenax-ng/tx-portal-backend/actions/runs/5586903202
Then the check by workflow should run successfully.

2023-07-19 08:47 UTC, aaschmid commented on tests/endtoend/AuthFlow/TempMailApiRequests.cs
> +        var passwordMessage = messages.First(item => item.mail_subject.Contains("Password required"));
I see multiple options for this:

1. Directly check for null and throw Exception with proper message if so.
2. Assert for null and use `!` operator on next occurrence
3. Create two methods `DeserializeData` which checks for null internally and `NullableDeserialzeData` which has the current behavior (maybe first method with new argument for proper error message).

I am unsure as each has its benefits and disadvantages. Do you have any preference?

2023-07-19 08:52 UTC, aaschmid commented on tests/endtoend/InterfacePartnerHealthCheck/ClearinghouseEndToEndTests.cs
> +                "{\"callbackUrl\":\"https://portal-backend.dev.demo.catena-x.net/api/administration/registration/clearinghouse\",\"participantDetails\":{\"name\":\"SmokeTest CH\",\"city\":\"Stuttgart
I think the url should also not be part of the code, such that I will move it to the environment variables.

Also, this contains some `IdentityDetails` for which I want to ask, if that is ok to keep them within the code directly.

2023-07-19 18:40 UTC, irinamesh commented on tests/endtoend/InterfacePartnerHealthCheck/ClearinghouseEndToEndTests.cs
> +                "{\"callbackUrl\":\"https://portal-backend.dev.demo.catena-x.net/api/administration/registration/clearinghouse\",\"participantDetails\":{\"name\":\"SmokeTest CH\",\"city\":\"Stuttgart
@jjeroch could you please take a look at this? As per initial requirements body could be hardcoded in this case. As we don't use hardcoded URLs anymore it makes sense to define it with an environment variable. Can IdentityDetails be defined directly or should it also be moved from the code?

2023-07-19 18:46 UTC, irinamesh commented
> @jjeroch due to test names, I can create something like `$CHOOSEN_NAME(testEntry: $SOME_VALUE_FROM_TEST_DATA)`, e.g. `Scenario Create New App(testEntry: TestAutomation - MyTestApp)` whereas `"TestAutomation - MyTestApp"` is the `title` in `TestDataCreateApp.json`.
> 
> ![grafik](https://user-images.githubusercontent.com/567653/253875462-3fee6773-14d6-450a-b54d-0da8e6d78a08.png)
> 
> I also might have found a solution for not prefixing by namespace and test class names (here `Org.Eclipse.TractusX.Portal.Backend.EndToEnd.Tests` and `CreateNewTestAppSzenario`), but this needs further investigation if affecting also unit test cases ...
> 
> Would this satisfy your requirements? And if yes, do you have any preference of the names?

@aaschmid thank you

@jjeroch here are screenshots that show how can it look in ReportPortal:

Test scenarios without test data:
<img width="689" alt="image" src="https://github.com/eclipse-tractusx/portal-backend/assets/130034909/cea13f53-b9e0-42e2-8577-2dbf7f0700e6">

Test scenario with test data:
<img width="686" alt="image" src="https://github.com/eclipse-tractusx/portal-backend/assets/130034909/7cbe22da-0dbb-4300-81b2-12f93d921c05">

Do you have any suggestions for improvement?

2023-07-19 18:54 UTC, irinamesh commented
> **BUG**
> 
> Please check the report portal - https://portal-reportportal.dev.demo.catena-x.net/ui/#superadmin_personal/launches/all/12/330/332/log
> 
> Looks broken: <img alt="image" width="1383" src="https://user-images.githubusercontent.com/94133633/253858443-4e8e634e-1a92-4b4c-9495-f2f7d5074175.png">

Yes, looks broken also by me. As I see it affects only this page and reload does not help. If it is needed, we can create an issue here: https://github.com/reportportal/reportportal/issues, but I'm not sure if they can reproduce this.

2023-07-19 19:01 UTC, irinamesh commented
> But I can't guarantee that you'll be able to do exactly what you want with `Newtonsoft.Json`, so I think your safest bet is to keep things as they are right now.
> 
> I've raised [basdijkstra/rest-assured-net#99](https://github.com/basdijkstra/rest-assured-net/issues/99) to remind myself to dive deeper into this when I return from my holidays. Feel free to add a comment there if you've got specific ideas or suggestions around this.
> 
> Maybe at some point I'll switch from `Newtonsoft.Json` to `System.Text.Json`, as that's built into .NET instead of being an external dependency. Even better would be if I can find a way to support both, but that might make things a little more complex.
> 
> Thank you so much for your explanation, gives me some food for thought. And thank you, too, for the kind words. It means a lot to me seeing people use this library in their projects.

@basdijkstra thank you too! yes, we want to be on the safe side, that's why I've decided on this implementation. We'd love to hear about updates and new releases. Have a good holiday! You're doing a great job!

2023-07-19 19:05 UTC, irinamesh commented on tests/endtoend/RegistrationScenarios/UnHappyPathRegistrationWithoutDocument.cs
> +public class UnHappyPathRegistrationWithoutDocument
UnHappyPathRegistrationScenario was not fully implemented as fix in productive code was necessary. I suppose we can delete the whole file as we have all needed information in RegistrationEndpointHelper and RegistrationScenarios.

2023-07-19 19:11 UTC, irinamesh commented on tests/endtoend/AuthFlow/OneSecMailApiRequests.cs
> +public class OneSecMailApiRequests
@aaschmid fyi: this file can be deleted. we refused to use OneSecMailApi as it has no authentication scheme.

2023-07-20 19:44 UTC, jjeroch commented
> Test scenarios without test data:

@irinamesh  thanks. Lets take "Test scenarios without test data" the test data itself should be stored in the logs (means when clicking on the Test Scenario and looking up the details.

2023-07-21 07:08 UTC, Phil91 commented on tests/endtoend/AuthFlow/TempMailApiRequests.cs
> +        var passwordMessage = messages.First(item => item.mail_subject.Contains("Password required"));
For me all options would be fine, I think I'd go with option 1.

Regarding the errors @evegufy do we want the error message to contain the urls?

2023-07-22 12:20 UTC, evegufy commented
@irinamesh @jjeroch here the 1rst run with int env https://github.com/catenax-ng/tx-portal-backend/actions/runs/5630519459

2023-07-31 11:47 UTC, Phil91 requested changes
Closed the fixed issues, thanks for that @aaschmid
found one minor additional point. there are two open comments left, besides of that everything looks fine.

Is it planned to merge the fluentAssertion branch into this one?

2023-07-31 11:47 UTC, Phil91 commented on tests/endtoend/TestDataHelper.cs
> +            testDataSet.Add(new TestDataRegistrationModel(companyDetailData, updateCompanyDetailData, companyRoles!,
Since companyRoles are only set in one case, we should maybe change it to an empty List when initializing, if no key equals companyRoles we'll have an unhandled exception here, same as for documentName, we should maybe initialize it with string.Empty

2023-07-31 12:29 UTC, aaschmid commented on tests/endtoend/TestDataHelper.cs
> +            testDataSet.Add(new TestDataRegistrationModel(companyDetailData, updateCompanyDetailData, companyRoles!,
I agree. As I checked the usage of `DocumentName`, I saw it's usage is aware of `?` and check it's nullablility correctly such that I removed the exception and the `!` for it. 

See commit with hash 2b77d1e61 (tackles also the comment I missed out, thanks for the hint).

2023-07-31 12:29 UTC, aaschmid commented
@Phil91 thanks for your feedback. I now also cherry-picked my changes due to fluent assertion and pushed it here - just didn't want to interrupt the review process with a lot of new changes -, see commit hash d8d9f2b38.

The remaining cherry-pick is about test names which I also prepared as separate branch to cherry-pick from. My [first version](https://github.com/TNG-Catena-X/tx-portal-backend/commit/0dd100d67dd7ce1b9bfeba7707e3ecc21dce2c19) was already reviewed, and I incorporated the changes in [here](https://github.com/TNG-Catena-X/tx-portal-backend/commit/fefab7684). Remaining question is about the displaying of test data, see first commit and comments there.

2023-07-31 14:11 UTC, Phil91 commented on tests/endtoend/TestDataHelper.cs
> +            testDataSet.Add(new TestDataRegistrationModel(companyDetailData, updateCompanyDetailData, companyRoles!,
@aaschmid  thanks :) i'll have a look at it

2023-08-02 09:56 UTC, Phil91 requested changes

2023-08-02 09:56 UTC, Phil91 commented on tests/endtoend/NotificationInitScenario/ModifyCoreUserRoleScenario.cs
> +        notificationAddContent?.Username.Should().Be(_username);
We could add a notificationAddContent.Should().NotBeNull() here, than we could change the first usage to notificationAddContent!.Username ... and remove the ? from the other two usages - same applies for notificationRemoveContent

2023-08-02 09:56 UTC, Phil91 commented on tests/endtoend/RegistrationScenarios/RegistrationScenarios.cs
> +        applicationDetails?.ApplicationId.ToString().Should().Be(applicationId);
```suggestion
        applicationDetails.Should().NotBeNull();
        applicationDetails!.CompanyApplicationStatusId.Should().Be(CompanyApplicationStatusId.SUBMITTED);
        applicationDetails.ApplicationId.ToString().Should().Be(applicationId);
```

2023-08-02 09:56 UTC, Phil91 commented on tests/endtoend/AuthFlow/DevMailApiRequests.cs
> +        Assert.True(result); // fool `dotnet format`
can this be removed?

2023-08-02 12:50 UTC, aaschmid commented on tests/endtoend/NotificationInitScenario/ModifyCoreUserRoleScenario.cs
> +        notificationAddContent?.Username.Should().Be(_username);
I am fine with either way -> changed as you suggested.

2023-08-02 12:59 UTC, aaschmid commented on tests/endtoend/AuthFlow/DevMailApiRequests.cs
> +        Assert.True(result); // fool `dotnet format`
Thanks for pointing out, done. 
(I thought that I tried it while migrating to fluent assertions and got a warning about it. However, this seems not to be the case (meanwhile or I was to blind last time ;-) )

Trying this again lead me to another warning in `ServiceAccountCUDScenarios` which I also fixed :-)

2023-08-02 13:00 UTC, aaschmid commented on tests/endtoend/AuthFlow/DevMailApiRequests.cs
> +        Assert.True(result); // fool `dotnet format`
Review comments incorperated, see b4bcc78

2023-08-03 12:53 UTC, aaschmid commented
@Phil91 as discussed today, I rebased and squashed everything onto current `dev` branch. In addition, I cherry-picked the changed test names on request of Julia in commit 704eb9f368c6e9a8353bcaeeb26bbfbff953bd79.

The squash also contains the small changes requested by Julia. Unfortunately, I squashed them as well such that I will describe them shortly here. If that is not sufficient please let me now:
* Test case: `CreateNewTestAppScenario.CreateAppRequest`
* Instead of calling three different methods (one would have been now) for three different document types, I created `UploadAppDocumentOrImage` taking the `documentType` directly from the available enum and call this method three times with different parameters.

2023-08-11 08:53 UTC, evegufy approved these changes

2023-08-11 09:22 UTC, Phil91 approved these changes

2023-08-17 06:52 UTC, merged