feat(DbUpdate)!- View for CompanyLinkedServiceAccounts
eclipse-tractusx/portal-backend pull request #111
Opened 2023-06-28 08:28 UTC by qxz2mqe

## Description

Created View CompanyLinkedServiceAccountsView.

## Why

Created View to simplify the logic to fetch managed tech user for provider and owner.

## Issue

CPLP-2841.

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [ ] I have commented my code, particularly in hard-to-understand areas

2023-07-06 09:04 UTC, Phil91 requested changes
Please rebase to the latest dev, you than need to recreate the migration since the migration were merged into one on the dev branch

2023-07-06 09:38 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.Migrations/Migrations/20230628064201_CPLP-2841-CompanyLinkedServiceAccountsView.cs
> +            migrationBuilder.Sql(@"CREATE OR REPLACE VIEW CompanyLinkedServiceAccount AS
@Phil91 I am trying to reach you on teams and via email but looks like your emailid got changed and my messages are not delivered. I want to discuss about your review comments . Can you ping me on teams

2023-07-07 07:23 UTC, Phil91 requested changes
Please add some UnitTests to check whether the View is queryable. You can have a look at the `OfferSubscriptionViewTests` for reference in PR #129

2023-07-07 07:23 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Migrations/20230706131002_CPLP-2841-CompanyLinkedServiceAccountsView.cs
> +               i.company_id as owners,
the column needs to be named exactly like the property in the model

```suggestion
               i.company_id as owner,
```

2023-07-07 07:23 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Migrations/20230706131002_CPLP-2841-CompanyLinkedServiceAccountsView.cs
> +            migrationBuilder.Sql(@"CREATE OR REPLACE VIEW CompanyLinkedServiceAccounts AS
Since we're using schemas we should use them for the views as well to have them at the same schema as all data
```suggestion
            migrationBuilder.Sql(@"CREATE OR REPLACE VIEW portal.CompanyLinkedServiceAccounts AS
```

2023-07-07 07:23 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Migrations/20230706131002_CPLP-2841-CompanyLinkedServiceAccountsView.cs
> +            migrationBuilder.Sql(@"DROP VIEW [IF EXISTS] CompanyLinkedServiceAccounts");
the down method currently fails because of the [] please remove them and use the schema as well

```suggestion
            migrationBuilder.Sql("DROP VIEW IF EXISTS portal.CompanyLinkedServiceAccounts");
```

2023-07-07 07:23 UTC, Phil91 commented on src/portalbackend/PortalBackend.PortalEntities/PortalDbContext.cs
> +             .ToView(nameof(CompanyLinkedServiceAccounts))
the .ToView method has an overload to specify the schema.

```suggestion
             .ToView(nameof(CompanyLinkedServiceAccounts), "portal")
```

2023-07-07 07:47 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.Migrations/Migrations/20230706131002_CPLP-2841-CompanyLinkedServiceAccountsView.cs
> +               i.company_id as owners,
Owner is reserve keyword in sql so i am keeping it as owners and also changing it in model

2023-07-07 07:56 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.Migrations/Migrations/20230706131002_CPLP-2841-CompanyLinkedServiceAccountsView.cs
> +            migrationBuilder.Sql(@"CREATE OR REPLACE VIEW CompanyLinkedServiceAccounts AS
fixed

2023-07-07 07:56 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.Migrations/Migrations/20230706131002_CPLP-2841-CompanyLinkedServiceAccountsView.cs
> +            migrationBuilder.Sql(@"DROP VIEW [IF EXISTS] CompanyLinkedServiceAccounts");
fixed

2023-07-07 07:56 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.PortalEntities/PortalDbContext.cs
> +             .ToView(nameof(CompanyLinkedServiceAccounts))
fixed

2023-07-10 13:59 UTC, Phil91 requested changes

2023-07-10 13:59 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Migrations/PortalDbContextModelSnapshot.cs
> +                    b.ToView("CompaniesLinkedServiceAccounts");
same here, the "portal" is missing. To make sure the latest changes are applied correctly recreate the migration on base of the latest dev portalDbContextModelSnapshot.

2023-07-10 13:59 UTC, Phil91 commented on src/portalbackend/PortalBackend.PortalEntities/Views/CompaniesLinkedServiceAccount.cs
> +public class CompaniesLinkedServiceAccount
Please add some UnitTests to check whether the View is queryable. You can have a look at the `OfferSubscriptionViewTests` for reference in PR https://github.com/eclipse-tractusx/portal-backend/pull/129

2023-07-11 14:20 UTC, Phil91 requested changes
@qxz2mqe could you please rebase the latest dev once again, there shouldn't be any conflicts. After that i can approve and merge the PR

2023-07-11 19:02 UTC, Phil91 submitted a review, later dismissed

2023-07-12 06:33 UTC, Phil91 approved these changes

2023-07-12 07:52 UTC, ntruchsess approved these changes

2023-07-12 07:58 UTC, merged