fix(process worker): fix the crashing of pod
eclipse-tractusx/portal-backend pull request #1119
Opened 2024-10-25 13:09 UTC by dhiren-singh-007

## Description

Handled the system exception and added the Critical/Fatal log type so that we can monitor the logs for criticality.

## Why

It was causing issues for other processes as well .
Eg if a OSP customer sets the wrong callback address or if it is down then it returns the referenced class of SystemException and then it crashed the pod , which stops all other processes.

## Issue

#1114 

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have checked that new and existing tests pass locally with my changes

2024-10-28 10:09 UTC, Phil91 requested changes
Please revert the changes in the framework dir since nothing changed in the framework logic

2024-10-29 12:00 UTC, ntruchsess approved these changes

2024-10-29 12:10 UTC, ntruchsess commented
@dhiren-singh-007 : I think it makes sense to force a restart of the pod when it runs out of memory - everything else should be logged as critical. I also changed the way SocketException and IOException are handled within the remote api calls. Those wouln't throw this kind of systemexception but ServiceException flagged as RecoverOptions.NETWORK (being mapped to RecoverOptions.INFRASTRUCTURE which is most external system calls treat as recoverable skipping the process-step to be retried later). Nevertheless we might want to evaluate whether this is the right strategy for all external system calls - e.g. when calling a url that is provided by the customer it might be better to set the respective process-step to ERROR in this case.

2024-10-29 12:11 UTC, Phil91 approved these changes

2024-10-29 12:16 UTC, merged