fix(connector): change providercompany check to get acces for managed connector.
eclipse-tractusx/portal-backend pull request #1124
Opened 2024-10-30 09:36 UTC by AnuragNagpure

## Description

In endpoint API: GET: /api/administration/connectors/{connectorId} 
As a customer/host company user can't see the details of managed connector getting company {companyId} is not provider of connector {connectorId} error
## Why

Only provider and host/customer company should be able to see the details of connector.

## Issue

#1090 

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-10-30 15:06 UTC, dhiren-singh-007 commented on src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
> +        return result;
I think validation should not be removed , It should check for both either host or provider 
```cs
if (!result.IsProvidingOrHostCompany)
        {
            throw ForbiddenException.Create(AdministrationConnectorErrors.CONNECTOR_NOT_PROVIDER_COMPANY_NOR_HOST, new ErrorParameter[] { new("companyId", companyId.ToString()), new("connectorId", connectorId.ToString()) });
        }

2024-10-30 15:07 UTC, dhiren-singh-007 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ConnectorsRepository.cs
> +    public Task<ConnectorData?> GetConnectorByIdForCompany(Guid connectorId, Guid companyId) =>
`IsProviderCompany` renamed to`IsProvidingOrHostCompany`

2024-10-30 15:08 UTC, dhiren-singh-007 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ConnectorsRepository.cs
> +            .Where(connector => connector.HostId == companyId && connector.Id == connectorId && connector.StatusId != ConnectorStatusId.INACTIVE)
This should remain same 
`.Where(connector => connector.Id == connectorId && connector.StatusId != ConnectorStatusId.INACTIVE)`

2024-10-30 15:08 UTC, dhiren-singh-007 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ConnectorsRepository.cs
> -                connector.ProviderId == companyId
This can be like this `connector.ProviderId == companyId || connector.HostId == companyId`

2024-10-30 15:13 UTC, dhiren-singh-007 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ConnectorsRepository.cs
> -    public Task<(ConnectorData ConnectorData, bool IsProviderCompany)> GetConnectorByIdForCompany(Guid connectorId, Guid companyId) =>
`IsProviderCompany` can be renamed to`IsProvidingOrHostCompany`

2024-11-04 06:09 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ConnectorsRepository.cs
> +            .Where(connector => connector.HostId == companyId && connector.Id == connectorId && connector.StatusId != ConnectorStatusId.INACTIVE)
Reverted the changes

2024-11-04 06:10 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ConnectorsRepository.cs
> -                connector.ProviderId == companyId
added as per requirement

2024-11-04 06:10 UTC, AnuragNagpure commented on src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
> -        if (!result.IsProviderCompany)
reverted changes

2024-11-04 06:10 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ConnectorsRepository.cs
> -    public Task<(ConnectorData ConnectorData, bool IsProviderCompany)> GetConnectorByIdForCompany(Guid connectorId, Guid companyId) =>
renamed

2024-11-07 11:36 UTC, AnuragNagpure commented on src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
>              throw ForbiddenException.Create(AdministrationConnectorErrors.CONNECTOR_NOT_PROVIDER_COMPANY, new ErrorParameter[] { new("companyId", companyId.ToString()), new("connectorId", connectorId
changed

2024-11-08 09:52 UTC, dhiren-singh-007 approved these changes
lgtm

2024-11-12 14:18 UTC, Phil91 requested changes
The RepositoryTest case currently only covers the provider case, please provide a test case to check for the host company as well. Shouldn't be the same as the provider company

2024-11-14 12:51 UTC, ntruchsess commented
> The RepositoryTest case currently only covers the provider case, please provide a test case to check for the host company as well. Shouldn't be the same as the provider company

I did adjust the repository-tests accordingly https://github.com/eclipse-tractusx/portal-backend/pull/1124/commits/7dcc1dcbcc78ce53b0529f431c1057924710d089

2024-11-14 12:54 UTC, ntruchsess submitted a review, later dismissed

2024-11-14 12:54 UTC, Phil91 submitted a review, later dismissed

2024-11-14 14:15 UTC, merged