feat(BpnDidService): Transition from API Key to Technical User Authentication for BDRS Integration (#59)
eclipse-tractusx/portal-backend pull request #1129
Opened 2024-11-05 11:49 UTC by tfjanjua

## Description

We need to update the authentication mechanism for our portal's integration with the BDRS. The current implementation uses an API Key, but it is needed to switch to a new authentication method using a technical user with client ID and secret. 

## Why

The endpoints the portal is hitting remain unchanged, however, the error handling got improved to support the new errors provided with the technical user authentication method.

## Issue

Ref: #1078

## Corresponding Configuration PR
https://github.com/eclipse-tractusx/portal/pull/474

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-11-05 12:55 UTC, tfjanjua commented
> Before approving I'd wait for the PRs to adjust the configuration in the [portal](https://github.com/eclipse-tractusx/portal) repo and add the technical user in the [portal-iam](https://github.com/eclipse-tractusx/portal-iam) repo

@Phil91 configuration PR has been attached

Seed data (related to Service Account of `BDRS Management`) still needs to be part of this PR

2024-11-05 13:10 UTC, evegufy requested changes
Requesting changes so that the PR doesn't get merged until there's an according change on BDRS side https://github.com/eclipse-tractusx/sig-release/issues/959#issuecomment-2457122731

2024-11-05 16:13 UTC, tfjanjua commented
> Requesting changes so that the PR doesn't get merged until there's an according change on BDRS side [eclipse-tractusx/sig-release#959 (comment)](https://github.com/eclipse-tractusx/sig-release/issues/959#issuecomment-2457122731)

Just FYI: @evegufy | @Phil91,  I have added Seed Data for a technical user for `BDRS Management`

2024-11-13 23:56 UTC, ntruchsess commented
@tfjanjua as there was a conflict with latest seeding-data related changes on main I did rebase the branch on main and die a force-push. Please pull those changes before applying further commits.

2024-12-13 08:10 UTC, evegufy commented
don't merge until change from BDRS side is clarified. 
I was then also under the impression that you prediscussed the change with the BDRS committers, as commented [here](https://github.com/eclipse-tractusx/sig-release/issues/959#issuecomment-2457122731), but that doesn't seem the case, see https://github.com/eclipse-tractusx/bpn-did-resolution-service/issues/120.

2025-01-06 11:05 UTC, Phil91 approved these changes

2025-03-05 12:36 UTC, evegufy commented
https://github.com/eclipse-tractusx/sig-release/issues/959#issuecomment-2653076719 --> close

2025-03-05 12:36 UTC, closed without merging