feat(daps): add config to disable daps calls
eclipse-tractusx/portal-backend pull request #114
Opened 2023-06-28 13:53 UTC by Phil91

## Description

Disabled daps calls

## Why

Daps should get removed in the long run, this PR is the first iteration.

## Issue

N/A - Jira Issue: CPLP-2702

## Corresponding CD PR

[#43](https://github.com/eclipse-tractusx/portal-cd/pull/43)

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2023-07-02 21:45 UTC, jjeroch commented
please dont merge as long as we dont have the FE pr in place. I will inform you as soon as it is ready and pre-checked by me.

2023-07-03 21:22 UTC, ntruchsess requested changes

2023-07-03 21:22 UTC, ntruchsess commented on src/administration/Administration.Service/Controllers/ConnectorsController.cs
> +    [Authorize(Roles = "notexistingrole")]
what is the purpose of effectively disable access to this endpoint instead of removing it?

2023-07-04 06:36 UTC, Phil91 commented on src/administration/Administration.Service/Controllers/ConnectorsController.cs
> +    [Authorize(Roles = "notexistingrole")]
@jjeroch  could you clarify? in my opinion to quickly add it back again if we need the daps call for some reason.

2023-07-07 09:02 UTC, jjeroch commented on src/administration/Administration.Service/Controllers/ConnectorsController.cs
> +    [Authorize(Roles = "notexistingrole")]
@ntruchsess & @Phil91 since the daps removal is supposed to only take place after we tested all e2e flows successfully, the approach on portal side is: disable the daps services for now until the e2e tests have been successful. As soon as all tests have passed the test gateway we will remove those disabled interfaces/functions, etc.

In case the tests are unsuccessful we can easily enable daps again without almost any efforts.

Hope that answers the question and hope my assumption regarding "work efforts" is correct ;)

2023-07-07 09:22 UTC, Phil91 commented
closing this PR, created the branch on upstream directly (see PR #131) to easily test the changes on our dev environment.

2023-07-07 09:22 UTC, closed without merging