feat(seeding): add userProfile and localizationTexts to seeding
eclipse-tractusx/portal-backend pull request #1154
Opened 2024-11-17 11:30 UTC by Phil91

## Description

add userProfile and localizationTexts to keycloak seeding

## Why

To enable the seeding of userProfiles and localization Texts

## Issue

Refs: #1150

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-11-18 06:59 UTC, Phil91 commented on src/keycloak/Keycloak.Seeding/BusinessLogic/SeedDataHandler.cs
> +        get => _keycloakRealm?.LocalizationTexts?.FilterNotNullValues().Select(x => (x.Key, x.Value.Select(kvp => kvp))) ?? Enumerable.Empty<(string, IEnumerable<KeyValuePair<string, string>>)>();
The select statement is needed, otherwise the return type is IDictionary<string, string> but we want KeyValuePair<string, string>

2024-11-18 06:59 UTC, Phil91 commented on src/keycloak/Keycloak.Seeding/Extensions/ComponentsExtensions.cs
> +                    .Any(matchingComponent => matchingComponent == null));
fixed

2024-11-18 06:59 UTC, Phil91 commented on src/keycloak/Keycloak.Seeding/Extensions/ComponentsExtensions.cs
> +                    c.Value != null && updateConfigValues != null && c.Value.SequenceEqual(updateConfigValues)));
fixed

2024-11-18 07:00 UTC, Phil91 commented on src/keycloak/Keycloak.Library/Models/Users/UserProfileConfig.cs
> +        return Attributes.Equals(other.Attributes) && Groups.Equals(other.Groups);
fixed

2024-11-18 07:00 UTC, Phil91 commented on src/keycloak/Keycloak.Library/Localization/KeycloakClient.cs
> +            .PutAsync(new StringContent(translation, MediaTypeHeaderValue.Parse("text/plain")), cancellationToken: cancellationToken)
won't fix, the string content is disposed after the put

2024-11-18 07:35 UTC, evegufy commented
Hi @Phil91 format check failed

2024-11-18 09:20 UTC, Phil91 commented on src/keycloak/Keycloak.Library/Models/Users/UserProfileConfig.cs
> +        ((Scopes == null && other.Scopes == null) || Scopes != null && other.Scopes != null && Scopes.Order().SequenceEqual(other.Scopes.Order()));
fixed

2024-11-18 12:04 UTC, evegufy requested changes
I tested the CX-Central realm for the import of the user profile related values and that works now 👍 
But I also tested if the import of the realm in sharedidp still works with this change and I'm getting the following error in the seeding job:
`
{"Timestamp":"2024-11-18T11:59:38.8573917+00:00","Level":"Fatal","MessageTemplate":"Unhandled exception","RenderedMessage":"Unhandled exception","Exception":"Org.Eclipse.TractusX.Portal.Backend.Keycloak.ErrorHandling.KeycloakNoSuccessException: Bad Request: http://sharedidp-keycloak/auth/realms/master/protocol/openid-connect/token\n ---> Flurl.Http.FlurlHttpException: Call failed with status code 400 (Bad Request): POST http://sharedidp-keycloak:80/auth/realms/master/protocol/openid-connect/token\n   at Flurl.Http.FlurlClient.SendAsync(IFlurlRequest request, HttpCompletionOption completionOption, CancellationToken cancellationToken)\n   --- End of inner exception stack trace ---\n   at Org.Eclipse.TractusX.Portal.Backend.Keycloak.ErrorHandling.FlurlErrorHandler.<>c__DisplayClass0_0.<ConfigureErrorHandler>b__1(FlurlCall call) in /src/keycloak/Keycloak.ErrorHandling/FlurlErrorHandler.cs:line 58\n   at Flurl.Http.FlurlEventHandler.FromAsyncAction.HandleAsync(FlurlEventType eventType, FlurlCall call)\n   at Flurl.Http.FlurlClient.RaiseEventAsync(FlurlEventType eventType, FlurlCall call)\n   at Flurl.Http.FlurlClient.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)\n   at Flurl.Http.FlurlClient.SendAsync(IFlurlRequest request, HttpCompletionOption completionOption, CancellationToken cancellationToken)\n   at Flurl.Http.FlurlClient.SendAsync(IFlurlRequest request, HttpCompletionOption completionOption, CancellationToken cancellationToken)\n   at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)\n   at Org.Eclipse.TractusX.Portal.Backend.Keycloak.Library.Common.Extensions.FlurlRequestExtensions.GetAccessTokenAsync(String url, String realm, String userName, String password, Boolean useAuthTrail, CancellationToken cancellationToken) in /src/keycloak/Keycloak.Library/Common/Extensions/FlurlRequestExtensions.cs:line 37\n   at Org.Eclipse.TractusX.Portal.Backend.Keycloak.Library.Common.Extensions.FlurlRequestExtensions.WithAuthenticationAsync(IFlurlRequest request, Func`2 getTokenAsync, String url, String realm, String userName, String password, String clientSecret, String clientId, Boolean useAuthTrail, CancellationToken cancellationToken) in /src/keycloak/Keycloak.Library/Common/Extensions/FlurlRequestExtensions.cs:line 84\n   at Org.Eclipse.TractusX.Portal.Backend.Keycloak.Library.KeycloakClient.DeleteComponentAsync(String realm, String componentId, CancellationToken cancellationToken) in /src/keycloak/Keycloak.Library/Components/KeycloakClient.cs:line 69\n   at Org.Eclipse.TractusX.Portal.Backend.Keycloak.Seeding.BusinessLogic.ComponentsUpdater.DeleteComponents(KeycloakClient keycloak, String realm, IEnumerable`1 components, IEnumerable`1 updateComponents, CancellationToken cancellationToken) in /src/keycloak/Keycloak.Seeding/BusinessLogic/ComponentsUpdater.cs:line 81\n   at Org.Eclipse.TractusX.Portal.Backend.Keycloak.Seeding.BusinessLogic.ComponentsUpdater.UpdateComponents(String keycloakInstanceName, CancellationToken cancellationToken) in /src/keycloak/Keycloak.Seeding/BusinessLogic/ComponentsUpdater.cs:line 45\n   at Org.Eclipse.TractusX.Portal.Backend.Keycloak.Seeding.BusinessLogic.KeycloakSeeder.Seed(CancellationToken cancellationToken) in /src/keycloak/Keycloak.Seeding/BusinessLogic/KeecloakSeeder.cs:line 49\n   at Program.<Main>$(String[] args) in /src/keycloak/Keycloak.Seeding/Program.cs:line 86"}
`

2024-11-19 22:51 UTC, ntruchsess requested changes

2024-11-19 22:51 UTC, ntruchsess commented on src/keycloak/Keycloak.Library/Localization/KeycloakClient.cs
> +            .PutAsync(new StringContent(translation, MediaTypeHeaderValue.Parse("text/plain")), cancellationToken: cancellationToken)
```suggestion
        using var stringContent = new StringContent(translation, MediaTypeHeaderValue.Parse("text/plain"));
        await (await GetBaseUrlAsync(realm, cancellationToken).ConfigureAwait(ConfigureAwaitOptions.None))
            .AppendPathSegment(AdminUrlSegment)
            .AppendPathSegment(realm, true)
            .AppendPathSegment(LocalizationUrlSegment)
            .AppendPathSegment(locale, true)
            .AppendPathSegment(key, true)
            .PutAsync(stringContent, cancellationToken: cancellationToken)
            .ConfigureAwait(ConfigureAwaitOptions.None);
```

2024-11-19 22:51 UTC, ntruchsess commented on src/keycloak/Keycloak.Seeding/BusinessLogic/LocalizationsUpdater.cs
> +        }
```suggestion
        if (!await locales
                .Join(
                    translations,
                    l => l,
                    trans => trans.Locale,
                    (l, trans) => (Locale: l, Update: trans))
                .IfAnyAwait(async localesToUpdate =>
                {
                    foreach (var (locale, update) in
                            localesToUpdate)
                    {
                        var localizations = await keycloak.GetLocaleAsync(realm, locale, cancellationToken: cancellationToken).ConfigureAwait(ConfigureAwaitOptions.None);
                        foreach (var missingTranslation in update.Translations.ExceptBy(localizations.Select(loc => loc.Key),
                                    locModel => locModel.Key))
                        {
                            await keycloak.UpdateLocaleAsync(realm, locale, missingTranslation.Key, missingTranslation.Value, cancellationToken).ConfigureAwait(false);
                        }

                        foreach (var updateTranslation in
                                localizations.Join(
                                    update.Translations,
                                    l => l.Key,
                                    trans => trans.Key,
                                    (l, trans) => (Key: l.Key, Update: trans)))
                        {
                            await keycloak.UpdateLocaleAsync(realm, locale, updateTranslation.Key, updateTranslation.Update.Value, cancellationToken).ConfigureAwait(false);
                        }

                        foreach (var deleteTranslation in
                                localizations.ExceptBy(update.Translations.Select(t => t.Key),
                                    l => l.Key))
                        {
                            await keycloak.DeleteLocaleAsync(realm, locale, deleteTranslation.Key, cancellationToken).ConfigureAwait(ConfigureAwaitOptions.None);
                        }
                    }
                }).ConfigureAwait(false))
        {
            await AddLocales(keycloak, realm, translations, cancellationToken);
        }
```

2024-11-19 22:51 UTC, ntruchsess commented on src/keycloak/Keycloak.Seeding/BusinessLogic/SeedDataHandler.cs
> +        get => _keycloakRealm?.LocalizationTexts?.FilterNotNullValues().Select(x => (x.Key, x.Value.Select(kvp => kvp))) ?? Enumerable.Empty<(string, IEnumerable<KeyValuePair<string, string>>)>();
not 100% sure, but as IDictionary<K,V> implements IEnumerable<KeyValuePair<K,V>> I think a cast would also do:
```suggestion
        get => _keycloakRealm?.LocalizationTexts?.FilterNotNullValues().Select(x => (x.Key, x.Value as IEnumerable<KeyValuePair<string, string>>)) ?? Enumerable.Empty<(string, IEnumerable<KeyValuePair<string, string>>)>();
```

2024-11-19 22:51 UTC, ntruchsess commented on src/keycloak/Keycloak.Seeding/BusinessLogic/UserProfileUpdater.cs
> +        if (userProfiles.Count() != 1 || !userProfiles.Single().ComponentModel.Config.TryGetValue(UserProfileConfig, out var configs) || configs.Count() != 1)
```suggestion
        if (userProfiles.Count() != 1 || !(userProfiles.Single().ComponentModel.Config?.TryGetValue(UserProfileConfig, out var configs) ?? false) || configs?.Count() != 1)
```

2024-11-20 08:01 UTC, Phil91 commented on src/keycloak/Keycloak.Library/Localization/KeycloakClient.cs
> +            .PutAsync(new StringContent(translation, MediaTypeHeaderValue.Parse("text/plain")), cancellationToken: cancellationToken)
added

2024-11-20 08:01 UTC, Phil91 commented on src/keycloak/Keycloak.Seeding/BusinessLogic/LocalizationsUpdater.cs
> +        }
really like the implementation - added

2024-11-20 08:01 UTC, Phil91 commented on src/keycloak/Keycloak.Seeding/BusinessLogic/SeedDataHandler.cs
> +        get => _keycloakRealm?.LocalizationTexts?.FilterNotNullValues().Select(x => (x.Key, x.Value.Select(kvp => kvp))) ?? Enumerable.Empty<(string, IEnumerable<KeyValuePair<string, string>>)>();
adjusted

2024-11-20 08:01 UTC, Phil91 commented on src/keycloak/Keycloak.Seeding/BusinessLogic/UserProfileUpdater.cs
> +        if (userProfiles.Count() != 1 || !userProfiles.Single().ComponentModel.Config.TryGetValue(UserProfileConfig, out var configs) || configs.Count() != 1)
adjusted

2024-11-20 08:03 UTC, Phil91 commented
> I tested the CX-Central realm for the import of the user profile related values and that works now 👍 But I also tested if the [import of the realms in sharedidp](https://github.com/eclipse-tractusx/portal-iam/tree/v4.0.0-rc.1/import/realm-config/generic/catenax-shared) still works with this change and I'm getting the following error in the seeding job: ` {"Timestamp":"2024-11-18T11:59:38.8573917+00:00","Level":"Fatal","MessageTemplate":"Unhandled exception","RenderedMessage":"Unhandled exception","Exception":"Org.Eclipse.TractusX.Portal.Backend.Keycloak.ErrorHandling.KeycloakNoSuccessException: Bad Request: http://sharedidp-keycloak/auth/realms/master/protocol/openid-connect/token\n ---> Flurl.Http.FlurlHttpException: Call failed with status code 400 (Bad Request): POST http://sharedidp-keycloak:80/auth/realms/master/protocol/openid-connect/token\n at Flurl.Http.FlurlClient.SendAsync(IFlurlRequest request, HttpCompletionOption completionOption, CancellationToken cancellationToken)\n --- End of inner exception stack trace ---\n at Org.Eclipse.TractusX.Portal.Backend.Keycloak.ErrorHandling.FlurlErrorHandler.<>c__DisplayClass0_0.<ConfigureErrorHandler>b__1(FlurlCall call) in /src/keycloak/Keycloak.ErrorHandling/FlurlErrorHandler.cs:line 58\n at Flurl.Http.FlurlEventHandler.FromAsyncAction.HandleAsync(FlurlEventType eventType, FlurlCall call)\n at Flurl.Http.FlurlClient.RaiseEventAsync(FlurlEventType eventType, FlurlCall call)\n at Flurl.Http.FlurlClient.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)\n at Flurl.Http.FlurlClient.SendAsync(IFlurlRequest request, HttpCompletionOption completionOption, CancellationToken cancellationToken)\n at Flurl.Http.FlurlClient.SendAsync(IFlurlRequest request, HttpCompletionOption completionOption, CancellationToken cancellationToken)\n at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)\n at Org.Eclipse.TractusX.Portal.Backend.Keycloak.Library.Common.Extensions.FlurlRequestExtensions.GetAccessTokenAsync(String url, String realm, String userName, String password, Boolean useAuthTrail, CancellationToken cancellationToken) in /src/keycloak/Keycloak.Library/Common/Extensions/FlurlRequestExtensions.cs:line 37\n at Org.Eclipse.TractusX.Portal.Backend.Keycloak.Library.Common.Extensions.FlurlRequestExtensions.WithAuthenticationAsync(IFlurlRequest request, Func`2 getTokenAsync, String url, String realm, String userName, String password, String clientSecret, String clientId, Boolean useAuthTrail, CancellationToken cancellationToken) in /src/keycloak/Keycloak.Library/Common/Extensions/FlurlRequestExtensions.cs:line 84\n at Org.Eclipse.TractusX.Portal.Backend.Keycloak.Library.KeycloakClient.DeleteComponentAsync(String realm, String componentId, CancellationToken cancellationToken) in /src/keycloak/Keycloak.Library/Components/KeycloakClient.cs:line 69\n at Org.Eclipse.TractusX.Portal.Backend.Keycloak.Seeding.BusinessLogic.ComponentsUpdater.DeleteComponents(KeycloakClient keycloak, String realm, IEnumerable`1 components, IEnumerable`1 updateComponents, CancellationToken cancellationToken) in /src/keycloak/Keycloak.Seeding/BusinessLogic/ComponentsUpdater.cs:line 81\n at Org.Eclipse.TractusX.Portal.Backend.Keycloak.Seeding.BusinessLogic.ComponentsUpdater.UpdateComponents(String keycloakInstanceName, CancellationToken cancellationToken) in /src/keycloak/Keycloak.Seeding/BusinessLogic/ComponentsUpdater.cs:line 45\n at Org.Eclipse.TractusX.Portal.Backend.Keycloak.Seeding.BusinessLogic.KeycloakSeeder.Seed(CancellationToken cancellationToken) in /src/keycloak/Keycloak.Seeding/BusinessLogic/KeecloakSeeder.cs:line 49\n at Program.<Main>$(String[] args) in /src/keycloak/Keycloak.Seeding/Program.cs:line 86"} `

could you please recheck, I've adjusted the logic

2024-11-20 09:46 UTC, evegufy commented
> > I tested the CX-Central realm for the import of the user profile related values and that works now 👍 But I also tested if the [import of the realms in sharedidp](https://github.com/eclipse-tractusx/portal-iam/tree/v4.0.0-rc.1/import/realm-config/generic/catenax-shared) still works with this change and I'm getting the following error in the seeding job: ` {"Timestamp":"2024-11-18T11:59:38.8573917+00:00","Level":"Fatal","MessageTemplate":"Unhandled exception","RenderedMessage":"Unhandled exception","Exception":"Org.Eclipse.TractusX.Portal.Backend.Keycloak.ErrorHandling.KeycloakNoSuccessException: Bad Request: http://sharedidp-keycloak/auth/realms/master/protocol/openid-connect/token\n ---> Flurl.Http.FlurlHttpException: Call failed with status code 400 (Bad Request): POST http://sharedidp-keycloak:80/auth/realms/master/protocol/openid-connect/token\n at Flurl.Http.FlurlClient.SendAsync(IFlurlRequest request, HttpCompletionOption completionOption, CancellationToken cancellationToken)\n --- End of inner exception stack trace ---\n at Org.Eclipse.TractusX.Portal.Backend.Keycloak.ErrorHandling.FlurlErrorHandler.<>c__DisplayClass0_0.<ConfigureErrorHandler>b__1(FlurlCall call) in /src/keycloak/Keycloak.ErrorHandling/FlurlErrorHandler.cs:line 58\n at Flurl.Http.FlurlEventHandler.FromAsyncAction.HandleAsync(FlurlEventType eventType, FlurlCall call)\n at Flurl.Http.FlurlClient.RaiseEventAsync(FlurlEventType eventType, FlurlCall call)\n at Flurl.Http.FlurlClient.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)\n at Flurl.Http.FlurlClient.SendAsync(IFlurlRequest request, HttpCompletionOption completionOption, CancellationToken cancellationToken)\n at Flurl.Http.FlurlClient.SendAsync(IFlurlRequest request, HttpCompletionOption completionOption, CancellationToken cancellationToken)\n at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)\n at Org.Eclipse.TractusX.Portal.Backend.Keycloak.Library.Common.Extensions.FlurlRequestExtensions.GetAccessTokenAsync(String url, String realm, String userName, String password, Boolean useAuthTrail, CancellationToken cancellationToken) in /src/keycloak/Keycloak.Library/Common/Extensions/FlurlRequestExtensions.cs:line 37\n at Org.Eclipse.TractusX.Portal.Backend.Keycloak.Library.Common.Extensions.FlurlRequestExtensions.WithAuthenticationAsync(IFlurlRequest request, Func`2 getTokenAsync, String url, String realm, String userName, String password, String clientSecret, String clientId, Boolean useAuthTrail, CancellationToken cancellationToken) in /src/keycloak/Keycloak.Library/Common/Extensions/FlurlRequestExtensions.cs:line 84\n at Org.Eclipse.TractusX.Portal.Backend.Keycloak.Library.KeycloakClient.DeleteComponentAsync(String realm, String componentId, CancellationToken cancellationToken) in /src/keycloak/Keycloak.Library/Components/KeycloakClient.cs:line 69\n at Org.Eclipse.TractusX.Portal.Backend.Keycloak.Seeding.BusinessLogic.ComponentsUpdater.DeleteComponents(KeycloakClient keycloak, String realm, IEnumerable`1 components, IEnumerable`1 updateComponents, CancellationToken cancellationToken) in /src/keycloak/Keycloak.Seeding/BusinessLogic/ComponentsUpdater.cs:line 81\n at Org.Eclipse.TractusX.Portal.Backend.Keycloak.Seeding.BusinessLogic.ComponentsUpdater.UpdateComponents(String keycloakInstanceName, CancellationToken cancellationToken) in /src/keycloak/Keycloak.Seeding/BusinessLogic/ComponentsUpdater.cs:line 45\n at Org.Eclipse.TractusX.Portal.Backend.Keycloak.Seeding.BusinessLogic.KeycloakSeeder.Seed(CancellationToken cancellationToken) in /src/keycloak/Keycloak.Seeding/BusinessLogic/KeecloakSeeder.cs:line 49\n at Program.<Main>$(String[] args) in /src/keycloak/Keycloak.Seeding/Program.cs:line 86"} `
> 
> could you please recheck, I've adjusted the logic

successfully retested 👍

2024-11-20 09:46 UTC, evegufy approved these changes

2024-11-20 12:43 UTC, ntruchsess approved these changes

2024-11-20 12:50 UTC, merged