build: upgrade to .net 9
eclipse-tractusx/portal-backend pull request #1161
Opened 2024-11-19 07:56 UTC by Phil91

## Description

Upgrade .NET to v9

## Why

To have the latest dotnet version in the projects

## Issue

Refs: #1155

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-11-20 08:06 UTC, Phil91 commented
we need to wait for https://github.com/efcore/EFCore.NamingConventions/issues/295 to be resolved

2024-12-03 11:51 UTC, Phil91 commented
> we need to wait for [efcore/EFCore.NamingConventions#295](https://github.com/efcore/EFCore.NamingConventions/issues/295) to be resolved

v9.0.0 was released to nuget

2024-12-03 11:58 UTC, Phil91 commented
[Npgsql/9.0.1](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/17608)
[Mono.TextTemplating/3.0.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/17609)
[Npgsql/9.0.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/17610)
[Swashbuckle.AspNetCore.SwaggerGen/7.0.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/17611)
[Swashbuckle.AspNetCore.Swagger/7.0.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/17612)
[Laraue.EfCoreTriggers.Common/9.0.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/17613)
[Swashbuckle.AspNetCore.SwaggerUI/7.0.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/17614)
[Npgsql.EntityFrameworkCore.PostgreSQL/9.0.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/17615)
[Laraue.EfCoreTriggers.PostgreSql/9.0.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/17616)
[EFCore.NamingConventions/9.0.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/17617)
[Swashbuckle.AspNetCore/7.0.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/17618)
[Npgsql.EntityFrameworkCore.PostgreSQL/9.0.1](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/17619)
[SwashBuckle.AspNetCore/7.0.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/17620)

2025-01-24 11:46 UTC, Phil91 commented
IP Issues created for

[nuget/nuget/-/xunit.runner.visualstudio/3.0.1](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/19188)
[nuget/nuget/-/FluentAssertions/8.0.1](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/19187)

2025-01-24 13:31 UTC, ntruchsess requested changes
besides the failed dependency-check everything seems fine. I'll approve as soon the IP-issues are approved and the DEPENDENCIES file is updated accordingly.

2025-02-05 11:32 UTC, ntruchsess approved these changes

2025-02-05 11:35 UTC, merged