fix(osp): applied regex validation on uniqueIds param
eclipse-tractusx/portal-backend pull request #1163
Opened 2024-11-19 11:06 UTC by tfjanjua

## Description

Applied one more validation on `uniqueIds` param through regex.

## Why

Currently, request is being validated with invalid data e.g: "VAT ID" --> “value“ : “XYZ“

![image](https://github.com/user-attachments/assets/83a4f60a-e15c-4504-b06e-2c2ca405f913)

## Issue

Ref: #1157

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-11-19 21:48 UTC, ntruchsess requested changes

2024-11-19 21:48 UTC, ntruchsess commented on src/registration/Registration.Common/RegistrationValidation.cs
> +        }
```suggestion
        data.UniqueIds.Where(uniqueId => IsInvalidValueByUniqueIdentifier(uniqueId.Value, uniqueId.UniqueIdentifierId))
            .IfAny(invalidUniqueIdentifiersValues =>
                {
                    throw new ControllerArgumentException(
                        $"Invalid value of uniqueIds: '{string.Join(", ", invalidUniqueIdentifiersValues.Select(uniqueId => uniqueId.UniqueIdentifierId))}'",
                        nameof(data.UniqueIds));
                });
```

2024-11-19 21:48 UTC, ntruchsess commented on src/registration/Registration.Common/RegistrationValidation.cs
> +            _ => throw new ArgumentOutOfRangeException(nameof(uniqueIdentifierId), uniqueIdentifierId, "Provided unique identifier is not available in the system")
throw ControllerArgumentException instead. ArgumentOutOfRangeException is a SystemException which should not be thrown by businesslogic (also see remarks at https://learn.microsoft.com/en-us/dotnet/api/system.systemexception?view=net-8.0 )

2024-11-22 15:39 UTC, tfjanjua commented on src/registration/Registration.Common/RegistrationValidation.cs
> +        }
Thanks for suggestion. Its done

2024-11-22 15:39 UTC, tfjanjua commented on src/registration/Registration.Common/RegistrationValidation.cs
> +            _ => throw new ArgumentOutOfRangeException(nameof(uniqueIdentifierId), uniqueIdentifierId, "Provided unique identifier is not available in the system")
done

2024-12-13 08:12 UTC, evegufy commented
please take care of codeql finding

2024-12-13 09:09 UTC, Phil91 commented
changes looks fine, after the fix of the codeQl finding we can merge the pr imo

2024-12-13 13:52 UTC, tfjanjua commented
@evegufy | @Phil91 
codeql findings has been resolved.

2025-01-08 13:25 UTC, tfjanjua commented
@evegufy | @Phil91 | @ntruchsess 
Can this PR be merged if there are no other findings? I ask this because we need this change as part of our next release.

2025-01-14 07:21 UTC, Phil91 submitted a review, later dismissed

2025-02-06 07:34 UTC, tfjanjua commented
Hi @Phil91 | @ntruchsess 
Please let me know if this PR can be merged if there is no more feedback!

2025-02-06 11:52 UTC, evegufy requested changes
@tfjanjua sorry for the delay! could you please resolve the conflicts?

2025-02-06 14:32 UTC, ntruchsess approved these changes

2025-02-06 14:41 UTC, merged