feat(documents): documentSize column added with migration script in documents table
eclipse-tractusx/portal-backend pull request #1164
Opened 2024-11-19 12:25 UTC by AnuragNagpure

## Description

POST Endpoint to be adjusted: /api/registration/application/{applicationId}/documentType/{documentTypeId}/documents
API should store Length in Kilobyte.
New Databasefield in table documents -> document_size type Long

GET Endpoints to be adjusted:
/api/registration/application/{applicationId}/documentType/{documentTypeId}/documents

Execute SQL script to update the documents.document_size field for existing entries.

## Why

New documentSize field added in docuents table also script for already existing document to get its size in database added.
Post/Get endpoints associated with documents table enhanced.

## Issue

#880 

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-11-19 13:58 UTC, Phil91 requested changes

2024-11-19 13:58 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/IDocumentRepository.cs
> +    Document CreateDocument(string documentName, byte[] documentContent, byte[] hash, MediaTypeId mediaTypeId, DocumentTypeId documentTypeId, long documentLength, Action<Document>? setupOptionalField
Please add to the param collection in the summary

2024-11-19 13:58 UTC, Phil91 commented on src/portalbackend/PortalBackend.PortalEntities/AuditEntities/AuditDocument20231115.cs
> +    public long? DocumentSize { get; set; }
Please never update Audit entities, the way to go would be to create a new entity with the added property and link it appropriately in the origin engine.

2024-11-19 13:58 UTC, Phil91 commented on src/portalbackend/PortalBackend.PortalEntities/AuditEntities/AuditDocument20231108.cs
> +    public long? DocumentSize { get; set; }
Please never update Audit entities, the way to go would be to create a new entity with the added property and link it appropriately in the origin engine.

2024-11-19 13:58 UTC, Phil91 commented on src/portalbackend/PortalBackend.PortalEntities/Entities/Document.cs
> +    public Document(Guid id, byte[] documentContent, byte[] documentHash, string documentName, MediaTypeId mediaTypeId, DateTimeOffset dateCreated, DocumentStatusId documentStatusId, DocumentTypeId d
Please adjust the AuditEntityV1 to a newly created auditEntity

2024-11-19 13:58 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Migrations/20241119105520_document_size_parameter.cs
> +    public partial class document_size_parameter : Migration
Please recreate the migration after adding the new audit entity

2024-11-20 09:58 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.Migrations/Migrations/20241119105520_document_size_parameter.cs
> +    public partial class document_size_parameter : Migration
new migration added

2024-11-20 09:58 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.PortalEntities/Entities/Document.cs
> +    public Document(Guid id, byte[] documentContent, byte[] documentHash, string documentName, MediaTypeId mediaTypeId, DateTimeOffset dateCreated, DocumentStatusId documentStatusId, DocumentTypeId d
adjusted

2024-11-20 09:58 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.PortalEntities/AuditEntities/AuditDocument20231108.cs
> +    public long? DocumentSize { get; set; }
sure will note it

2024-11-20 09:58 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.PortalEntities/AuditEntities/AuditDocument20231115.cs
> +    public long? DocumentSize { get; set; }
will do the same

2024-11-20 09:58 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.DBAccess/Repositories/IDocumentRepository.cs
> +    Document CreateDocument(string documentName, byte[] documentContent, byte[] hash, MediaTypeId mediaTypeId, DocumentTypeId documentTypeId, long documentLength, Action<Document>? setupOptionalField
added

2024-11-20 12:16 UTC, Phil91 requested changes

2024-11-20 12:16 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Migrations/20241120091826_document_size_field_update_audit_entities.cs
> +/********************************************************************************
It looks like you didn't rollback the previous migration or didn't rollback the snapshot file, the migration doesn't include the add of the column.

2024-11-21 11:00 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.Migrations/Migrations/20241120091826_document_size_field_update_audit_entities.cs
> +/********************************************************************************
changes done

2024-11-22 14:44 UTC, Phil91 approved these changes

2024-11-22 14:47 UTC, merged