feat(subscriptionDecline): Ability for App or Service Provider to Decline the Subscription request
eclipse-tractusx/portal-backend pull request #1171
Opened 2024-11-21 16:52 UTC by tfjanjua

## Description

Ability for App or Service Provider to Decline the Subscription request
- /api/apps/subscription/{subscriptionId}/decline
- /api/services/subscription/{subscriptionId}/decline

## Why

Currently this functionality not exists and its one of the requests from real users.

## Issue

Ref: #1140

## Checklist

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-12-13 08:15 UTC, evegufy commented
Please resolve conflict and take care of codeql finding
@Phil91 @ntruchsess please review.

2024-12-13 08:57 UTC, Phil91 requested changes
Might be possible that the created migrations and the snapshot file were created with utf-8 with bom encoding. please make sure that those files are encoded with utf-8

2024-12-13 08:57 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
> +
Would remove it

2024-12-13 08:57 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/IOfferSubscriptionsRepository.cs
> +    OfferSubscription DeleteOfferSubscription(Guid subscriptionId, Guid offerId, Guid companyId, OfferSubscriptionStatusId offerSubscriptionStatusId, Guid requesterId);
Would remove it and use the Remove<TEntity> call in `PortalRepositories`

2024-12-13 08:57 UTC, Phil91 commented on src/marketplace/Offers.Library/Service/OfferSubscriptionService.cs
> +        var offerSubscription = offerSubscriptionsRepository.DeleteOfferSubscription(subscriptionId, offerId, offerSubscriptionDetails.CompanyId, offerSubscriptionDetails.Status, offerSubscriptionDet
would change to `portalRepositories.Remove` the offerSubscription is not needed since we already know the id

2024-12-13 08:57 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Migrations/20241121163647_1140_Decline-Offer-Subscription.Designer.cs
> +﻿// <auto-generated />
Please add file header

2024-12-13 08:57 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Migrations/20241121163647_1140_Decline-Offer-Subscription.cs
> +﻿using Microsoft.EntityFrameworkCore.Migrations;
Please add file header

2024-12-13 08:57 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Migrations/PortalDbContextModelSnapshot.cs
> +﻿// <auto-generated />
Please read file header

2024-12-13 08:57 UTC, Phil91 commented on src/marketplace/Offers.Library/Service/OfferSubscriptionService.cs
> +        if (offerSubscriptionDetails.Status == OfferSubscriptionStatusId.INACTIVE)
do we really want to check for == INACTIVE? imo it would make more sense to check for != PENDING?

2024-12-23 12:20 UTC, tfjanjua commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
> +
done

2024-12-23 12:20 UTC, tfjanjua commented on src/portalbackend/PortalBackend.DBAccess/Repositories/IOfferSubscriptionsRepository.cs
> +    OfferSubscription DeleteOfferSubscription(Guid subscriptionId, Guid offerId, Guid companyId, OfferSubscriptionStatusId offerSubscriptionStatusId, Guid requesterId);
done

2024-12-23 12:20 UTC, tfjanjua commented on src/marketplace/Offers.Library/Service/OfferSubscriptionService.cs
> +        var offerSubscription = offerSubscriptionsRepository.DeleteOfferSubscription(subscriptionId, offerId, offerSubscriptionDetails.CompanyId, offerSubscriptionDetails.Status, offerSubscriptionDet
done

2024-12-23 12:21 UTC, tfjanjua commented on src/portalbackend/PortalBackend.Migrations/Migrations/20241121163647_1140_Decline-Offer-Subscription.Designer.cs
> +﻿// <auto-generated />
done

2024-12-23 12:21 UTC, tfjanjua commented on src/portalbackend/PortalBackend.Migrations/Migrations/PortalDbContextModelSnapshot.cs
> +﻿// <auto-generated />
done

2024-12-23 12:21 UTC, tfjanjua commented on src/marketplace/Offers.Library/Service/OfferSubscriptionService.cs
> +        if (offerSubscriptionDetails.Status == OfferSubscriptionStatusId.INACTIVE)
done

2024-12-23 12:22 UTC, tfjanjua commented on src/portalbackend/PortalBackend.Migrations/Migrations/20241121163647_1140_Decline-Offer-Subscription.cs
> +﻿using Microsoft.EntityFrameworkCore.Migrations;
done

2025-01-06 10:49 UTC, Phil91 requested changes

2025-01-06 10:49 UTC, Phil91 commented on src/marketplace/Offers.Library/Service/OfferSubscriptionService.cs
> +            throw new NotFoundException($"Offer {offerId} does not exist.");
Please use the "new ErrorHandling" instead of `new NotFoundException` use `NotFoundException.Create(` please adjust the other exceptions as well.

2025-01-06 10:49 UTC, Phil91 commented on src/marketplace/Offers.Library/Service/OfferSubscriptionService.cs
> +            offerSubscriptionDetails.RequesterEmail!,
The `RequesterEmail` isn't checked for not being null. Please add the check and skip the sending of the mail if the requesterEmail is nullOrWhiteSpace

2025-01-08 12:12 UTC, tfjanjua commented on src/marketplace/Offers.Library/Service/OfferSubscriptionService.cs
> +            throw new NotFoundException($"Offer {offerId} does not exist.");
done

2025-01-08 12:12 UTC, tfjanjua commented on src/marketplace/Offers.Library/Service/OfferSubscriptionService.cs
> +            offerSubscriptionDetails.RequesterEmail!,
done

2025-01-13 08:59 UTC, tfjanjua commented
@evegufy  | @Phil91  | @ntruchsess 
Can this PR be merged if there are no other findings? I ask this because we need this change as part of our next release. thanks

2025-01-13 09:04 UTC, dorkabcox commented
Dear Team, could you take this item with priority? Thank you!

2025-01-13 09:57 UTC, Phil91 approved these changes

2025-01-16 13:53 UTC, merged