feat(seeding): make seeder configureable
eclipse-tractusx/portal-backend pull request #1174
Opened 2024-11-22 12:45 UTC by Phil91

## Description

Add configuration to disable specific seeded values in the keycloak seeder

## Why

To be able to seed only wanted values

## Issue

Refs: #1172

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/admin/Dev%20Process/How%20to%20contribute.md#commits-branches-and-pull-requests-guidelines)
- [x] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-11-25 08:41 UTC, evegufy requested changes

2024-11-25 08:41 UTC, evegufy commented on src/keycloak/Keycloak.Seeding/Models/ConfigurationKeys.cs
> +    // TODO (PS): Clarify how to define the identity providers which should be skipped
see https://github.com/eclipse-tractusx/portal-iam/blob/main/import/realm-config/generic/catenax-central/CX-Central-users-0.json#L21

2024-11-25 08:41 UTC, evegufy commented on src/keycloak/Keycloak.Seeding/Models/ConfigurationKeys.cs
> +    public const string AuthenticatorConfigConfigKey = "AUTHENTICATORCONFIG";
use enum

2024-11-25 08:41 UTC, evegufy commented on src/keycloak/Keycloak.Seeding/appsettings.json
> +              "Delete": true
Please remove values that don't make sense (e.g. userProfiles) and document accordingly.

2024-11-25 12:13 UTC, ntruchsess requested changes

2024-11-25 12:13 UTC, ntruchsess commented on src/keycloak/Keycloak.Seeding/Models/ConfigurationKeys.cs
> +public enum ConfigurationKeys
I'd not use the plural in enum-types as the parameter that is being passed to a method is only a single value
```suggestion
public enum ConfigurationKey
```

2024-11-25 12:13 UTC, ntruchsess commented on src/keycloak/Keycloak.Seeding/Models/KeycloakRealmSettings.cs
> +    public IEnumerable<SeederConfiguration>? SeederConfiguration { get; set; }
```suggestion
    public IEnumerable<SeederConfiguration>? SeederConfigurations { get; set; }
```

2024-11-25 12:13 UTC, ntruchsess commented on src/keycloak/Keycloak.Seeding/BusinessLogic/ClientScopesUpdater.cs
> +    }
```suggestion
private static Task CheckAndExecute(ConfigurationKey configKey, ModificationType modificationType, KeycloakClient keycloak, string realm, IEnumerable<ClientScope> clientScopes, IEnumerable<ClientScopeModel> seedClientScopes, KeycloakRealmSettings seederConfig, CancellationToken cancellationToken, Func<KeycloakClient, string, IEnumerable<ClientScope>, IEnumerable<ClientScopeModel>, KeycloakRealmSettings, CancellationToken, Task> executeLogic) =>
        seederConfig.ModificationAllowed(configKey, modificationType)
            ? executeLogic(keycloak, realm, clientScopes, seedClientScopes, seederConfig, cancellationToken)
            : Task.CompletedTask;
```
(there are more occurences of this pattern that should be adjusted the same way)

2024-11-25 17:40 UTC, evegufy requested changes
Since https://github.com/eclipse-tractusx/portal-backend/pull/1174/commits/26ac07f279aab53a09f77ab3a0c1fd29eb40259d, [this configuration ](https://github.com/eclipse-tractusx/portal-iam/pull/234/files#diff-ee300b45d719481af34a480f94ace430d25f73c634f2591e9c1ba74b32e2cba1R193-R240)doesn't work anymore, for instance the cx-admin role isn't imported anymore, it works with the commit before https://github.com/eclipse-tractusx/portal-backend/pull/1174/commits/210bfb3a5473130e1b0661a61f93ca17f3366617

2024-11-26 16:22 UTC, evegufy approved these changes
I tested now everything successfully 👍

2024-11-27 08:04 UTC, ntruchsess commented on src/keycloak/Keycloak.Seeding/BusinessLogic/KeecloakSeeder.cs
> +    }
implemented

2024-11-27 08:04 UTC, ntruchsess commented on src/keycloak/Keycloak.Seeding/Models/KeycloakRealmSettings.cs
> +    public IEnumerable<SeederConfiguration>? SeederConfiguration { get; set; }
implemented

2024-11-27 08:04 UTC, ntruchsess commented on src/keycloak/Keycloak.Seeding/BusinessLogic/ClientScopesUpdater.cs
> +    }
implemented

2024-11-28 13:55 UTC, ntruchsess approved these changes

2024-11-28 14:09 UTC, ntruchsess approved these changes

2024-11-28 15:10 UTC, ntruchsess approved these changes

2024-11-28 15:17 UTC, ntruchsess approved these changes

2024-11-28 15:40 UTC, ntruchsess approved these changes

2024-11-28 16:35 UTC, evegufy approved these changes
tested again, looks good 👍

2024-11-28 17:19 UTC, merged