feat(error): error handling changes added in administrative services
eclipse-tractusx/portal-backend pull request #1192
Opened 2024-12-02 19:32 UTC by AnuragNagpure

## Description

Implement new error handling in below mentioned Administrative Services Controller and respective Business Logic
CompanyDataController
DocumentsController
IdentityProviderController
NetworkController
PartnerNetworkController
RegistrationController
RegistrationStatusController
ServiceAccountController
SubscriptionConfigurationController

All supported exceptions need to get transferred to the new error response method.

## Why

Implement for all controller and its business logic the new error handling - see details regarding the structure below.

## Issue

#1183 

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/admin/Dev%20Process/How%20to%20contribute.md#commits-branches-and-pull-requests-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-12-03 11:33 UTC, Phil91 requested changes
In my opinion it would make sense to add a `DefaultErrorMessageContainer` to the Framework.ErrorHandling -> ErrorHandling.

This could include a ENTITY_NOT_EXIST with the following error message: `{entityType} {entityId} does not exist`
It could include NULL_NOT_ALLOWED with the following error message: `{propertyName} must not be null`
It could include VALUE_EXPECTED with the following error message: `value for {headerProviderAlias} expected`
It could include ENTITY_ALREADY_EXISTS with the following error message: `{entityType} {entityId} already exist`

maybe there are a few more which can be aligned

2024-12-17 16:00 UTC, ntruchsess commented
> In my opinion it would make sense to add a `DefaultErrorMessageContainer` to the Framework.ErrorHandling -> ErrorHandling.
> 
> This could include a ENTITY_NOT_EXIST with the following error message: `{entityType} {entityId} does not exist` It could include NULL_NOT_ALLOWED with the following error message: `{propertyName} must not be null` It could include VALUE_EXPECTED with the following error message: `value for {headerProviderAlias} expected` It could include ENTITY_ALREADY_EXISTS with the following error message: `{entityType} {entityId} already exist`
> 
> maybe there are a few more which can be aligned

@Phil91 : Certainly having generic error-types would reduce the amount of code in the backend. But the idea is that the frontend can (optionally) do more than just pop-up an internationalized error-message. If appropriate it could precisely link to error-specific information that might help the user to resolve the issue. It's also the plan to implement a unified error-handling that any fe-code getting a standard-error from the backend just would delegate to. If error-codes were generic the fe would need to pass additional context-information to the error-handler. As a result the reduced amount of code in the backend would result in higher complexity in the frontend.

2024-12-18 05:58 UTC, Phil91 commented
> > In my opinion it would make sense to add a `DefaultErrorMessageContainer` to the Framework.ErrorHandling -> ErrorHandling.
> > This could include a ENTITY_NOT_EXIST with the following error message: `{entityType} {entityId} does not exist` It could include NULL_NOT_ALLOWED with the following error message: `{propertyName} must not be null` It could include VALUE_EXPECTED with the following error message: `value for {headerProviderAlias} expected` It could include ENTITY_ALREADY_EXISTS with the following error message: `{entityType} {entityId} already exist`
> > maybe there are a few more which can be aligned
> 
> @Phil91 : Certainly having generic error-types would reduce the amount of code in the backend. But the idea is that the frontend can (optionally) do more than just pop-up an internationalized error-message. If appropriate it could precisely link to error-specific information that might help the user to resolve the issue. It's also the plan to implement a unified error-handling that any fe-code getting a standard-error from the backend just would delegate to. If error-codes were generic the fe would need to pass additional context-information to the error-handler. As a result the reduced amount of code in the backend would result in higher complexity in the frontend.

@ntruchsess okay got the point, I will do a rereview. I think we can merge the pr after that.

2024-12-18 08:10 UTC, ntruchsess approved these changes

2024-12-18 08:12 UTC, Phil91 approved these changes

2024-12-18 08:13 UTC, merged