feat(bpdm): add error handling for fetch legal entity
eclipse-tractusx/portal-backend pull request #120
Opened 2023-07-03 09:22 UTC by Phil91

## Description

Changed the url to fetch the legal entity, for the bpn check in the application process

## Why

The endpoint got enhanced by an errorMessage for the internal error handling. With the new endpoint an operator is able to see the specific error that occured and handle it.

## Issue

N/A - Jira Issue: CPLP-2143

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2023-07-03 21:41 UTC, ntruchsess requested changes

2023-07-03 21:41 UTC, ntruchsess commented on src/externalsystems/Bpdm.Library/BpdmService.cs
> +            if (paginationResponse.Errors.Any())
use 'IfAny()':
```
            paginationResponse.Errors.IfAny(errors =>
                throw new ServiceException($"The external system bpdm responded with errors {string.Join(";", errors.Select(x => $"ErrorCode: {x.ErrorCode}, ErrorMessage: {x.Message}"))}"));
```

2023-07-03 21:41 UTC, ntruchsess commented on src/externalsystems/Bpdm.Library/BpdmService.cs
> +            if (paginationResponse == null || (paginationResponse.Content == null && paginationResponse.Errors == null))
the check of Content and Errors seems to be redundant as both are defined as 'non-nullable' in BpdmLegalEntityOutputData.cs

2023-07-03 21:41 UTC, ntruchsess commented on src/externalsystems/Bpdm.Library/BpdmService.cs
> +            if (paginationResponse.Content!.Count(x => x.ExternalId == externalId) != 1)
why not:
```
            try
            {
                return paginationResponse.Content!.Single(x => x.ExternalId == externalId);
            }
            catch(InvalidOperationException)
            {
                throw new ServiceException("Access to external system bpdm did not return a valid legal entity response", true);
            }
```

2023-07-03 21:41 UTC, ntruchsess commented on src/externalsystems/Bpdm.Library/BusinessLogic/IBpdmBusinessLogic.cs
> +using Org.Eclipse.TractusX.Portal.Backend.PortalBackend.PortalEntities.Enums;
using Enums is not referenced and can be removed

2023-07-03 21:41 UTC, ntruchsess commented on src/externalsystems/Bpdm.Library/IBpdmService.cs
> +using Org.Eclipse.TractusX.Portal.Backend.PortalBackend.PortalEntities.Enums;
both usings (Enums + Library) are not referenced and shall be removed

2023-07-04 11:22 UTC, Phil91 commented on src/externalsystems/Bpdm.Library/BpdmService.cs
> +            if (paginationResponse == null || (paginationResponse.Content == null && paginationResponse.Errors == null))
the problem is that somehow the json serializer completly ignores the fact that the two values are not nullable and sets them to null. there is now jsonException thrown or anything. I therefor decided to mark the two properties as nullable and do the check.

2023-07-13 08:16 UTC, ntruchsess approved these changes

2023-07-13 08:18 UTC, merged