feat(app)!: change app subscription process
eclipse-tractusx/portal-backend pull request #121
Opened 2023-07-04 14:01 UTC by Phil91

## Description

an inactive subscription now won't be activated, instead a new subscription will be created

the following endpoints have been changed from appId to subscriptionId:

/api/apps/supscription/{subscriptiondId}/activate
/api/apps/{subscriptionId}/unsubscribe

## Why

Since the subscription is linked to a technical user and an app instance we don't want to reactivate an inactive subscription. Instead we want to create a new one.

## Issue

N/A - Jira Issue: CPLP-2911

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2023-07-13 11:43 UTC, ntruchsess requested changes
I did rebase and change some exceptionTypes. Please pull before proceeding.

2023-07-13 11:43 UTC, ntruchsess commented on src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
> +    public async Task UnsubscribeOwnCompanyAppSubscriptionAsync(Guid subscriptionId, Guid companyId)
this method is lacking unit-tests

2023-07-14 07:11 UTC, Phil91 commented on src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
> +    public async Task UnsubscribeOwnCompanyAppSubscriptionAsync(Guid subscriptionId, Guid companyId)
added unit tests

2023-07-14 14:17 UTC, ntruchsess approved these changes

2023-07-14 14:25 UTC, ntruchsess commented
We need to clarify whether to remove the 'obsolete'-annotations on the updated endpoints (and code being referenced)

2023-07-14 15:52 UTC, merged