bug(notification):- get notification -count
eclipse-tractusx/portal-backend pull request #127
Opened 2023-07-06 08:17 UTC by qxz2mqe

## Description

fixed 500 error for notification count.

## Why

If there is no matching notification topic id in table notification_type_assigned_topics for notificationtypeid so null was returning through query due to which nullable exception was throwing 500 error.

## Issue
CPLP--2939

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)

- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my change

2023-07-06 09:17 UTC, Phil91 requested changes
Making the NotificationTopicId nullable will only solve the issue for the GetNotificationCount endpoint.

The problem we're currently facing is a missing configuration of notificationType to notificationTopic in my opinion. Please add the missing configuration to the notification_type_assigned_topic.json to make sure the seeding adds the missing values to our database.

Other than that code changes are fine.

2023-07-06 09:21 UTC, qxz2mqe commented
@Phil91  Can you please provide me the data and seeding data file name where I have to add it?

2023-07-06 09:25 UTC, Phil91 commented
> @Phil91 Can you please provide me the data and seeding data file name where I have to add it?

@qxz2mqe sure, the missing values are types: 23, 24, 25 they should been linked with topic 1.
i think as soon as the data are in the database we won't receive the null error anymore, but i doesn't hurt to have the NotificationTopicId nullable in the Get Repository call since it could always happen as we see right now.

2023-07-06 09:45 UTC, qxz2mqe commented
@Phil91  added the required data

2023-07-10 11:48 UTC, Phil91 requested changes

2023-07-10 13:23 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.DBAccess/Repositories/NotificationRepository.cs
> +    public IAsyncEnumerable<(bool IsRead, bool? Done, NotificationTopicId? NotificationTopicId, int Count)> GetCountDetailsForUserAsync(Guid companyUserId) =>
Can you please provide some example here?

2023-07-11 13:36 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.DBAccess/Repositories/NotificationRepository.cs
> +    public IAsyncEnumerable<(bool IsRead, bool? Done, NotificationTopicId? NotificationTopicId, int Count)> GetCountDetailsForUserAsync(Guid companyUserId) =>
fixed

2023-07-11 14:27 UTC, Phil91 requested changes
Could you please rebase to the latest dev, than i can approve and merge the PR

2023-07-11 18:46 UTC, merged