fix(connector): get discovery
eclipse-tractusx/portal-backend pull request #130
Opened 2023-07-07 06:47 UTC by qxz2mqe

## Description

updated swagger summary and description.

## Why

Description and summary was not providing clear picture of usage.

## Issue

CPLP-2931

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)

2023-07-07 07:37 UTC, Phil91 requested changes

2023-07-07 07:37 UTC, Phil91 commented on src/administration/Administration.Service/Controllers/ConnectorsController.cs
> +    /// post list of bpn and empty body to Retrieve available company connector.
the description is a bit confusing since you have to post a body, but the body could be an empty array.

@jjeroch should posting an empty body be possible?

```suggestion
    /// post list of bpns or an empty array to retrieve available company connector.
```

2023-07-11 08:20 UTC, Phil91 approved these changes

2023-07-11 14:36 UTC, jjeroch commented
@Phil91 agree, its a nice improvement to enable an empty body

2023-07-11 15:18 UTC, merged