feat(serviceaccount):- get owncompany serviceaccounts
eclipse-tractusx/portal-backend pull request #141
Opened 2023-07-13 09:44 UTC by qxz2mqe

## Description

Added relation for serviceaccount id in response body 

## Why

Added relation to know whether service account belongs to owner or provider

## Issue

CPLP-2786

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [ ] I have created and linked IP issues or requested their creation by a committer
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

2023-07-13 15:32 UTC, Phil91 requested changes

2023-07-13 15:32 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ServiceAccountRepository.cs
> +                serviceAccount.CompaniesLinkedServiceAccount!.Provider != null ? "provider" : "owner",
this needs either to be the value of provider or owner not a string value but instead the uuid of the database column of the view

2023-07-13 15:32 UTC, Phil91 commented on tests/portalbackend/PortalBackend.DBAccess.Tests/ServiceAccountRespotitoryTests.cs
> +            result.Data.First().Relation.Should().Be("owner");
Please adjust the test accordingly after changing the implementation

2023-07-13 15:34 UTC, Phil91 commented
@ntruchsess could you please also have a look at it as well?
I'm not quite sure about the "migration" since we want to use the view to get the data of the provider / owner it seems to be needed to have a key (at least for ef to be able to create the navigation and links) i tryed different solutions by myself but didn't came up with something better.

2023-07-13 15:49 UTC, ntruchsess requested changes

2023-07-13 15:49 UTC, ntruchsess commented on src/portalbackend/PortalBackend.Migrations/Migrations/20230713071711_CPLP-2786-AddCompanyAccountServiceToView.cs
> +        protected override void Up(MigrationBuilder migrationBuilder)
It's sufficient to have the changes in DbContext, there is no point in creating an empty migration. Please remove.

2023-07-13 15:49 UTC, ntruchsess commented on src/portalbackend/PortalBackend.Migrations/Migrations/20230713071711_CPLP-2786-AddCompanyAccountServiceToView.Designer.cs
> +namespace Org.Eclipse.TractusX.Portal.Backend.PortalBackend.Migrations.Migrations
It's sufficient to have the changes in DbContext, there is no point in creating an empty migration. Please remove.

2023-07-13 15:49 UTC, ntruchsess commented on src/portalbackend/PortalBackend.Migrations/Migrations/PortalDbContextModelSnapshot.cs
> +﻿/********************************************************************************
It's sufficient to have the changes in DbContext, there is no point in creating an empty migration. Please revert those changes of the snapshot.

2023-07-14 05:38 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.Migrations/Migrations/PortalDbContextModelSnapshot.cs
> +﻿/********************************************************************************
reverted

2023-07-14 05:38 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.Migrations/Migrations/20230713071711_CPLP-2786-AddCompanyAccountServiceToView.Designer.cs
> +namespace Org.Eclipse.TractusX.Portal.Backend.PortalBackend.Migrations.Migrations
reverted

2023-07-14 05:39 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.Migrations/Migrations/20230713071711_CPLP-2786-AddCompanyAccountServiceToView.cs
> +        protected override void Up(MigrationBuilder migrationBuilder)
reverted

2023-07-14 07:32 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ServiceAccountRepository.cs
> +                serviceAccount.CompaniesLinkedServiceAccount!.Provider != null ? "provider" : "owner",
@Phil91  I have clarified with julia and it is string

2023-07-14 07:33 UTC, qxz2mqe commented on tests/portalbackend/PortalBackend.DBAccess.Tests/ServiceAccountRespotitoryTests.cs
> +            result.Data.First().Relation.Should().Be("owner");
No change is required as confirm with julia

2023-07-14 08:43 UTC, ntruchsess requested changes

2023-07-14 08:43 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ServiceAccountRepository.cs
> +                serviceAccount.CompaniesLinkedServiceAccount!.Provider != null ? "provider" : "owner",
please create an enum-type 'CompaniesLinkedServiceAccountType' in DbAccess/Models and use that (Then database will return an int while the json-serialization will take care of converting the enum-value to string).

2023-07-14 08:43 UTC, ntruchsess commented on src/portalbackend/PortalBackend.Migrations/Migrations/PortalDbContextModelSnapshot.cs
> +﻿/********************************************************************************
to revert checkout the previous version of the file. This one still has changes (it has changed to encoding 'UTF-8 with BOM' while it should be plain UTF-8)

2023-07-14 08:43 UTC, ntruchsess commented on src/portalbackend/PortalBackend.PortalEntities/Entities/CompanyServiceAccount.cs
> +    public virtual CompaniesLinkedServiceAccount? CompaniesLinkedServiceAccount { get; set; }
set must not be public as - while the pk of this relationship is on the other side - this other side is a view that cannot be updated.

2023-07-14 08:43 UTC, ntruchsess commented on src/portalbackend/PortalBackend.PortalEntities/Views/CompaniesLinkedServiceAccount.cs
>      public Guid ServiceAccountId { get; set; }
all setters must be private as the view cannot be updated.

2023-07-14 10:25 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ServiceAccountRepository.cs
> +                serviceAccount.CompaniesLinkedServiceAccount!.Provider != null ? "provider" : "owner",
@ntruchsess had a discussion with julia about the string value, we agreed on changing it to a bool flag to decide whether it's a the provider or owner

2023-07-14 10:35 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ServiceAccountRepository.cs
> +                serviceAccount.CompaniesLinkedServiceAccount!.Provider != null ? "provider" : "owner",
fixed

2023-07-14 10:36 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.Migrations/Migrations/PortalDbContextModelSnapshot.cs
> +﻿/********************************************************************************
fixed

2023-07-14 10:36 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.PortalEntities/Entities/CompanyServiceAccount.cs
> +    public virtual CompaniesLinkedServiceAccount? CompaniesLinkedServiceAccount { get; set; }
fixed

2023-07-14 10:37 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.PortalEntities/Views/CompaniesLinkedServiceAccount.cs
>      public Guid ServiceAccountId { get; set; }
fixed

2023-07-14 10:37 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.DBAccess/Models/CompanyServiceAccountData.cs
> +    [property: JsonPropertyName("relation")] string Relation,
fixed

2023-07-14 16:29 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ServiceAccountRepository.cs
> +                serviceAccount.CompaniesLinkedServiceAccount!.Provider != null ? false : true,
did fix my own comment.

2023-07-17 06:15 UTC, merged