feat(serviceaccount): get service accounts by Id
eclipse-tractusx/portal-backend pull request #145
Opened 2023-07-17 09:38 UTC by qxz2mqe

## Description

added validation for company of user executing endpoint is  is owner or provider

## Why

Earlier check was If user belongs to same company then allow to execute the end point now if it is of owner or provider company also then it shoild allow to execute the endpoint

## Issue

CPLP-2830

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- - [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

2023-07-17 10:15 UTC, Phil91 requested changes

2023-07-17 10:15 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
> +        if (!await _portalRepositories.GetInstance<IServiceAccountRepository>().IsCompanyServiceAccountLinkedCompany(serviceAccountId, companyId).ConfigureAwait(false))
If executing this with an technical user the first if statement will be successful, but the result returned from `GetOwnCompanyServiceAccountDetailedDataUntrackedAsync` will be null and a ConflictException will be thrown.

Please remove the `IsCompanyServiceAccountLinkedCompany` call and edit the `GetOwnCompanyServiceAccountDetailedDataUntrackedAsync` 

Please test the changes locally before rerequesting the review

2023-07-20 06:16 UTC, Phil91 requested changes
Please add some UnitTests for `GetOwnCompanyServiceAccountDetailedDataUntrackedAsync` to check the result for the company check

2023-07-20 06:16 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ServiceAccountRepository.cs
> +                serviceAccount.Identity.CompanyId == companyId && (serviceAccount.CompaniesLinkedServiceAccount!.Owners == companyId || serviceAccount.CompaniesLinkedServiceAccount!.Provider == compa
The check of the identity.CompanyId can be removed since we do the check for a matching company with the companiesLinkedServiceAccount

```suggestion
                serviceAccount.CompaniesLinkedServiceAccount!.Owners == companyId || serviceAccount.CompaniesLinkedServiceAccount!.Provider == companyId)
```

2023-07-21 12:21 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ServiceAccountRepository.cs
> +                serviceAccount.Identity.CompanyId == companyId && (serviceAccount.CompaniesLinkedServiceAccount!.Owners == companyId || serviceAccount.CompaniesLinkedServiceAccount!.Provider == compa
fixed

2023-07-25 08:52 UTC, Phil91 requested changes
The `ServiceAccountRepositoryTests` should include additional two Tests to check the result of the `GetOwnCompanyServiceAccountDetailedDataUntrackedAsync` one if the serviceAccount has different OwnerId than ProviderId the companyId equals the provider of the serviceAccount. And one to test if we have a valid serviceAccountId with a not matching companyId

2023-07-26 05:36 UTC, qxz2mqe commented
@Phil91  Added the Unit Test

2023-07-31 14:32 UTC, Phil91 approved these changes

2023-08-01 06:19 UTC, Phil91 approved these changes

2023-08-01 06:21 UTC, merged