feat(audit): set lastEditorId when changing auditable entities
eclipse-tractusx/portal-backend pull request #147
Opened 2023-07-18 08:21 UTC by Phil91

## Description

lastEditorId is now set whenever a auditable entity is changed 
index for lastEditorId columns created

## Why

to be able to see who changed a auditable entity

## Issue

N/A - Jira Ticket: CPLP-2960

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2023-07-24 06:39 UTC, Phil91 commented
@ntruchsess the latest changes are in

2023-07-27 18:25 UTC, ntruchsess requested changes
I did some cleanup removing the remaining writes to LastEditorId and some redundant uses of WithUserIdAndCompanyId that have been added lately. Please double-check. In case there were good reasons for those calls that I just don't see let's discuss this.

2023-07-27 18:25 UTC, ntruchsess commented on src/administration/Administration.Service/Controllers/CompanyDataController.cs
> +    // [Authorize(Roles = "request_ssicredential")]
have those authorizations been removed on purpose?

2023-07-27 18:25 UTC, ntruchsess commented on src/portalbackend/PortalBackend.PortalEntities/PortalDbContext.cs
> +        Console.WriteLine("Constructor without params hit");
maybe throwing InvalidOperationException is more suitable? The console-output might not be visible anywhere.

2023-07-29 14:56 UTC, Phil91 commented on src/administration/Administration.Service/Controllers/CompanyDataController.cs
> +    // [Authorize(Roles = "request_ssicredential")]
that wasn't on purpose, i did rollback the removal

2023-07-29 14:57 UTC, Phil91 commented on src/portalbackend/PortalBackend.PortalEntities/PortalDbContext.cs
> +        Console.WriteLine("Constructor without params hit");
Agreed, i did change the implementation

2023-07-31 07:42 UTC, Phil91 commented
@ntruchsess all changes are in, please be aware of the cd pr [#54](https://github.com/eclipse-tractusx/portal-cd/pull/54)

2023-07-31 12:26 UTC, ntruchsess approved these changes

2023-07-31 12:29 UTC, merged