feat(apps & services): put and post enpoints
eclipse-tractusx/portal-backend pull request #152
Opened 2023-07-19 06:41 UTC by qxz2mqe

## Description

Added DateLastChanged for most of endpoints of apps and services for put and post
## Why

Added DateLastChanged so that whenever we are updating or creating a record for offer related table there should be update for last date 
## Issue

CPLP-2886

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

2023-07-21 13:03 UTC, closed without merging

2023-07-22 23:14 UTC, Phil91 requested changes
the DateLastChanged is currently not set within the 

/api/apps/AppReleaseProcess/createapp endpoint, please add that to the logic

2023-07-22 23:14 UTC, Phil91 commented on src/marketplace/Services.Service/BusinessLogic/ServiceReleaseBusinessLogic.cs
> +                offer.DateLastChanged = DateTimeOffset.UtcNow;
please don't set the DateLastChanged in the initialize to DateTimeOffset.UtcNow, either set it to the correct database value or remove the call since the value will be set in the modify action and the set value isn't null or default

2023-07-22 23:15 UTC, Phil91 commented
@jjeroch  most of the endpoints are not directly changing the offer. in most cases we set or remove an entry in a mapping table.

exceptions for that are:

/api/apps/AppReleaseProcess/createapp
/api/apps/AppReleaseProcess/{appId}

do we really want to change the logic this way?

2023-07-24 07:27 UTC, qxz2mqe commented on src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
> +        _portalRepositories.GetInstance<IOfferRepository>().AttachAndModifyOffer(appId, offer =>
fixed

2023-07-24 07:28 UTC, qxz2mqe commented on src/marketplace/Services.Service/BusinessLogic/ServiceReleaseBusinessLogic.cs
> +                offer.DateLastChanged = DateTimeOffset.UtcNow;
fixed

2023-07-24 10:18 UTC, Phil91 commented
> @jjeroch most of the endpoints are not directly changing the offer. in most cases we set or remove an entry in a mapping table.
> 
> exceptions for that are:
> 
> /api/apps/AppReleaseProcess/createapp /api/apps/AppReleaseProcess/{appId}
> 
> do we really want to change the logic this way?

clarified, the logic should be as soon as an offer or offer related entity changes, the DateLastChanged of the offer should be updated

2023-07-24 16:59 UTC, Phil91 approved these changes