fix(invitedUsers): filter deleted users for invitedUsers endpoint
eclipse-tractusx/portal-backend pull request #155
Opened 2023-07-20 08:46 UTC by Phil91

## Description

Remove the deleted users from the invitedUsers request

## Why

Deleted users don't have an userEntityId, therefor the request will fail when keycloak is requested for the user informations

## Issue

N/A - Jira Issue: CPLP-2986

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2023-07-28 06:56 UTC, ntruchsess requested changes

2023-07-28 06:56 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/InvitationRepository.cs
> +        _dbContext.Invitations
I suggest:
```
    public IAsyncEnumerable<InvitedUserDetail> GetInvitedUserDetailsUntrackedAsync(Guid applicationId) =>
        _dbContext.Invitations
            .AsNoTracking()
            .Where(invitation => invitation.CompanyApplicationId == applicationId && invitation.CompanyUser!.Identity!.UserStatusId != UserStatusId.DELETED)
            .Select(invitation => new InvitedUserDetail(
                invitation.CompanyUser!.Identity!.UserEntityId,
                invitation.InvitationStatusId,
                invitation.CompanyUser.Email))
            .AsAsyncEnumerable();
```

2023-07-28 06:56 UTC, ntruchsess commented on tests/portalbackend/PortalBackend.DBAccess.Tests/InvitationRepositoryTests.cs
> +        result.Should().NotBeNull();
I suggest:
```
        result.Should().HaveCount(2)
            .And.Satisfy(
                x => x.EmailId == "test@user.com" && x.InvitationStatus == InvitationStatusId.CREATED,
                x => x.EmailId == "company.admin1@acme.corp" && x.InvitationStatus == InvitationStatusId.CREATED);
```
(there's no point in asserting 'NotBeNull()' if there are more asserts that implicitly fail if NotBeNull is not satisfied)

2023-07-29 15:21 UTC, Phil91 commented on tests/portalbackend/PortalBackend.DBAccess.Tests/InvitationRepositoryTests.cs
> +        result.Should().NotBeNull();
adjusted

2023-07-29 15:21 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/InvitationRepository.cs
> +        _dbContext.Invitations
adjusted

2023-07-31 13:07 UTC, ntruchsess approved these changes

2023-07-31 13:09 UTC, merged