Feature/cplp 2958 open apis
eclipse-tractusx/portal-backend pull request #161
Opened 2023-07-21 13:57 UTC by Phil91

## Description

Add GET endpoint to receive public apis foreach service

## Why

To be able to display the public available urls in the frontend a new endpoint was needed

## Issue

N/A - Jira Issue: CPLP-2958

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2023-08-07 21:32 UTC, ntruchsess requested changes

2023-08-07 21:32 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRepository.cs
> +            .ToArrayAsync();
the query should return IAsyncEnumerable, any materialization via ToArrayAsync or ToListAsync should be executed in the businessLogic

2023-08-07 21:32 UTC, ntruchsess commented on src/framework/Framework.PublicInfos/PublicInformationBusinessLogic.cs
> +    public async Task<IEnumerable<UrlInformation>> GetPublicUrls(Guid companyId)
1) I suggest to use linq instead of list + foreach/add:
```
    public async Task<IEnumerable<UrlInformation>> GetPublicUrls(Guid companyId)
    {
        var companyRoleIds = await _portalRepositories.GetInstance<ICompanyRepository>().GetOwnCompanyRolesAsync(companyId).ConfigureAwait(false);
        return _actionDescriptorCollectionProvider.ActionDescriptors.Items
            .Where(item => item.ActionConstraints != null)
            .OfType<ControllerActionDescriptor>()
            .Where(item => item.MethodInfo.GetCustomAttribute<PublicUrlAttribute>()?.CompanyRoleIds.Intersect(companyRoleIds).Any() ?? false)
            .Select(item =>
                new UrlInformation(
                    string.Join(", ", item.ActionConstraints!.OfType<HttpMethodActionConstraint>().SelectMany(x => x.HttpMethods).Distinct()),
                    (item.AttributeRouteInfo?.Template ?? throw new ConflictException($"There must be an url for {item.DisplayName}")).ToLower()));
    }
```
2) this method is missing an explicit unit-test that works independent from real controller classes (using a faked IActionDescriptorCollection + faked repository-call)

2023-08-08 13:53 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRepository.cs
> +            .ToArrayAsync();
adjusted

2023-08-08 13:53 UTC, Phil91 commented on src/framework/Framework.PublicInfos/PublicInformationBusinessLogic.cs
> +    public async Task<IEnumerable<UrlInformation>> GetPublicUrls(Guid companyId)
changed it to a linq statement instead and added unit tests for it.

2023-08-11 12:14 UTC, ntruchsess requested changes

2023-08-11 12:14 UTC, ntruchsess commented on tests/maintenance/Maintenance.App.Tests/Setup/TestDbFixture.cs
> +        // BaseSeed.SeedData().Invoke(context);
that commented line of code shall be removed. Looks like the previously called method now does not have any references and can be removed as well. (please also check the other static 'SeedData()'-methods as the appear to also have 0 references, but maybe my code-scanner is incorrect here?)

2023-08-11 12:31 UTC, Phil91 commented on tests/maintenance/Maintenance.App.Tests/Setup/TestDbFixture.cs
> +        // BaseSeed.SeedData().Invoke(context);
removed the commented out code.

The SeedData is used in `ServiceCollectionExtensions`  in the Method `EnsureDbCreatedWithSeeding<TSeedingData>`

2023-08-11 13:09 UTC, ntruchsess approved these changes

2023-08-11 13:11 UTC, merged