feat(bpdm): adjust bpdm service calls to new service
eclipse-tractusx/portal-backend pull request #164
Opened 2023-07-24 13:48 UTC by Phil91

## Description

Change BPDM-Service Calls for the new Service
Align Service Models

## Why

structure of bpdm service has changed, therefor the models have been aligned

## Issue

N/A - Jira Ticket: CPLP-2976

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2023-07-27 20:06 UTC, ntruchsess requested changes

2023-07-27 20:06 UTC, ntruchsess commented on src/externalsystems/Bpdm.Library/BpnAccess.cs
> +        if (!result.IsSuccessStatusCode)
consider use of HttpAsyncResponseMessageExtension.CatchingIntoServiceExceptionFor

2023-07-27 20:06 UTC, ntruchsess commented on src/externalsystems/Bpdm.Library/BpnAccess.cs
> +            var legalEntityResponse = await JsonSerializer.DeserializeAsync<BpdmLegalEntityDto>(
consider use of HttpContentJsonExtensions.ReadFromJsonAsync

2023-07-29 15:11 UTC, Phil91 commented on src/externalsystems/Bpdm.Library/BpnAccess.cs
> +            var legalEntityResponse = await JsonSerializer.DeserializeAsync<BpdmLegalEntityDto>(
changed

2023-07-29 15:11 UTC, Phil91 commented on src/externalsystems/Bpdm.Library/BpnAccess.cs
> +        if (!result.IsSuccessStatusCode)
changed

2023-07-31 12:33 UTC, ntruchsess approved these changes

2023-07-31 12:55 UTC, merged