updates(email templates):  welcome email
eclipse-tractusx/portal-backend pull request #169
Opened 2023-07-26 12:55 UTC by manojava-gk

## Description

update welcome email content. provide link icon when link text is present

## Why

change request

## Issue

NA

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally

2023-07-28 12:30 UTC, ntruchsess requested changes

2023-07-28 17:31 UTC, ntruchsess approved these changes

2023-08-02 21:19 UTC, jjeroch commented
@ntruchsess  lets merge this change please

2023-08-04 06:28 UTC, ntruchsess approved these changes

2023-08-04 06:29 UTC, merged