Feature/cplp 2650 keycloak seeding
eclipse-tractusx/portal-backend pull request #184
Opened 2023-08-04 10:27 UTC by ntruchsess

## Description

This PR contains a new program that allows to upload (seed) realm-data from a json-file that can be created by doing an export (backup) of a realm in keycloak. In case the realm does already exist the entities in the target-realm are not replaced but updated accordingly. In respect to entities not existing in the import-file but existing in the keycloak-realm different strategies are implemented. Top-level-entities that usually are created via normal processes of portal-backend processes (like users, idps and clients) are never deleted. Subordenary entities that are part of the configuration of such top-level entity (like mappers belonging to an existing identityprovider) can be deleted if existing in keycloak but not in the import-json.

## Why

The import-facility of keycloak is not capable to do such delta-updates on existing realms. Future versions of keycloak do support even less functionality on the initial import.

## Issue

N/A, CPLP-2650

## Checklist

Please delete options that are not relevant.

- [X] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [X] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [X] I have performed a self-review of my own code
- [X] I have successfully tested my changes locally
- [X] I have added tests that prove my changes work
- [X] I have checked that new and existing tests pass locally with my changes
- [X] I have commented my code, particularly in hard-to-understand areas

2023-08-08 16:19 UTC, evegufy commented
@ntruchsess as discussed, please solve or comment the sonarcloud issue.
Here is the pr for the workflows: https://github.com/catenax-ng/tx-portal-backend/pull/408

2023-08-09 16:08 UTC, Phil91 requested changes

2023-08-09 16:08 UTC, Phil91 commented on src/keycloak/Keycloak.Seeding/appsettings.json
> +  },
The logging section can be removed due to serilog

2023-08-09 16:08 UTC, Phil91 commented on src/keycloak/Keycloak.Seeding/appsettings.json
> +    "MinimumLevel": "Information",
The minimumLevel section should be changed into the following:

```suggestion
"MinimumLevel": {
    "Default": "Information",
    "Override": {
    "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
},
```

2023-08-10 10:52 UTC, evegufy commented on src/keycloak/Keycloak.Seeding/Program.cs
> +    Log.Fatal(ex, "Unhandled exception");
Please throw exception after logging

2023-08-10 10:55 UTC, evegufy requested changes

2023-08-10 10:55 UTC, evegufy commented on src/keycloak/Keycloak.Seeding/appsettings.json
> +    "master": {
Please change to the more intuitive value of 'central' here

2023-08-10 11:18 UTC, ntruchsess commented on src/keycloak/Keycloak.Seeding/BusinessLogic/KeecloakSeeder.cs
> +        foreach (var dataPath in _settings.DataPathes)
as those imports would run in parallel on the same keycloak-instance and the algorithm is determining the difference in between existing and seeding data it's likely to run into concurrency-issues if 'existing' data is changing from parallel updates while a particular dataPath is being processed.

2023-08-11 11:44 UTC, ntruchsess commented on src/keycloak/Keycloak.Seeding/readme.md
> +﻿# Lorem ipsum
removed

2023-08-11 11:46 UTC, ntruchsess commented on src/keycloak/Keycloak.Seeding/BusinessLogic/KeecloakSeeder.cs
> +        foreach (var dataPath in _settings.DataPathes)
as discussed - any parallelism here might lead to concurrency-issues.

2023-08-11 12:50 UTC, ntruchsess commented on src/keycloak/Keycloak.Seeding/appsettings.json
> +  },
removed

2023-08-11 12:54 UTC, ntruchsess commented on src/keycloak/Keycloak.Seeding/BusinessLogic/UsersUpdater.cs
> +        // FederationLink = update.FederationLink,
removed

2023-08-11 13:02 UTC, ntruchsess commented on src/keycloak/Keycloak.Seeding/Program.cs
> +    Log.Fatal(ex, "Unhandled exception");
setting exit-code to 1 in case of unhandled exception

2023-08-11 13:02 UTC, ntruchsess commented on src/keycloak/Keycloak.Seeding/appsettings.json
> +    "master": {
done

2023-08-11 13:19 UTC, ntruchsess commented on src/keycloak/Keycloak.Seeding/BusinessLogic/RealmUpdater.cs
> +    private static bool CompareRealm(Realm keycloakRealm, KeycloakRealm seedRealm) =>
fixed

2023-08-11 13:19 UTC, ntruchsess commented on src/keycloak/Keycloak.Seeding/BusinessLogic/UsersUpdater.cs
> +    private static bool CompareUser(User user, UserModel update) =>
fixed

2023-08-11 13:44 UTC, Phil91 approved these changes

2023-08-11 15:13 UTC, evegufy approved these changes
Local tests were successful.

2023-08-11 15:21 UTC, merged