release: merge main to dev
eclipse-tractusx/portal-backend pull request #189
Opened 2023-08-07 13:55 UTC by Phil91

## Description

merge the latest main to dev

## Why

to have the latest changes available on dev

## Issue

N/A

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally

2023-08-07 16:01 UTC, ntruchsess requested changes

2023-08-07 16:01 UTC, ntruchsess commented on tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/company_service_accounts.test.json
> -  {
as this duplicate exists in main as well we need to fix it there first, then rebase this branch.

2023-08-07 17:16 UTC, Phil91 commented on tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/company_service_accounts.test.json
> -  {
it doesn't see: [company_service_accounts.test.json](https://github.com/eclipse-tractusx/portal-backend/blob/main/tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/company_service_accounts.test.json) on main the duplicate was introduced with the merge from main to dev

2023-08-08 08:58 UTC, ntruchsess approved these changes

2023-08-08 09:02 UTC, merged