fix(serviceaccount):= get owncompany serviceaccount
eclipse-tractusx/portal-backend pull request #202
Opened 2023-08-16 06:07 UTC by qxz2mqe

## Description

Added provider and owner instead of identity companyid in query
## Why

Response was returning serviceaccounts only for logged in user company not for provider and owner.

## Issue

CPLP-3113.

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [ ] I have created and linked IP issues or requested their creation by a committer
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

2023-08-16 14:29 UTC, ntruchsess commented
please don't use special characters in branch-names. Github is complaining:
'The head ref may contain hidden characters: "bug/cplp-3113-tech-user\u2014not=display"'

2023-08-16 14:32 UTC, ntruchsess requested changes

2023-08-16 16:21 UTC, ntruchsess requested changes

2023-08-17 10:49 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ServiceAccountRepository.cs
> +                    (serviceAccount.CompaniesLinkedServiceAccount!.Owners == userCompanyId || serviceAccount.CompaniesLinkedServiceAccount!.Provider == userCompanyId) &&
fixed

2023-08-17 11:12 UTC, Phil91 approved these changes

2023-08-17 11:18 UTC, merged