chore: upgrade .NET
eclipse-tractusx/portal-backend pull request #203
Opened 2023-08-16 07:09 UTC by Phil91

## Description

- upgrade .NET to v7
- upgrade nuget packages
- remove trigger dependency
- write audit entities automatically on DbContext SaveChanges

## Why

To be able to use the latest features of the latest version of .NET and nuget Packages.
Removed the trigger dependency to use custom logic

## Issue

N/A - Jira Issues: CPLP-2897, CPLP-3100

## Corresponding Assets PR

[#134](https://github.com/eclipse-tractusx/portal-assets/pull/134)

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2023-08-16 10:05 UTC, Phil91 commented
IP Team Reviews have been created:

[AutoFixture/4.18.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10057)
[AutoFixture.AutoFakeItEasy/4.18.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10064)
[AutoFixture.Xunit/4.18.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10082)
[BouncyCastle.Cryptography/2.2.1](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10066)
[coverlet.collector/6.0.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10075)
[EFCore.NamingConventions/7.0.2](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10067)
[FakeItEasy/7.4.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10080)
[FluentAssertions/6.11.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10061)
[Humanizer.Core/2.14.1](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10060)
[MailKit/4.1.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10076)
[MimeKit/4.1.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10079)
[Npgsql/7.0.4](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10062)
[Npgsql.EntityFrameworkCore.PostgreSQL/7.0.4](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10081)
[Serilog/3.0.1](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10063)
[Serilog.AspNetCore/7.0.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10084)
[Serilog.Extensions.Hosting/7.0.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10078)
[Serilog.Extensions.Logging/7.0.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10070
[Serilog.Settings.Configuration/7.0.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10069)
[SSH.NET/2020.0.2](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10073)
[SharpZipLib/1.4.2](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10058)
[Testcontainers/3.4.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10083)
[Testcontainers.PostgreSql/3.4.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10056)
[xunit/2.5.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10072)
[xunit.analyzers/1.2.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10068)
[xunit.assert/2.5.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10071)
[xunit.core/2.5.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10059)
[xunit.extensibility.core/2.5.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10077)
[xunit.extensibility.execution/2.5.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10074)
[xunit.runner.visualstudio/2.5.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10065

2023-08-16 11:51 UTC, Phil91 commented
@ntruchsess please don't merge this PR, I'd take over as soon as this is approved due to the currently still pending dependency checks

2023-08-30 18:36 UTC, ntruchsess commented
I get a conflict-warning when building the Migrations:
```
/usr/share/dotnet/sdk/7.0.400/Microsoft.Common.CurrentVersion.targets(2364,5): warning MSB3277: Found conflicts between different versions of "Microsoft.EntityFrameworkCore.Relational" that could not be resolved. [/home/norbert/tx-portal-backend/src/framework/Framework.ProcessIdentity/Framework.ProcessIdentity.csproj]
/usr/share/dotnet/sdk/7.0.400/Microsoft.Common.CurrentVersion.targets(2364,5): warning MSB3277: There was a conflict between "Microsoft.EntityFrameworkCore.Relational, Version=7.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" and "Microsoft.EntityFrameworkCore.Relational, Version=7.0.10.0, Culture=neutral, PublicKeyToken=adb9793829ddae60". [/home/norbert/tx-portal-backend/src/framework/Framework.ProcessIdentity/Framework.ProcessIdentity.csproj]
/usr/share/dotnet/sdk/7.0.400/Microsoft.Common.CurrentVersion.targets(2364,5): warning MSB3277:     "Microsoft.EntityFrameworkCore.Relational, Version=7.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" was chosen because it was primary and "Microsoft.EntityFrameworkCore.Relational, Version=7.0.10.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" was not. [/home/norbert/tx-portal-backend/src/framework/Framework.ProcessIdentity/Framework.ProcessIdentity.csproj]
/usr/share/dotnet/sdk/7.0.400/Microsoft.Common.CurrentVersion.targets(2364,5): warning MSB3277:     References which depend on "Microsoft.EntityFrameworkCore.Relational, Version=7.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" [/home/norbert/.nuget/packages/microsoft.entityframeworkcore.relational/7.0.5/lib/net6.0/Microsoft.EntityFrameworkCore.Relational.dll]. [/home/norbert/tx-portal-backend/src/framework/Framework.ProcessIdentity/Framework.ProcessIdentity.csproj]
/usr/share/dotnet/sdk/7.0.400/Microsoft.Common.CurrentVersion.targets(2364,5): warning MSB3277:         /home/norbert/.nuget/packages/microsoft.entityframeworkcore.relational/7.0.5/lib/net6.0/Microsoft.EntityFrameworkCore.Relational.dll [/home/norbert/tx-portal-backend/src/framework/Framework.ProcessIdentity/Framework.ProcessIdentity.csproj]
/usr/share/dotnet/sdk/7.0.400/Microsoft.Common.CurrentVersion.targets(2364,5): warning MSB3277:           Project file item includes which caused reference "/home/norbert/.nuget/packages/microsoft.entityframeworkcore.relational/7.0.5/lib/net6.0/Microsoft.EntityFrameworkCore.Relational.dll". [/home/norbert/tx-portal-backend/src/framework/Framework.ProcessIdentity/Framework.ProcessIdentity.csproj]
/usr/share/dotnet/sdk/7.0.400/Microsoft.Common.CurrentVersion.targets(2364,5): warning MSB3277:             /home/norbert/.nuget/packages/microsoft.entityframeworkcore.relational/7.0.5/lib/net6.0/Microsoft.EntityFrameworkCore.Relational.dll [/home/norbert/tx-portal-backend/src/framework/Framework.ProcessIdentity/Framework.ProcessIdentity.csproj]
/usr/share/dotnet/sdk/7.0.400/Microsoft.Common.CurrentVersion.targets(2364,5): warning MSB3277:     References which depend on "Microsoft.EntityFrameworkCore.Relational, Version=7.0.10.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" []. [/home/norbert/tx-portal-backend/src/framework/Framework.ProcessIdentity/Framework.ProcessIdentity.csproj]
/usr/share/dotnet/sdk/7.0.400/Microsoft.Common.CurrentVersion.targets(2364,5): warning MSB3277:         /home/norbert/tx-portal-backend/src/portalbackend/PortalBackend.PortalEntities/bin/Debug/net7.0/Org.Eclipse.TractusX.Portal.Backend.PortalBackend.PortalEntities.dll [/home/norbert/tx-portal-backend/src/framework/Framework.ProcessIdentity/Framework.ProcessIdentity.csproj]
/usr/share/dotnet/sdk/7.0.400/Microsoft.Common.CurrentVersion.targets(2364,5): warning MSB3277:           Project file item includes which caused reference "/home/norbert/tx-portal-backend/src/portalbackend/PortalBackend.PortalEntities/bin/Debug/net7.0/Org.Eclipse.TractusX.Portal.Backend.PortalBackend.PortalEntities.dll". [/home/norbert/tx-portal-backend/src/framework/Framework.ProcessIdentity/Framework.ProcessIdentity.csproj]
/usr/share/dotnet/sdk/7.0.400/Microsoft.Common.CurrentVersion.targets(2364,5): warning MSB3277:             /home/norbert/tx-portal-backend/src/portalbackend/PortalBackend.PortalEntities/bin/Debug/net7.0/Org.Eclipse.TractusX.Portal.Backend.PortalBackend.PortalEntities.dll [/home/norbert/tx-portal-backend/src/framework/Framework.ProcessIdentity/Framework.ProcessIdentity.csproj]
```

2023-08-30 18:47 UTC, ntruchsess requested changes

2023-08-30 18:47 UTC, ntruchsess commented on src/portalbackend/PortalBackend.PortalEntities/Auditing/AuditHandlerV1.cs
> +            return;
this should never happen as AuditEntityV1Attribute can only be used on types implementing IAuditEntityV1. As an assertion this has not been changed throw UnexpectedConditionException instead of returning silently.

2023-08-30 18:47 UTC, ntruchsess commented on src/portalbackend/PortalBackend.PortalEntities/Auditing/AuditHandlerV1.cs
> +        var sourceProperties = new List<PropertyInfo>();
linq-style:
```
        var sourceProperties = (typeof(IBaseEntity).IsAssignableFrom(entityType)
                ? typeof(IBaseEntity).GetProperties()
                : Enumerable.Empty<PropertyInfo>())
            .Concat(entityType.GetProperties(BindingFlags.Public |
                                             BindingFlags.Instance |
                                             BindingFlags.DeclaredOnly).Where(p => !(p.GetGetMethod()?.IsVirtual ?? false)))
            .ToList();

```

2023-08-30 18:47 UTC, ntruchsess commented on src/portalbackend/PortalBackend.PortalEntities/Auditing/AuditValidation.cs
> +        if (typeof(IBaseEntity).IsAssignableFrom(auditableEntityType))
there is quite a lot of duplicated code in this method and AuditHandlerV1 that should be implemented only once and be reused.

2023-08-31 16:04 UTC, ntruchsess requested changes

2023-09-01 08:09 UTC, Phil91 commented
IP Team Reviews have been created for the trigger framework:

- [ ] https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10247
- [ ] https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10248

2023-09-01 14:43 UTC, ntruchsess approved these changes

2023-09-01 14:45 UTC, merged