feat(autosetup): introduce manuell process step to trigger activation
eclipse-tractusx/portal-backend pull request #231
Opened 2023-08-23 14:10 UTC by Phil91

## Description

introduce TRIGGER_ACTIVATE_SUBSCRIPTION process step to manually trigger the offer subscription activation
enable client and service accounts when activating the offer subscription

## Why

Please include an explanation of why this change is necessary as well as relevant motivation and context. List any dependencies that are required for this change.

## Issue

N/A - Jira Issue: CPLP-3165

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2023-08-30 18:54 UTC, ntruchsess commented
please rebase on dev and recreate the migration. (if you prefer this might also be done after merging https://github.com/eclipse-tractusx/portal-backend/pull/203)

2023-08-30 18:55 UTC, ntruchsess requested changes
please rebase on dev and recreate the migration resolving the conflict. (If you prefer this may be done after merge of https://github.com/eclipse-tractusx/portal-backend/pull/203)

2023-09-01 07:52 UTC, Phil91 commented
@ntruchsess i've rebased to the latest dev, since we have to wait for a dependency check in #203 i'd say we merge this branch first

2023-09-14 20:15 UTC, ntruchsess approved these changes

2023-09-14 20:16 UTC, merged