feat(n2n): add database structure for n2n
eclipse-tractusx/portal-backend pull request #243
Opened 2023-08-28 07:52 UTC by Phil91

## Description

add new database structure for network to network
add seeding for n2n
adjust POST: api/administration/identityprovider/owncompany/identityproviders

## Why

To prepare the database for the n2n changes

## Issue

N/A - Jira Issues: CPLP-3151, CPLP-3145, CPLP-3149, CPLP-3150

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2023-09-04 21:58 UTC, ntruchsess requested changes

2023-09-04 21:58 UTC, ntruchsess commented on src/portalbackend/PortalBackend.Migrations/Migrations/20230904091939_CPLP-3165-AddN2NModels.cs
> +            migrationBuilder.Sql("DROP FUNCTION \"portal\".\"LC_TRIGGER_AFTER_INSERT_COMPANYAPPLICATION\"() CASCADE;");
fails with error '42883: function portal.LC_TRIGGER_AFTER_INSERT_COMPANYAPPLICATION() does not exist' (this is due to the schema and function-names are enclosed in "..")
not sure why this is the case as it should be generated? Provious migration 'AdjustTriggers' seems to be all fine in respect to this.

2023-09-04 21:58 UTC, ntruchsess commented on src/portalbackend/PortalBackend.Migrations/Migrations/PortalDbContextModelSnapshot.cs
> +                        .HasAnnotation("LC_TRIGGER_AFTER_INSERT_CONNECTOR", "CREATE FUNCTION \"portal\".\"LC_TRIGGER_AFTER_INSERT_CONNECTOR\"() RETURNS trigger as $LC_TRIGGER_AFTER_INSERT_CONNECTOR$\
those Annotations are unrelated to N2N so they shouldn't have changed?

2023-09-04 22:17 UTC, ntruchsess commented
regarding the issues with trigger-annotations in context-snapshot:
I have installed ef-tools latest version 7.0.10 and when I checkout dev and add a new migration this migration is not empty but contains all trigger-function being recreated.

2023-09-05 15:52 UTC, ntruchsess commented on src/portalbackend/PortalBackend.Migrations/Migrations/PortalDbContextModelSnapshot.cs
> +                        .HasAnnotation("LC_TRIGGER_AFTER_INSERT_CONNECTOR", "CREATE FUNCTION \"portal\".\"LC_TRIGGER_AFTER_INSERT_CONNECTOR\"() RETURNS trigger as $LC_TRIGGER_AFTER_INSERT_CONNECTOR$\
this is fixed in https://github.com/eclipse-tractusx/portal-backend/pull/254

2023-09-05 15:53 UTC, ntruchsess commented
> regarding the issues with trigger-annotations in context-snapshot: I have installed ef-tools latest version 7.0.10 and when I checkout dev and add a new migration this migration is not empty but contains all trigger-function being recreated.

this is fixed in https://github.com/eclipse-tractusx/portal-backend/pull/254

2023-09-06 06:51 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/PortalBackend.Migrations.csproj
> +    <Compile Remove="Migrations\20230825073236_CPLP-3165-AddN2NModels.cs" />
removed

2023-09-06 06:52 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Migrations/20230904091939_CPLP-3165-AddN2NModels.cs
> +            migrationBuilder.Sql("UPDATE portal.identity_providers AS idp SET owner_id = (SELECT cip.company_id FROM portal.company_identity_providers AS cip WHERE idp.id = cip.identity_provider_id)
removed the migration scripts and set ownerId to optional

2023-09-07 20:51 UTC, ntruchsess approved these changes

2023-09-07 20:56 UTC, merged