feat(n2n): add network registration
eclipse-tractusx/portal-backend pull request #255
Opened 2023-09-06 08:46 UTC by Phil91

## Description

add endpoint POST registration/network/partnerRegistration to register partners to the network
add new process to synchronize users with central keycloak instance for the partnerRegistration

## Why

To allow onboarding service providers to register companies to the catena network

## Issue

N/A - Jira Issue: CPLP-2637

## Depending PRs

**Backend**

Before merging PR #243 should be merged

**CD Repo**

[#85](https://github.com/eclipse-tractusx/portal-cd/pull/85)

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2023-09-14 20:49 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/NetworkBusinessLogic.cs
> +    private static readonly Regex Name = new(@"^(([A-Za-zÀ-ÿ]{1,40}?([-,.'\s]?[A-Za-zÀ-ÿ]{1,40}?)){1,8})$", RegexOptions.Compiled, TimeSpan.FromSeconds(1));
I suggest to ensure a particular type would comply to the same patterns whereever it is being used I suggest to keep those patterns in a single location. Some month we startet here: https://github.com/eclipse-tractusx/portal-backend/blob/main/src/framework/Framework.Models/ValidationExpressions.cs
(I guess we need to rediscuss the patterns as in above location the exact same patterns are commented out - afaik for performance-reasons).

2023-09-14 21:11 UTC, ntruchsess requested changes
see my comments from initial review (remark: I did already rebase on dev recreating the migration)

2023-09-15 11:04 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/NetworkBusinessLogic.cs
> +        foreach (var user in data.UserDetails)
adjusted

2023-09-15 11:04 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/NetworkBusinessLogic.cs
> +    private static readonly Regex Name = new(@"^(([A-Za-zÀ-ÿ]{1,40}?([-,.'\s]?[A-Za-zÀ-ÿ]{1,40}?)){1,8})$", RegexOptions.Compiled, TimeSpan.FromSeconds(1));
i have moved the bpn expression to the ValidationExpressions and adjusted the ones for Name and Email

2023-09-19 20:09 UTC, ntruchsess requested changes

2023-09-19 20:09 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/NetworkBusinessLogic.cs
> +        var idps = await companyRepository.GetLinkedIdpIds(_identityService.IdentityData.CompanyId)
changed

2023-09-19 20:09 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/NetworkBusinessLogic.cs
> +        if (idps.All(x => !identityProviderIds.Where(y => y != null).Contains(x)))
fixed

2023-09-19 20:10 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/NetworkBusinessLogic.cs
> +            throw new UnexpectedConditionException($"Errors occured while saving the users: ${string.Join("", errors.Select(x => x.Message))}", errors.First());
fixed

2023-09-19 20:10 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/NetworkBusinessLogic.cs
> +        if (errors.Any())
fixed

2023-09-19 20:10 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/NetworkBusinessLogic.cs
> +        var idps = await identityProviderRepository.GetCompanyIdentityProviderCategoryDataUntracked(ownerCompanyId).ToListAsync().ConfigureAwait(false);
rewritten

2023-09-19 20:10 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/NetworkBusinessLogic.cs
> +        var company = companyRepository.CreateCompany(data.Name, c =>
fixed

2023-09-19 20:11 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/IdentityProviderRepository.cs
> +                IEnumerable<(Guid Id, string Alias)> IdpAliase)>
fixed

2023-09-19 20:15 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs
> +                .Select(i => i.CompanyUser!)
fixed

2023-09-19 20:43 UTC, ntruchsess requested changes

2023-09-19 20:43 UTC, ntruchsess commented on src/processes/NetworkRegistration.Library/NetworkRegistrationHandler.cs
> +                         await _userProvisioningService.CreateCentralUserWithProviderLinks(cu.CompanyUserId, new UserCreationRoleDataIdpInfo(cu.FirstName, cu.LastName, cu.Email, roleData, string.Empt
firstName, lastName, email and alias may be null here. Either this code must explicitly check and throw e.g. ConflictException or datatypes shall be adjusted accordingly. (We might discuss the options first).

2023-09-19 20:46 UTC, ntruchsess commented
@Phil91 : I did fix most of my findings (see https://github.com/eclipse-tractusx/portal-backend/pull/255/commits/49fb260533342e5355f590b3534775e983a71ee6 ), please double-check (especially the changes relating to functional findings like querying by ownerId vs. companyIdentityProvider-link).
Some findings are left to be either fixed or discussed/postponed to later ticket.

2023-09-19 21:13 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/NetworkBusinessLogic.cs
> +        if (await networkRepository.CheckExternalIdExists(data.ExternalId)
added the constraint. think thats a good idea.

2023-09-19 21:13 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/NetworkBusinessLogic.cs
> +        if (string.IsNullOrWhiteSpace(data.Bpn) || !BpnRegex.IsMatch(data.Bpn))
check added

2023-09-19 21:14 UTC, Phil91 commented on src/processes/NetworkRegistration.Library/NetworkRegistrationHandler.cs
> +                         await _userProvisioningService.CreateCentralUserWithProviderLinks(cu.CompanyUserId, new UserCreationRoleDataIdpInfo(cu.FirstName, cu.LastName, cu.Email, roleData, string.Empt
It makes sense to check the data, since they are stored in the database and before they are stored checked to be not null, without one manipulating the data they should therefor never be null.

2023-09-20 06:34 UTC, ntruchsess requested changes

2023-09-20 06:34 UTC, ntruchsess commented on src/processes/NetworkRegistration.Library/NetworkRegistrationHandler.cs
> +                         await _userProvisioningService.CreateCentralUserWithProviderLinks(cu.CompanyUserId, new UserCreationRoleDataIdpInfo(cu.FirstName!, cu.LastName!, cu.Email!, roleData, string.E
Alias can be null here

2023-09-20 07:05 UTC, ntruchsess commented
@Phil91 : we need a bit more coverage - specially the new process-related code has little or no coverage. See: https://github.com/catenax-ng/tx-portal-backend/pull/418

2023-09-20 12:52 UTC, Phil91 commented on src/processes/NetworkRegistration.Library/NetworkRegistrationHandler.cs
> +                         await _userProvisioningService.CreateCentralUserWithProviderLinks(cu.CompanyUserId, new UserCreationRoleDataIdpInfo(cu.FirstName!, cu.LastName!, cu.Email!, roleData, string.E
check for alias added

2023-09-20 12:52 UTC, Phil91 commented
> @Phil91 : we need a bit more coverage - specially the new process-related code has little or no coverage. See: https://sonarcloud.io/component_measures?id=catenax-ng_tx-portal-backend&pullRequest=418&metric=new_coverage&view=list

@ntruchsess tests have been added

2023-09-20 17:45 UTC, ntruchsess approved these changes

2023-09-21 06:58 UTC, merged