feat(n2n): add submit endpoint
eclipse-tractusx/portal-backend pull request #260
Opened 2023-09-11 11:51 UTC by Phil91

## Description

add POST: api/administration/registration/network/partnerRegistration/submit endpoint

## Why

To enable the company admin of the service provider to submit the application

## Issue

N/A - Jira Issue: CPLP-2638

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2023-09-19 08:22 UTC, Phil91 commented
> #### ⚠️ GitGuardian has uncovered 5 secrets following the scan of your pull request.
> Please consider investigating the findings and remediating the incidents. Failure to do so may lead to compromising the associated services or software components.
> 
> 🔎 Detected hardcoded secrets in your pull request
> 🛠 Guidelines to remediate hardcoded secrets
> 🦉 [GitGuardian](https://dashboard.gitguardian.com/auth/login/?utm_medium=checkruns&utm_source=github&utm_campaign=cr1) detects secrets in your source code to help developers and security teams secure the modern development process. You are seeing this because you or someone else with access to this repository has authorized GitGuardian to scan your pull request.Our GitHub checks need improvements? [Share your feedbacks](https://050127dayho.typeform.com/to/KmeAPTMk)!

The issue has already been comented. The secret is only used in the unitTests and needed in there because of the encryption which would throw an error if the format isn't matching

2023-09-21 14:24 UTC, ntruchsess requested changes

2023-09-21 14:24 UTC, ntruchsess commented on src/administration/Administration.Service/Administration.Service.csproj
> +  <ItemGroup>
fixed

2023-09-21 14:25 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/NetworkBusinessLogic.cs
> +        var missingRoles = data.CompanyRoleIds
fixed

2023-09-21 14:25 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/NetworkBusinessLogic.cs
> +        var allAgreementsActive = data.CompanyRoleIds.SelectMany(x => x.AgreementIds)
fixed

2023-09-21 14:25 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/NetworkRepository.cs
> +            .Where(x => x.Id == companyId)
fixed

2023-09-21 14:36 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/NetworkRepository.cs
> +                    new List<string?>()))
I had this first, but it fails while executing it.

2023-09-21 14:52 UTC, Phil91 commented on src/administration/Administration.Service/Models/CompanyRoleConsentDetails.cs
> +    [property: JsonPropertyName("companyRole")] CompanyRoleId CompanyRole,
has been reverted

2023-09-21 14:55 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/NetworkRepository.cs
> +                    x.Process!.ProcessSteps.Where(p => p.ProcessStepTypeId == ProcessStepTypeId.VERIFY_REGISTRATION && p.ProcessStepStatusId == ProcessStepStatusId.FAILED).Select(step => step.Message
absolutley right, i did filter the 'null' messages

2023-09-21 14:59 UTC, ntruchsess requested changes

2023-09-21 14:59 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/RegistrationStatusBusinessLogic.cs
> +        var secretResult = encryptor.TransformFinalBlock(toEncryptedArray, 0, toEncryptedArray.Length);
I think that call only works reliable when InputBlockSize is taken into account (this is not explicitly documented but one should validate that TransformFinalBlock does support the transformation of a block that is larger than InputBlockSize). From my understanding the incomming bytes should be split into chunks of InputBlockSize and transformed separately while TransformFinalBlock then would transform anything that is left over (being smaller than InputBlockSize).

2023-09-21 14:59 UTC, ntruchsess commented on src/portalbackend/PortalBackend.PortalEntities/Entities/OnboardingServiceProviderDetail.cs
> +    public string ClientSecret { get; set; }
this should be byte[] rendering the conversion to base64 obsolete
(this is supported by postgres, see Document-entity)

2023-09-21 14:59 UTC, ntruchsess commented on src/externalsystems/OnboardingServiceProvider.Library/OnboardingServiceProviderBusinessLogic.cs
> +        var resultArray = decryptor.TransformFinalBlock(toEncryptArray, 0, toEncryptArray.Length);
same as with the encryption part - I expect this should be done blockwise

2023-09-21 14:59 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRepository.cs
> +                        c.OnboardingServiceProviderDetail!.ClientId,
! is not required to be specified more than once for the same nullable

2023-09-21 14:59 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/NetworkRepository.cs
> +                        x.OnboardingServiceProvider!.OnboardingServiceProviderDetail.AuthUrl,
redundant '!'

2023-09-21 16:25 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/RegistrationStatusBusinessLogic.cs
> +        var secretResult = encryptor.TransformFinalBlock(toEncryptedArray, 0, toEncryptedArray.Length);
changed it to the usage of a memory and cryptoStream

2023-09-21 16:25 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/NetworkRepository.cs
> +                    x.Process!.ProcessSteps.Where(p => p.ProcessStepTypeId == ProcessStepTypeId.VERIFY_REGISTRATION && p.ProcessStepStatusId == ProcessStepStatusId.FAILED).Select(step => step.Message
adjusted

2023-09-21 16:25 UTC, Phil91 commented on src/portalbackend/PortalBackend.PortalEntities/Entities/OnboardingServiceProviderDetail.cs
> +    public string ClientSecret { get; set; }
changed

2023-09-21 16:25 UTC, Phil91 commented on src/externalsystems/OnboardingServiceProvider.Library/OnboardingServiceProviderBusinessLogic.cs
> +        var resultArray = decryptor.TransformFinalBlock(toEncryptArray, 0, toEncryptArray.Length);
changed it to the usage of a memory and cryptoStream

2023-09-21 16:26 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRepository.cs
> +                        c.OnboardingServiceProviderDetail!.ClientId,
removed

2023-09-21 16:26 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/NetworkRepository.cs
> +                        x.OnboardingServiceProvider!.OnboardingServiceProviderDetail.AuthUrl,
removed

2023-09-21 17:40 UTC, ntruchsess approved these changes

2023-09-22 07:26 UTC, merged