feat(apps): added endpoint to fetch app active documents
eclipse-tractusx/portal-backend pull request #266
Opened 2023-09-13 10:21 UTC by VPrasannaK94

## Description

added endpoint to fetch app active documents

## Why

Added endpoint to fetch Active app documents

## Issue

[CPLP-3087](https://jira.catena-x.net/browse/CPLP-3087)

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2023-09-21 08:58 UTC, ntruchsess requested changes

2023-09-21 08:58 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
> +        .SingleOrDefaultAsync();
returning Task<IEnumerable<...>?> from a query is an antipattern. You just don't do this, a query should allways return IAsyncEnumerable<...> instead.
I suggest:
```
_context.OfferAssignedDocuments
    .Where(x => x.OfferId == offerId &&
        x.Offer!.OfferStatusId == OfferStatusId.ACTIVE &&
        x.Offer.OfferTypeId == offerTypeId &&
        x.Offer.ProviderCompanyId == userCompanyId &&
        documentTypeIds.Contains(x.Document!.DocumentTypeId))
    .Select(x => new DocumentTypeData(
        x.Document!.DocumentTypeId,
        x.Document.Id,
        x.Document.DocumentName))
    .OrderBy(x => x.DocumentTypeId)
    .ToAsyncEnumerable();
```
(the OrderBy to be executed on the database is there so the businessCode may use AsyncGroupByExtensions.PreSortedGroupBy (namespace Org.Eclipse.TractusX.Portal.Backend.Framework.Async) to do the grouping afterwards.

2023-09-21 08:58 UTC, ntruchsess commented on src/marketplace/Apps.Service/BusinessLogic/AppChangeBusinessLogic.cs
> +        foreach (var doctype in _settings.ActiveAppDocumentTypeIds)
the whole thing can be done efficiently using pure LINQ:
```
var appDocTypeData = await _portalRepositories.GetInstance<IOfferRepository>()
    .GetActiveOfferDocumentTypeDataAsync(appId, companyId, OfferTypeId.APP, _settings.ActiveAppDocumentTypeIds)
    .PreSortedGroupBy(result => result.DocumentTypeId)
    .ToDictionaryAsync(
        group => group.Key,
        group => group.Select(result =>
            new DocumentData(
                result.DocumentId,
                result.DocumentName)))
    .ConfigureAwait(false);
return new ActiveAppDocumentData(
    _settings.ActiveAppDocumentTypeIds.ToDictionary(
        documentTypeId => documentTypeId,
        documentTypeId => appDocTypeData.TryGetValue(documentTypeId, out var data)
            ? data
            : Enumerable.Empty<DocumentData>()));
```
(suggestion is based on the query returning IAsyncEnumerable as suggested in the comment in OfferRepository.cs)

2023-09-21 08:58 UTC, ntruchsess commented on src/marketplace/Apps.Service/ViewModels/AppData.cs
> +public record ActiveAppDocumentData(IDictionary<DocumentTypeId, IEnumerable<DocumentData?>> Documents);
DocumentData being nullable within the IEnumerable makes no sense. In the endpoints response you don't want to see 'null' as a member of the json-array that is mapped to the documentTypeId. The code that is creating those objects needs to be adjusted accordingly so it doesn't put null into this Enumerable.

2023-09-21 09:37 UTC, ntruchsess requested changes

2023-09-21 09:37 UTC, ntruchsess commented on src/marketplace/Apps.Service/Controllers/AppChangeController.cs
> +        await this.WithCompanyId(companyId => _businessLogic.GetActiveAppDocumentTypeDataAsync(appId, companyId)).ConfigureAwait(false);
please use the new IIdentityService in the businessLogic to retrieve the companyId of the calling user.

2023-09-22 05:09 UTC, VPrasannaK94 commented on src/marketplace/Apps.Service/BusinessLogic/AppChangeBusinessLogic.cs
> +        foreach (var doctype in _settings.ActiveAppDocumentTypeIds)
@ntruchsess , In Ticket, it mentioned If for any of the types no document should be available, the document type should be still available in the response body, but the array should be empty.
So, we need to have all configured activeAppDocumentTypeIds in responce body.

@jjeroch, Can you please clarify it from your end also.

2023-09-22 11:09 UTC, ntruchsess requested changes

2023-09-22 11:09 UTC, ntruchsess commented on tests/portalbackend/PortalBackend.DBAccess.Tests/OfferRepositoryTests.cs
> +        result.Should().NotBeNull().And.HaveCount(1).And.Satisfy(
please add more documents to test-seeding, covering at lease 3 documentTypeIds and assert the query does return the results ordered by documentTypeid (this is a prerequisite for the call to PreSortedGroupBy in the businesslogic)

2023-09-22 12:42 UTC, ntruchsess commented on src/marketplace/Apps.Service/BusinessLogic/AppChangeBusinessLogic.cs
> +        foreach (var doctype in _settings.ActiveAppDocumentTypeIds)
just clarified with @jjeroch : documentTypeIds that do not have documents shall be included as empty arrayes in the response. No adjusments of the current implementation required

2023-09-22 14:29 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
> +        .SingleOrDefaultAsync();
I see this query would not translate to sql due to the position of the OrderBy.
I've changed that. Executing the OrderBy on the level of the original entity works fine. See: https://github.com/catenax-ng/tx-portal-backend/commit/59a3fb9d6cb25aa51c8519a086fa735ba63e26eb

2023-10-09 08:20 UTC, ntruchsess commented on tests/portalbackend/PortalBackend.DBAccess.Tests/OfferRepositoryTests.cs
> +        result.Should().NotBeNull().And.HaveCount(1).And.Satisfy(
did add more test-data to cover the 'BeInAscentingOrder(x => x.DocumentTypeId)' assert

2023-10-09 08:27 UTC, ntruchsess approved these changes

2023-10-09 08:28 UTC, merged