fix(constraints): change function constraints to trigger function
eclipse-tractusx/portal-backend pull request #300
Opened 2023-10-12 10:10 UTC by Phil91

## Description

The check constraints is_external_type_use_case, is_credential_type_use_case & is_connector_managed are changed from function constraint to trigger function constraint

## Why

To be able to import data with pg_dumpall without running into exceptions because of the constraints

## Issue

N/A - Jira Issue: CPLP-3341

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2023-10-13 08:14 UTC, ntruchsess requested changes

2023-10-13 08:14 UTC, ntruchsess commented on src/portalbackend/PortalBackend.Migrations/Migrations/20231012090215_CPLP-3341-ChangeFunctionConstraints.cs
> +            migrationBuilder.Sql("DROP FUNCTION portal.is_connector_managed;");
please add 'IF EXISTS' as it is possible that this SQL has been executed manually to do a database-upgrade before this migration is being applied.
all to-be-added functions and triggers need to be dropped-if-exists before being (re-)added in the up() for the same reason.

2023-10-13 08:30 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Migrations/20231012090215_CPLP-3341-ChangeFunctionConstraints.cs
> +            migrationBuilder.Sql("DROP FUNCTION portal.is_connector_managed;");
adjusted

2023-10-16 14:48 UTC, ntruchsess approved these changes

2023-10-16 14:48 UTC, merged

2023-10-18 13:57 UTC, Phil91 commented
This script needs to be executed before a database update can happen:

ALTER TABLE portal.connector_assigned_offer_subscriptions DROP CONSTRAINT IF EXISTS CK_Connector_ConnectorType_IsManaged;
DROP FUNCTION IF EXISTS portal.is_connector_managed;

ALTER TABLE portal.verified_credential_type_assigned_use_cases DROP CONSTRAINT IF EXISTS CK_VCTypeAssignedUseCase_VerifiedCredentialType_UseCase;
DROP FUNCTION IF EXISTS portal.is_credential_type_use_case;

ALTER TABLE portal.company_ssi_details DROP CONSTRAINT IF EXISTS CK_VC_ExternalType_DetailId_UseCase;
DROP FUNCTION IF EXISTS portal.is_external_type_use_case;

DROP TRIGGER IF EXISTS ct_is_connector_managed ON portal.connector_assigned_offer_subscriptions;
DROP FUNCTION IF EXISTS portal.tr_is_connector_managed;

DROP TRIGGER IF EXISTS ct_is_credential_type_use_case ON portal.verified_credential_type_assigned_use_cases;
DROP FUNCTION IF EXISTS portal.tr_is_credential_type_use_case;

DROP TRIGGER IF EXISTS ct_is_external_type_use_case ON portal.company_ssi_details;
DROP FUNCTION IF EXISTS portal.tr_is_external_type_use_case;

CREATE FUNCTION portal.tr_is_connector_managed()
    RETURNS trigger
    VOLATILE
    COST 100
    AS $$
    BEGIN
    IF EXISTS(
        SELECT 1
            FROM portal.connectors
            WHERE Id = NEW.connector_id
            AND type_id = 2
    )
    THEN RETURN NEW;
    END IF;
    RAISE EXCEPTION 'the connector % is not managed', NEW.connector_id;
    END
    $$ LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER ct_is_connector_managed
    AFTER INSERT
    ON portal.connector_assigned_offer_subscriptions
    INITIALLY DEFERRED
    FOR EACH ROW
    EXECUTE PROCEDURE portal.tr_is_connector_managed();

CREATE FUNCTION portal.tr_is_credential_type_use_case()
    RETURNS trigger
    VOLATILE
    COST 100
    AS $$
    BEGIN
    IF EXISTS (
        SELECT 1
            FROM portal.verified_credential_types
            WHERE Id = NEW.verified_credential_type_id
                AND NEW.verified_credential_type_id IN (
                    SELECT verified_credential_type_id
                    FROM portal.verified_credential_type_assigned_kinds
                    WHERE verified_credential_type_kind_id = '1'
                )
    )
    THEN RETURN NEW;
    END IF;
    RAISE EXCEPTION 'The credential % is not a use case', NEW.verified_credential_type_id;
    END
    $$ LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER ct_is_credential_type_use_case
    AFTER INSERT
    ON portal.verified_credential_type_assigned_use_cases
    INITIALLY DEFERRED
    FOR EACH ROW
    EXECUTE PROCEDURE portal.tr_is_credential_type_use_case();

CREATE FUNCTION portal.tr_is_external_type_use_case()
    RETURNS trigger
    VOLATILE
    COST 100
    AS $$
    BEGIN
    IF NEW.verified_credential_external_type_use_case_detail_id IS NULL
        THEN RETURN NEW;
    END IF;
    IF EXISTS (
        SELECT 1
                FROM portal.verified_credential_external_type_use_case_detail_versions
                WHERE Id = NEW.verified_credential_external_type_use_case_detail_id
                    AND verified_credential_external_type_id IN (
                    SELECT verified_credential_external_type_id
                    FROM portal.verified_credential_type_assigned_external_types
                    WHERE verified_credential_type_id IN (
                        SELECT verified_credential_type_id
                        FROM portal.verified_credential_type_assigned_kinds
                        WHERE verified_credential_type_kind_id = '1'
                    )
                )
    )
    THEN RETURN NEW;
    END IF;
    RAISE EXCEPTION 'the detail % is not an use case', NEW.verified_credential_external_type_use_case_detail_id;
    END
    $$ LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER ct_is_external_type_use_case
    AFTER INSERT
    ON portal.company_ssi_details
    INITIALLY DEFERRED
    FOR EACH ROW
    EXECUTE PROCEDURE portal.tr_is_external_type_use_case();