add new exceptions for errortype, errorcode and parameters
eclipse-tractusx/portal-backend pull request #315
Opened 2023-10-26 16:26 UTC by ntruchsess

## Description

Please include a summary of the change.

## Why

Please include an explanation of why this change is necessary as well as relevant motivation and context. List any dependencies that are required for this change.

## Issue

Link to Github issue.

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [ ] I have created and linked IP issues or requested their creation by a committer
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

2023-10-27 07:20 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +            throw NotFoundException.Create(AdministrationRegistrationErrors.APPLICATION_NOT_FOUND, new ErrorParameter[] { new("applicationId", applicationId.ToString()) });
I'd suggest changing the ToString to nameof. Should result in the same

```suggestion
            throw NotFoundException.Create(AdministrationRegistrationErrors.APPLICATION_NOT_FOUND, new ErrorParameter[] { new("applicationId", nameof(applicationId)) });
```

2023-10-27 07:35 UTC, Phil91 commented on src/framework/Framework.ErrorHandling.Web/GeneralHttpErrorHandler.cs
> +    public GeneralHttpErrorHandler(RequestDelegate next, ILogger<GeneralHttpErrorHandler> logger, IErrorMessageService? errorMessageService = null)
I guess the errorMessageService is currently nullable so we don't have to adjust all the code at once and will be changed in the future to a not nullable?

If that's the case let's maybe add an todo here

2023-10-27 07:36 UTC, Phil91 requested changes
One minor question open.
Besides of that looking really good.

Could you please comment the sonar findings - in my opinion that are false positives

2023-10-27 08:12 UTC, ntruchsess commented on src/framework/Framework.ErrorHandling.Web/GeneralHttpErrorHandler.cs
> +    public GeneralHttpErrorHandler(RequestDelegate next, ILogger<GeneralHttpErrorHandler> logger, IErrorMessageService? errorMessageService = null)
yes, that is the reason. I did add a TODO as reminder

2023-10-31 07:08 UTC, Phil91 approved these changes

2023-10-31 10:17 UTC, merged