feat(nuget): create nuget packages for framework
eclipse-tractusx/portal-backend pull request #325
Opened 2023-11-03 09:11 UTC by Phil91

## Description

All framework projects are now available as nuget packages

## Why

To be able to use the backend framework code in the policy hub

## Issue

N/A - Jira Issue CPLP-3400

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-01-23 13:23 UTC, Phil91 commented
@ntruchsess , @evegufy  please be aware that the `Pre Checks` Action currently is failing due to the package versions. i've currently used a .beta version for the packages to be able to publish them to nuget. befor merging i will create a mayor version of all of them (1.0.0)

2024-01-24 16:31 UTC, evegufy commented on src/framework/Framework.Async/README.md
> +# Catena-X Portal Backend Framework Async
- Comment valid for all readme files under the framework directory -
IMO we should reduce the files to the most relevant information:
- remove the following sections: copyright, third-party content and cryptography
- move the source code section above the license section
- remove 'See [LICENSE](./LICENSE) for more information.' from the license section as the relative link isn't working on nuget https://www.nuget.org/packages/Org.Eclipse.TractusX.Portal.Backend.Framework.Seeding/1.0.0-beta.9

2024-01-24 16:34 UTC, evegufy commented on scripts/update-nuget-packages.md
> +# Update nuget packages
I think we should introduce a docs/nuget directory and move this file there.

2024-01-24 16:34 UTC, evegufy commented on scripts/update-nuget-packages.md
> +Currently each project of the framework directory is build and provided as an nuget package.
I'd remove the 'Currently'.

2024-01-24 16:35 UTC, evegufy commented on scripts/update-nuget-packages.md
> +NUGET_API_KEY is the key generated on nuget.org. The last command should only be executed within the github action
could you please provide a relative link to the relevant GH workflow?

2024-01-24 16:42 UTC, evegufy commented on .github/workflows/nuget-package-push.yml
> +name: Push Nuget Packages and Tag
It's not intended to replace the unit-tests-formatting workflow by the nuget workflow, right?

2024-01-24 16:43 UTC, evegufy commented on .github/workflows/nuget-package-push.yml
> +        - 'dev'
makes probably also sense to add the rc release branches 'release/v*.*.*-RC*'

2024-01-24 16:45 UTC, evegufy requested changes
Looks good!
Just some comments.

Please also provide an information about the nuget packges in the readme on root level, similar to the information for docker images, please link there also the documentation in docs/nuget,

2024-01-25 09:43 UTC, Phil91 commented on .github/workflows/nuget-package-push.yml
> +name: Push Nuget Packages and Tag
not sure why github shows it this way, i've renamed the existing workflow to pre-checks.yml somehow github shows it as a completly new file...

2024-01-25 09:43 UTC, Phil91 commented on .github/workflows/nuget-package-push.yml
> +        - 'dev'
added

2024-01-25 09:43 UTC, Phil91 commented on scripts/update-nuget-packages.md
> +NUGET_API_KEY is the key generated on nuget.org. The last command should only be executed within the github action
added

2024-01-25 09:43 UTC, Phil91 commented on scripts/update-nuget-packages.md
> +Currently each project of the framework directory is build and provided as an nuget package.
removed

2024-01-25 09:43 UTC, Phil91 commented on scripts/update-nuget-packages.md
> +# Update nuget packages
good idea. done

2024-01-25 09:43 UTC, Phil91 commented on src/framework/Framework.Async/README.md
> +# Catena-X Portal Backend Framework Async
adjusted

2024-01-25 11:52 UTC, evegufy commented on src/framework/Framework.Async/README.md
> +# Catena-X Portal Backend Framework Async
I forget to mention contributing in the list of sections to be removed, there is also a link which isn't working on nuget.

2024-01-25 11:57 UTC, evegufy commented
> Looks good! Just some comments.
> 
> Please also provide an information about the nuget packges in the readme on root level, similar to the information for docker images, please link there also the documentation in docs/nuget.

Thanks for the changes! I still don't see changes to the readme on root level.

2024-01-25 13:25 UTC, Phil91 commented on src/framework/Framework.Async/README.md
> +# Catena-X Portal Backend Framework Async
missed that, sorry. removed.

2024-01-26 07:05 UTC, evegufy commented on README.md
>  ### Base images
The notice for nuget is now in the middle of the notice for docker, the '### Base images' should be after '### DockerHub'.

2024-01-26 07:11 UTC, evegufy commented on README.md
> +* https://www.nuget.org/packages/Org.Eclipse.TractusX.Portal.Backend.Framework.Async/
the links look a bit 'much' could you do something like [nuget.org/packages/Org.Eclipse.TractusX.Portal.Backend.Framework.Async](https://www.nuget.org/packages/Org.Eclipse.TractusX.Portal.Backend.Framework.Async)?
Maybe for docker then as well.

2024-01-26 07:12 UTC, evegufy requested changes

2024-01-26 07:12 UTC, evegufy commented on docs/nuget/update-nuget-packages.md
> +Each project of the framework directory is build and provided as an nuget package.
Maybe also here a relative link to framework would be helpful.

2024-01-26 07:12 UTC, Phil91 commented on README.md
> +* https://www.nuget.org/packages/Org.Eclipse.TractusX.Portal.Backend.Framework.Async/
what about just writing the package name?

2024-01-26 07:32 UTC, Phil91 commented on README.md
>  ### Base images
moved to the correct place

2024-01-26 07:32 UTC, Phil91 commented on README.md
> +* https://www.nuget.org/packages/Org.Eclipse.TractusX.Portal.Backend.Framework.Async/
adjusted

2024-01-26 07:32 UTC, Phil91 commented on docs/nuget/update-nuget-packages.md
> +Each project of the framework directory is build and provided as an nuget package.
added the link :)

2024-02-01 21:26 UTC, ntruchsess requested changes

2024-02-02 08:04 UTC, Phil91 commented on src/framework/Framework.Web/Directory.Build.props
> +- Copyright (c) 2021, 2023 Microsoft and BMW Group AG
@ntruchsess  Only gonna' comment on this file, no idea how the copyright header got there since they were new files. I've adjusted all of the framework - directory.build.props

2024-02-02 14:10 UTC, ntruchsess approved these changes

2024-02-06 15:19 UTC, ntruchsess approved these changes

2024-02-06 15:41 UTC, merged