feat(registration): adjust validation
eclipse-tractusx/portal-backend pull request #329
Opened 2023-11-06 16:48 UTC by Phil91

## Description

adjust validation of the external registration
align validation for external registration and companyDetailsWithAddress

## Why

to have one validation for general validation data in place.

## Issue

N/A - Jira Issue: CPLP-3465

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2023-11-10 15:10 UTC, ntruchsess requested changes

2023-11-13 10:18 UTC, Phil91 commented on src/framework/Framework.Validation/RegistrationData.cs
> +public record RegistrationData(
moved to Registration.Common

2023-11-13 10:56 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Migrations/20231109082256_CPLP-3465-ChangeExternalId.cs
> +            migrationBuilder.AlterColumn<Guid>(
as discussed we will add documentation to describe that a rollback isn't possible if externalIds were added that are no uuids

2023-11-13 20:48 UTC, ntruchsess approved these changes

2023-11-13 20:50 UTC, merged