fix(userrole): fix user role assignment
eclipse-tractusx/portal-backend pull request #334
Opened 2023-11-09 07:56 UTC by Phil91

## Description

Adjusting the handling of user role assignments with multiple client ids.

## Why

Currently assigning roles to an offer with multiple client ids fails

## Issue

Refs: N/A - Jira Issue: TEST-1537

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2023-11-10 12:36 UTC, ntruchsess requested changes

2023-11-10 12:36 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/UserRolesBusinessLogic.cs
> +        var rolesAdded = rolesToAdd.IntersectBy(assignedRoles.SelectMany(x => x.Roles).Distinct(), role => role.CompanyUserRoleText).ToList();
rolesAdded will only contain the roles that have been assigned to **at least one** of the clients. In case a Role succeeds for one client but fails for a different one this will remain undetected.

To determine the roles that have been successfully assigned to **all** the clients I suggest:
```
var assignedRoles = _provisioningManager.AssignClientRolesToCentralUserAsync(iamUserId, clientRoleNames);

var rolesAdded = (await assignedRoles // determine the roles that have been assigned to all of the clients.
    .AggregateAsync(
        rolesToAdd,
        (IEnumerable<UserRoleModificationData> toAdd, (string ClientId, IEnumerable<string> Roles) assigned) =>
            toAdd.IntersectBy(assigned.Roles, role => role.CompanyUserRoleText)).ConfigureAwait(false))
    .ToList();
```

the expected behavious (fail early vs. ignore partial failure) should be clarified with @jjeroch

2023-11-13 10:55 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/UserRolesBusinessLogic.cs
> +        var rolesAdded = rolesToAdd.IntersectBy(assignedRoles.SelectMany(x => x.Roles).Distinct(), role => role.CompanyUserRoleText).ToList();
as discussed with @jjeroch we're using the fail early method.
code is adjusted accordingly

2023-11-13 20:41 UTC, ntruchsess approved these changes

2023-11-13 20:48 UTC, merged