feat(app & service) : add processStepTypeId field to provider/subscription endpoints
eclipse-tractusx/portal-backend pull request #341
Opened 2023-11-15 08:00 UTC by VPrasannaK94

## Description

add processStepTypeId field to provider/subscription endpoints

## Why

to know the current process step status of the offer subscription we added the processStepTypeId field for the existing endpoints

## Issue

N/A  Ref : CPLP-3251

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2023-11-16 16:52 UTC, ntruchsess requested changes

2023-11-16 16:52 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
> +                                s.Process!.ProcessSteps.Any() ?
I added a comment to https://jira.catena-x.net/browse/CPLP-3251 that points out the order of execution is undefined (random) if there are multiple process-steps in status TODO eligible to run at the same time0. That means if there are multiple process-step-types in status TODO and there should be a priority to choose one of those it needs to be explicitly given. As this is not nessesarely the order of definition in the enum I suggest to return all process-steps in status todo and pick the one that has the highest priority in the business-logic. That will both simplify the query, better maintainable (and also more flexible in case the priorities might change at a later point in time).

2023-11-16 18:01 UTC, ntruchsess requested changes
for the ProcessSteps I suggest a subquery like:
```
s.Process!.ProcessSteps.Any(ps => ps.ProcessStepStatusId == ProcessStepStatusId.TODO)
    ? s.Process!.ProcessSteps
        .Where(ps => ps.ProcessStepStatusId == ProcessStepStatusId.TODO)
        .DistinctBy(ps => ps.ProcessStepTypeId)
        .Select(ps => new ValueTuple<ProcessStepTypeId, ProcessStepStatusId>(
            ps.ProcessStepTypeId,
            ps.ProcessStepStatusId))
    : s.Process.ProcessSteps
        .Where(ps =>
            ps.ProcessStepStatusId == ProcessStepStatusId.DONE ||
            ps.ProcessStepStatusId == ProcessStepStatusId.FAILED)
        .GroupBy(ps => ps.ProcessStepTypeId)
        .Select(g => new ValueTuple<ProcessStepTypeId, ProcessStepStatusId>(
            g.Key,
            g.OrderByDescending(ps => ps.DateLastChanged).Select(ps => ps.ProcessStepStatusId).First())))),
```
or (this one assumes a process-step that is DONE cannot fail any more as it will not be executed another time)
```
s.Process!.ProcessSteps
    .Where(ps =>
        ps.ProcessStepStatusId == ProcessStepStatusId.TODO ||
        ps.ProcessStepStatusId == ProcessStepStatusId.DONE ||
        ps.ProcessStepStatusId == ProcessStepStatusId.FAILED)
    .GroupBy(ps => ps.ProcessStepTypeId)
    .Select(g => new ValueTuple<ProcessStepTypeId, ProcessStepStatusId>(
        g.Key,
        g.Any(ps => ps.ProcessStepStatusId == ProcessStepStatusId.TODO)
            ? ProcessStepStatusId.TODO
            : g.Any(ps => ps.ProcessStepStatusId == ProcessStepStatusId.DONE)
                ? ProcessStepStatusId.DONE
                : ProcessStepStatusId.FAILED))),
```
(the datatypes need to be adjusted accordingly and the businesslogic would need to determine the prioriy of process-step-types)

2023-11-16 22:24 UTC, jjeroch commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
> +                                            .OrderByDescending(ps => ps.ProcessStepTypeId)
Yes agree :)

2023-11-17 13:36 UTC, ntruchsess commented
```mermaid
flowchart TD
    X[START]
    A[100 TRIGGER_PROVIDER]
    A1{Single- or Multi-instance}
    B[101 START_AUTOSETUP]
    C[102 OFFERSUBSCRIPTION_CLIENT_CREATION]
    C1{Technical User Required}
    D[103 SINGLE_INSTANCE_SUBSCRIPTION_DETAILS_CREATION]
    E[104 OFFERSUBSCRIPTION_TECHNICALUSER_CREATION]
    F[105 ACTIVATE_SUBSCRIPTION]
    F1{Single- or Multi-instance}
    G[106 TRIGGER_PROVIDER_CALLBACK]
    H[107 RETRIGGER_PROVIDER]
    I[108 RETRIGGER_OFFERSUBSCRIPTION_CLIENT_CREATION]
    J[109 RETRIGGER_OFFERSUBSCRIPTION_TECHNICALUSER_CREATION]
    K[110 RETRIGGER_PROVIDER_CALLBACK]
    L[111 TRIGGER_ACTIVATE_SUBSCRIPTION]
    Z[DONE]
    X --> A
    A -->|recoverable Error| A
    A -->|unrecoverable Error| H
    A --> A1
    A1 -->|Single-Instance| D
    A1 -->|Multi-Instance| B
    B -->|is App| C
    B -->|is Service| E
    C -->|recoverable Error| C
    C -->|unrecoverable Error| I
    C --> C1
    C1 -->|technical User required| E
    C1 -->|technical User not required| L
    D --> F
    E -->|recoverable Error| E
    E -->|unrecoverable Error| J
    E --> L
    F --> F1
    F1 -->|Multi-Instance| G
    F1 -->|Single-Instance| Z
    G -->|recoverable Error| G
    G -->|unrecoverable Error| K
    G --> Z
    H --> A
    I --> C
    J --> E
    K --> G
    L --> F
```mermaid

2023-11-21 09:20 UTC, evegufy approved these changes

2023-11-21 09:44 UTC, merged