feat(countrieslongnames): CountriesLongNames table schema added
eclipse-tractusx/portal-backend pull request #343
Opened 2023-11-15 10:24 UTC by AnuragNagpure

## Backend Table restructure needed including a seeding data file update

Please include a summary of the change.

## make the existing table "countries" multi language capable

Currently the table supports only country names in german and english; however we should be more flexible and also be open for any other language
## Issue

N/A Ref : CPLP-3451

## Checklist

Please delete options that are not relevant.

- [x ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [ ] I have created and linked IP issues or requested their creation by a committer
- [x ] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x ] I have added tests that prove my changes work
- [x ] I have checked that new and existing tests pass locally with my changes
- [x ] I have commented my code, particularly in hard-to-understand areas

2023-11-16 09:30 UTC, Phil91 reviewed
@jjeroch should only the new table be created without adjusting the existing one?
If we want to adjust the existing one this would result in an adjustment of the existing seeding and queries as well.

2023-11-17 16:25 UTC, ntruchsess requested changes
please keep in mind under no circumstances migrations may be created in parallel and then be merged. As the current rc4 contains a migration (see #339) the following conditions must be fulfilled merging this PR:
1) PR #339 must be merged into rc4
2) rc4 must be released and merged into dev
3) The migration that is included in this PR must be reverted (it is crucial to start with the unchanged PortalDBContextSnapshot that comes with the rebase on dev, otherwise the delta that is being calculated is incorrect).
4) this PR must be rebased on dev (to include the migration that is part of PR #339
5) the migration to be included in this PR must be recreated.

2023-11-22 11:01 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.PortalEntities/Entities/CountriesLongNames.cs
> +public class CountriesLongNames
Changed entity name to 'CountryLongName'

2023-11-22 11:02 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.PortalEntities/Entities/CountriesLongNames.cs
> + * Copyright (c) 2021, 2023 BMW Group AG
Removed copyright BMW Group line

2023-11-22 11:02 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.PortalEntities/PortalDbContext.cs
> +               .WithMany(o => o.CountriesLongNames)
Formatted properly

2023-11-23 07:36 UTC, Phil91 reviewed
We should discuss if the old properties in country should be removed or not.

2023-11-23 07:36 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Migrations/PortalDbContextModelSnapshot.cs
> +﻿// <auto-generated />
Please readd the copyright header

2023-11-23 07:37 UTC, Phil91 commented on src/portalbackend/PortalBackend.PortalEntities/Entities/CountriesLongNames.cs
> +public class CountriesLongNames
Its still named `CountryLongNames`

2023-11-23 07:53 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.Migrations/Migrations/PortalDbContextModelSnapshot.cs
> +﻿// <auto-generated />
Header added please check

2023-11-28 18:34 UTC, ntruchsess commented on src/portalbackend/PortalBackend.PortalEntities/Entities/CountriesLongNames.cs
> +public class CountriesLongNames
fixed

2023-11-28 18:35 UTC, ntruchsess commented
> We should discuss if the old properties in country should be removed or not.

good point. There also should be a data-migration script in the migration

2023-11-28 20:31 UTC, ntruchsess approved these changes
@Phil91 : I did adjust the naming and removed the old properties from country. Migration has been recreated accordingly. Please double check

2023-11-28 20:31 UTC, ntruchsess commented on src/portalbackend/PortalBackend.Migrations/Seeder/Data/country_long_names.json
> +      "country_name_en": "United Arab Emirates (the)"
done

2023-11-28 20:31 UTC, ntruchsess commented on src/portalbackend/PortalBackend.Migrations/Seeder/Data/country_long_names.json
> +      "country_name_en": "Nepal"
done

2023-11-28 20:35 UTC, ntruchsess approved these changes
@Phil91 : I did adjust the naming and removed the old properties from country adjusting the respective queries in a backward-compatible way. Seeding-data is adjusted as well. Please double-check

2023-11-29 06:39 UTC, Phil91 approved these changes
@ntruchsess Lgtm

2023-11-29 07:43 UTC, merged