feat(worker): add new business process workers
eclipse-tractusx/portal-backend pull request #345
Opened 2023-11-21 14:23 UTC by Phil91

## Description

add worker for invitation
add mailing worker

## Why

Currently if the sending of a mail fails the user receives an error although the request itself was successful. Therefore the mail sending was moved to an process.

## Issue

N/A - Jira Issue: CPLP-3383

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-01-08 17:55 UTC, ntruchsess requested changes

2024-01-08 17:55 UTC, ntruchsess commented on src/processes/Invitation.Executor/InvitationProcessService.cs
> +    public async Task<(IEnumerable<ProcessStepTypeId>? nextStepTypeIds, ProcessStepStatusId stepStatusId, bool modified, string? processMessage)> CreateIdpDatabase(Guid companyInvitationId)
While the separation of CreateIdpDatabase into a separate step might technically not be required (there is nothing that can fail besides loosing the db-connection during the transaction), the SetupIdp-step itself consists of multiple remote calls that may fail individually and should be split into more fine-granular steps.

2024-01-08 17:55 UTC, ntruchsess commented on src/processes/Mailing.Executer/MailingProcessTypeExecutor.cs
> +            await _mailingService.SendMails(mail, mailParameter, Enumerable.Repeat(template, 1)).ConfigureAwait(false);
as from a process-step SendMails should never be called with multiple templates it is advisable to either change the method to accept a single template only or (if this is not feasible now do to many references) - create a new SendMail-method that accepts a single template and mark the existing SendMails-method as obsolete

2024-01-09 08:24 UTC, ntruchsess requested changes

2024-01-09 08:24 UTC, ntruchsess commented on src/portalbackend/PortalBackend.PortalEntities/PortalDbContext.cs
> +                .HasJsonConversion();
in EF7 Support for aggregate types by OwnsOne/OwnsMany has been extended to json-columns. There's a new builder -method 'toJson', so maybe this can be accomplished without a custom converter? (https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#json-columns)

2024-01-09 15:03 UTC, Phil91 commented on src/portalbackend/PortalBackend.PortalEntities/PortalDbContext.cs
> +                .HasJsonConversion();
I just remembered why I created a custom Extension for it.

<img width="649" alt="image" src="https://github.com/eclipse-tractusx/portal-backend/assets/7672600/a8c50a6e-0f80-4a79-8b5a-aae0b2ecf0fb">

sadly currently the Postgres implementation doesn't support the functionality.

2024-01-09 15:09 UTC, Phil91 commented on src/processes/Invitation.Executor/InvitationProcessService.cs
> +    public async Task<(IEnumerable<ProcessStepTypeId>? nextStepTypeIds, ProcessStepStatusId stepStatusId, bool modified, string? processMessage)> CreateIdpDatabase(Guid companyInvitationId)
adjusted as discussed

2024-01-09 15:09 UTC, Phil91 commented on src/processes/Mailing.Executer/MailingProcessTypeExecutor.cs
> +            await _mailingService.SendMails(mail, mailParameter, Enumerable.Repeat(template, 1)).ConfigureAwait(false);
adjusted as discussed

2024-01-10 20:43 UTC, ntruchsess requested changes

2024-01-10 20:43 UTC, ntruchsess commented on src/externalsystems/Provisioning.Library/IdpManagement.cs
> +    public async Task<(string ClientId, string Secret)> CreateSharedIdpServiceAccountAsync(string realm)
this method must be split into multiple single-write-call-to-keycloak methods.

2024-01-10 20:43 UTC, ntruchsess commented on src/externalsystems/Provisioning.Library/IdpManagement.cs
> +    public async Task CreateSharedRealmIdpClientAsync(string realm, string loginTheme, string organisationName, string clientId, string secret)
must also be split into multiple methods (one per write-access to keycloak)

2024-01-10 20:43 UTC, ntruchsess commented on src/keycloak/Keycloak.Library/Models/IdentityProviders/IdentityProvider.cs
> +using System.Text.Json.Serialization;
this is pointless - as long the keycloak-library is not refactored it will use Newtonsoft (regardless of what annotations are being used in the models).

2024-01-10 20:43 UTC, ntruchsess commented on src/keycloak/Keycloak.Library/Models/RealmsAdmin/Realm.cs
> +    [JsonPropertyName("id")]
this is pointless - as long the keycloak-library is not refactored it will use Newtonsoft (regardless of what annotations are being used in the models).

2024-01-10 20:43 UTC, ntruchsess commented on src/processes/Invitation.Executor/InvitationProcessService.cs
> +            await _mailingService.SendMails(email, mailParameters, "RegistrationTemplate").ConfigureAwait(false);
afaik there's already a mailing process type to execute async in process

2024-01-10 20:43 UTC, ntruchsess commented on src/processes/Invitation.Executor/InvitationProcessTypeExecutor.cs
> +                _ => (null, ProcessStepStatusId.TODO, false, null)
there shouldn't be any valid processStepTypeIds left so default should rather throw UnexpectedConditionException to detect if we forgot any.

2024-01-10 20:43 UTC, ntruchsess commented on src/processes/NetworkRegistration.Library/NetworkRegistrationHandler.cs
> +            await _mailingService.SendMails(receiver, mailParameters, "OspWelcomeMail").ConfigureAwait(false);
this should rather schedule a mailing process

2024-01-10 20:43 UTC, ntruchsess commented on src/registration/ApplicationActivation.Library/ApplicationActivationService.cs
> +            await _mailingService.SendMails(user.Email, mailParameters, "EmailRegistrationWelcomeTemplate").ConfigureAwait(false);
this should schedule mailing processes instead

2024-01-10 20:44 UTC, ntruchsess commented on src/portalbackend/PortalBackend.PortalEntities/PortalDbContext.cs
> +                .HasJsonConversion();
that's really sad :-(

2024-01-10 20:45 UTC, ntruchsess commented on src/processes/Invitation.Executor/InvitationProcessService.cs
> +    public async Task<(IEnumerable<ProcessStepTypeId>? nextStepTypeIds, ProcessStepStatusId stepStatusId, bool modified, string? processMessage)> CreateIdpDatabase(Guid companyInvitationId)
'mostly' adjusted ;-)

2024-01-11 08:45 UTC, Phil91 commented on src/externalsystems/Provisioning.Library/IdpManagement.cs
> +    public async Task<(string ClientId, string Secret)> CreateSharedIdpServiceAccountAsync(string realm)
done

2024-01-11 08:46 UTC, Phil91 commented on src/externalsystems/Provisioning.Library/IdpManagement.cs
> +    public async Task CreateSharedRealmIdpClientAsync(string realm, string loginTheme, string organisationName, string clientId, string secret)
done, didn't saw the second one.

2024-01-11 08:46 UTC, Phil91 commented on src/keycloak/Keycloak.Library/Models/RealmsAdmin/Realm.cs
> +    [JsonPropertyName("id")]
rolledback

2024-01-11 08:46 UTC, Phil91 commented on src/processes/Invitation.Executor/InvitationProcessTypeExecutor.cs
> +                _ => (null, ProcessStepStatusId.TODO, false, null)
changed

2024-01-11 08:46 UTC, Phil91 commented on src/processes/NetworkRegistration.Library/NetworkRegistrationHandler.cs
> +            await _mailingService.SendMails(receiver, mailParameters, "OspWelcomeMail").ConfigureAwait(false);
done

2024-01-11 08:46 UTC, Phil91 commented on src/registration/ApplicationActivation.Library/ApplicationActivationService.cs
> +            await _mailingService.SendMails(user.Email, mailParameters, "EmailRegistrationWelcomeTemplate").ConfigureAwait(false);
done

2024-01-11 08:47 UTC, Phil91 commented on src/keycloak/Keycloak.Library/Models/IdentityProviders/IdentityProvider.cs
> +using System.Text.Json.Serialization;
rolledback

2024-03-07 15:20 UTC, ntruchsess commented
please fix the conflicts

2024-03-07 15:21 UTC, ntruchsess requested changes
please first fix the conflicts

2024-03-14 15:43 UTC, ntruchsess approved these changes

2024-03-15 09:02 UTC, merged