feat(process): slimline process identity config
eclipse-tractusx/portal-backend pull request #361
Opened 2023-11-27 13:22 UTC by Phil91

## Description

All configuration values needed for the process identity were removed except for the identity id.

## Why

The determination of the identity needed for the process worker is now done with a database request to get the needed values for the specified user.

## Issue

N/A - Jira Issue: CPLP-3102

## Corresponding CD PR

[#130](https://github.com/eclipse-tractusx/portal-cd/pull/130)

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2023-11-28 22:38 UTC, ntruchsess requested changes

2023-11-28 22:38 UTC, ntruchsess commented on src/keycloak/Keycloak.Authentication/KeycloakClaimsTransformation.cs
> +                case false when !Guid.TryParse(preferredUserName, out var identityId):
the ! in when !Guid.TryParse looks incorrect. We should have a unit-test for the method TransformAsync

instead of the cumbersome switch / case that somewhat hides the actual flow of information I recommend a more traditional implementation:
```
private async ValueTask<bool> AddIdentity(ClaimsPrincipal principal, ClaimsIdentity claimsIdentity)
{
    var preferredUserName = principal.Claims.SingleOrDefault(x => x.Type == PortalClaimTypes.PreferredUserName)?.Value;

    if (!string.IsNullOrWhiteSpace(preferredUserName) && Guid.TryParse(preferredUserName, out var identityId))
    {
        claimsIdentity.AddClaim(new Claim(PortalClaimTypes.IdentityId, identityId.ToString()));
        return true;
    }

    var sub = principal.Claims.SingleOrDefault(x => x.Type == PortalClaimTypes.Sub)?.Value;
    _logger.LogInformation("Preferred user name {PreferredUserName} couldn't be parsed to uuid for userEntityId {Sub}", preferredUserName, sub);

    IdentityData? identityData;
    if (string.IsNullOrWhiteSpace(sub) || (identityData = await _portalDbRepositories.GetInstance<IUserRepository>().GetActiveUserDataByUserEntityId(sub).ConfigureAwait(false)) == null)
    {
        _logger.LogWarning("No identity found for userEntityId {Sub}", sub);
        return false;
    }

    claimsIdentity.AddClaim(new Claim(PortalClaimTypes.IdentityId, identityData.UserId.ToString()));
    return true;
}
```

2023-11-28 22:47 UTC, ntruchsess commented on src/framework/Framework.Web/ClaimsIdentityIdDetermination.cs
> +    public Guid IdentityId => (_identityId ??= _httpContextAccessor.HttpContext?.User.GetIdentityId())!.Value;
sonar marks this as a code smell. According to the smell's documentation it should accept
```public Guid IdentityId => (_identityId ?? (_identityId = _httpContextAccessor.HttpContext?.User.GetIdentityId()))!.Value;```
(I guess the rule doesn't know about the ??= operator, so maybe we should just mark this as a false positive?)

2023-11-29 09:45 UTC, Phil91 commented on src/keycloak/Keycloak.Authentication/KeycloakClaimsTransformation.cs
> +                case false when !Guid.TryParse(preferredUserName, out var identityId):
I did change the implementation and added unit tests.

2023-11-29 09:46 UTC, Phil91 commented on src/framework/Framework.Web/ClaimsIdentityIdDetermination.cs
> +    public Guid IdentityId => (_identityId ??= _httpContextAccessor.HttpContext?.User.GetIdentityId())!.Value;
I'd mark it as a false positive

2023-11-29 11:38 UTC, ntruchsess approved these changes

2023-11-29 11:45 UTC, merged