feat(idp): adjust delete idp endpoint
eclipse-tractusx/portal-backend pull request #379
Opened 2023-12-11 18:18 UTC by Phil91

## Description

* enable delete of managed idps

## Why

to have the possibility to delete the managed idps

## Issue

N/A - Jira Issue: CPLP-3329

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2023-12-11 18:18 UTC, Phil91 commented
before merging this PR, #379  should be merged

2024-01-15 16:46 UTC, ntruchsess requested changes
when setting users to DELETED the assigned Roles must be removed as well. As a consequence the role-based email-service cannot send emails to those users afterwards. That means the Names and email-addresses for the email-service must be determined before deleting the users

2024-01-15 16:46 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/IdentityRepository.cs
> +                x.Identity!.Company!.IdentityProviders.Any(idp => identityIds.Contains(idp.Id) && idp.OwnerId != x.Identity!.CompanyId) &&
this is comparing apples to pears (identityIds to idpIds).

2024-01-15 16:46 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/IdentityRepository.cs
> +                x.Identity!.Company!.IdentityProviders.Any(idp => identityIds.Contains(idp.Id) && idp.OwnerId != x.Identity!.CompanyId) &&
solved

2024-01-16 08:58 UTC, Phil91 commented
> when setting users to DELETED the assigned Roles must be removed as well. As a consequence the role-based email-service cannot send emails to those users afterwards. That means the Names and email-addresses for the email-service must be determined before deleting the users

added the deletion of the assigned roles

2024-01-22 14:25 UTC, ntruchsess approved these changes

2024-01-22 14:27 UTC, merged