feat(osp): add decline endpoint for customer
eclipse-tractusx/portal-backend pull request #384
Opened 2023-12-15 13:53 UTC by Phil91

## Description

add new endpoint to decline a company application which was created by an osp

## Why

to enable onboarded customers to decline their application by themselves

## Issue

Refs: CPLP-3497

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-01-15 13:15 UTC, ntruchsess requested changes

2024-01-15 13:15 UTC, ntruchsess commented on src/registration/Registration.Service/BusinessLogic/NetworkBusinessLogic.cs
> +                    ps => { ps.ProcessStepStatusId = ProcessStepStatusId.ABORTED; })));
what is the semantic difference in between 'SKIPPED' and 'ABORTED'? I do not think we need to introduce another stepstatus for the same thing.

2024-01-15 13:15 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/NetworkRepository.cs
> +    public Task<(bool Exists, (Guid CompanyId, CompanyStatusId CompanyStatusId, IEnumerable<(Guid IdentityId, UserStatusId UserStatus)> Identities) CompanyData, IEnumerable<(Guid InvitationId, Invita
I suggest a more efficient query:
```
    public Task<(
        bool Exists,
        bool IsValidTypeId,
        bool IsValidStatusId,
        bool IsValidCompany,
        (
            (CompanyStatusId CompanyStatusId, IEnumerable<(Guid IdentityId, UserStatusId UserStatus)> Identities) CompanyData,
            IEnumerable<(Guid InvitationId, InvitationStatusId StatusId)> InvitationData,
            (Guid ProcessId, IEnumerable<(Guid ProcessStepId, ProcessStepTypeId ProcessStepTypeId, ProcessStepStatusId ProcessStepStatusId)> ProcessSteps) ProcessData
        )? Data)> GetDeclineDataForApplicationId(Guid applicationId, CompanyApplicationTypeId validTypeId, IEnumerable<CompanyApplicationStatusId> validStatusIds, Guid companyId) =>
    _context.NetworkRegistrations
        .AsSplitQuery()
        .Where(registration => registration.CompanyApplication!.Id == applicationId)
        .Select(registration => new
        {
            IsValidType = validTypeId == registration.CompanyApplication!.CompanyApplicationTypeId,
            IsValidStatus = validStatusIds.Contains(registration.CompanyApplication.ApplicationStatusId),
            IsValidCompany = registration.CompanyId == companyId,
            Invitations = registration.CompanyApplication.Invitations,
            Company = registration.Company,
            Process = registration.Process
        })
        .Select(x => new ValueTuple<
                bool,
                bool,
                bool,
                bool,
                ValueTuple<
                    ValueTuple<CompanyStatusId, IEnumerable<ValueTuple<Guid, UserStatusId>>>,
                    IEnumerable<ValueTuple<Guid, InvitationStatusId>>,
                    ValueTuple<Guid, IEnumerable<ValueTuple<Guid, ProcessStepTypeId, ProcessStepStatusId>>>
                >?>(
            true,
            x.IsValidType,
            x.IsValidStatus,
            x.IsValidCompany,
            x.IsValidType && x.IsValidStatus && x.IsValidCompany
                ? new ValueTuple<
                    ValueTuple<CompanyStatusId, IEnumerable<ValueTuple<Guid, UserStatusId>>>,
                    IEnumerable<ValueTuple<Guid, InvitationStatusId>>,
                    ValueTuple<Guid, IEnumerable<ValueTuple<Guid, ProcessStepTypeId, ProcessStepStatusId>>>>(
                        new ValueTuple<CompanyStatusId, IEnumerable<ValueTuple<Guid, UserStatusId>>>(
                            x.Company!.CompanyStatusId,
                            x.Company.Identities.Select(i => new ValueTuple<Guid, UserStatusId>(i.Id, i.UserStatusId))),
                        x.Invitations.Select(x => new ValueTuple<Guid, InvitationStatusId>(
                            x.Id,
                            x.InvitationStatusId)),
                        new ValueTuple<Guid, IEnumerable<ValueTuple<Guid, ProcessStepTypeId, ProcessStepStatusId>>>(
                            x.Process!.Id,
                            x.Process.ProcessSteps
                                .Where(ps => ps.ProcessStepStatusId == ProcessStepStatusId.TODO)
                                .Select(x => new ValueTuple<Guid, ProcessStepTypeId, ProcessStepStatusId>(x.Id, x.ProcessStepTypeId, x.ProcessStepStatusId))))
                : null
        ))
        .SingleOrDefaultAsync();
```

2024-01-15 13:18 UTC, ntruchsess requested changes

2024-01-15 13:18 UTC, ntruchsess commented on src/registration/Registration.Service/BusinessLogic/NetworkBusinessLogic.cs
> +        processStepRepository.AttachAndModifyProcessSteps(data.ProcessSteps
Implementing process-step-handling explicitly is error-prone. Here at least the concurrency-check on the process-entity has been forgotten to implement. I strongly suggest to use the framework-methods that are implemented in ManualProcessStepDataExtensions

2024-01-17 10:18 UTC, Phil91 commented on src/registration/Registration.Service/BusinessLogic/NetworkBusinessLogic.cs
> +        processStepRepository.AttachAndModifyProcessSteps(data.ProcessSteps
adjusted.

2024-01-17 10:19 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/NetworkRepository.cs
> +    public Task<(bool Exists, (Guid CompanyId, CompanyStatusId CompanyStatusId, IEnumerable<(Guid IdentityId, UserStatusId UserStatus)> Identities) CompanyData, IEnumerable<(Guid InvitationId, Invita
adjusted and usings in business logic adjusted as well

2024-01-17 10:19 UTC, Phil91 commented on src/registration/Registration.Service/BusinessLogic/NetworkBusinessLogic.cs
> +                    ps => { ps.ProcessStepStatusId = ProcessStepStatusId.ABORTED; })));
thought it'd make sense to be able to differentiate, but removed it since it's kind of duplicated

2024-01-17 10:19 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs
> +            .SelectMany(x => x.Company!.Identities.Where(i => i.IdentityTypeId == IdentityTypeId.COMPANY_USER && (i.UserStatusId != UserStatusId.DELETED || i.UserStatusId == UserStatusId.INACTIVE)).S
adjusted

2024-01-22 18:09 UTC, ntruchsess approved these changes

2024-01-22 18:16 UTC, merged