feat(registration): add current user to applicationDeclineData
eclipse-tractusx/portal-backend pull request #390
Opened 2023-12-20 13:43 UTC by ntruchsess

## Description

current logged-in user has been added to response of endpoint 'applications/declinedata'

## Why

application-decline-page needs to display currently logged-in user.

## Issue

N/A

## Checklist

Please delete options that are not relevant.

- [X] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [X] I have performed a self-review of my own code
- [X] I have successfully tested my changes locally
- [X] I have added tests that prove my changes work
- [X] I have checked that new and existing tests pass locally with my changes

2023-12-20 13:59 UTC, ntruchsess commented
obsolete, needs to be created by someone else

2023-12-20 14:01 UTC, ntruchsess commented
reopened

2023-12-22 11:43 UTC, Phil91 requested changes

2023-12-22 11:43 UTC, Phil91 commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        var user = CreateNameString(data.FirstName, data.LastName, data.Email) ?? "unknown user";
since CreateNameString will always return a string that is not nullable `?? "unknown user"` can be removed.

2024-01-02 09:52 UTC, Phil91 commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        var user = CreateNameString(data.FirstName, data.LastName, data.Email) ?? "unknown user";
have removed the code

2024-01-02 09:54 UTC, Phil91 approved these changes

2024-01-02 10:00 UTC, merged