feat(email template): created decline registration template
eclipse-tractusx/portal-backend pull request #394
Opened 2023-12-28 08:41 UTC by nidhigarg-bmw

## Description

Created Decline Registration template

## Why

When user decline the request then this template will be sent

## Issue

n/a

## Checklist

Please delete options that are not relevant.

- [X] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [X] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [X] I have performed a self-review of my own code
- [X] I have successfully tested my changes locally

2023-12-28 09:44 UTC, jjeroch requested changes

2023-12-28 09:44 UTC, jjeroch commented on CHANGELOG.md
> +  * released new email template 'decline registration'
@nidhigarg-bmw correction needed. You have by mistake added the changeLog item in the closed section for 1.7.0 release. Please delete this again. No changeLog update in the backend repo

2024-01-02 07:17 UTC, Phil91 approved these changes

2024-01-02 09:24 UTC, jjeroch commented
@nidhigarg-bmw please have a look at the sonar fails. Ideally also sync with Mano, he did a number of the other email templates and might have useful hints to fix the issue (if needed)

2024-01-02 10:41 UTC, nidhigarg-bmw commented
> @nidhigarg-bmw please have a look at the sonar fails. Ideally also sync with Mano, he did a number of the other email templates and might have useful hints to fix the issue (if needed)

@jjeroch I already discussed with Mano, he told that they are known issues in all the templates. We can ignore these for now.

2024-01-02 11:07 UTC, jjeroch commented
> > @nidhigarg-bmw please have a look at the sonar fails. Ideally also sync with Mano, he did a number of the other email templates and might have useful hints to fix the issue (if needed)
> 
> @jjeroch I already discussed with Mano, he told that they are known issues in all the templates. We can ignore these for now.

@manojava-gk  & @nidhigarg-bmw  in sonar it shows the issue as "unresolved" ideally we decide/switch the status to "Won't Fix" or "False Positive"  (if this make sense) - please sync once if we ideally change the status of all those findings instead of leaving is "unresolved" - unresolved has always the message that something still needs to be done 
<img width="369" alt="image" src="https://github.com/eclipse-tractusx/portal-backend/assets/94133633/553e716a-7439-42e6-9656-25d4ead42832">

If you have troubles to update the status, please ping @Phil91

2024-01-07 09:48 UTC, merged