feat: change search for notifications to or
eclipse-tractusx/portal-backend pull request #396
Opened 2024-01-04 07:55 UTC by Phil91

## Description

Changing the search query for notifications instead of and to or

## Why

to enable a better searchability for the notifications

## Issue

Refs: CPLP-3045

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-01-10 03:48 UTC, oyo submitted a review, later dismissed
Actually I thought we add a parameter whether the parameters should be treated as AND or OR, but since the FE is currently the only application using this endpoint we can also go with this simple fix.

2024-01-10 15:31 UTC, ntruchsess requested changes
we need to discuss the expected semantics.

2024-01-10 15:31 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/NotificationRepository.cs
> +                    searchQuery == null || notification.Content != null && EF.Functions.ILike(notification.Content, $"%{searchQuery.EscapeForILike()}%")))
this means not sending the searchTypeId-parameter will also invalidate the searchQuery-parameter

2024-01-11 13:57 UTC, ntruchsess approved these changes

2024-01-11 14:02 UTC, merged