feat(ssi): add expiry handling for ssi
eclipse-tractusx/portal-backend pull request #397
Opened 2024-01-05 07:26 UTC by Phil91

## Description

* add cleanup process for expired ssi credentials older than x month
* add automatic decline process for pending ssi credentials
* post generated expiry date to miw
* adjust detail versions table for certificates
* add seeding for certificate versions

## Why

to add the expiry handling for credential ssi's

## Issue

Refs: N/A - Jira Issue: CPLP-3398

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-01-08 15:56 UTC, evegufy commented on docker/notice-credential-service.md
> +DockerHub: [https://hub.docker.com/r/tractusx/portal-credential-service](https://hub.docker.com/r/tractusx/portal-maintenance-service)
Links to maintenance service

2024-01-08 16:14 UTC, evegufy requested changes
Looks good in general!
Could you please provide the feedback Gitguardian that the 4 discovered secrets a false positives?
And one comment: For the overall consistency it might be better to call the project Credential.App (like it's called in most places) instead of VerifiedCredential.App.

2024-01-09 14:48 UTC, ntruchsess requested changes

2024-01-09 14:55 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
> +                                c.VerifiedCredentialExternalTypeDetailVersion.Version!,
since the `GetAllCredentialDetails`selects only credentials of type use case the trigger constraint does the validation for use, there can't be an entry with version = null in the database for a use case credential, therefor that should be okay or am I mistaken?

2024-01-10 09:52 UTC, Phil91 commented on src/portalbackend/PortalBackend.PortalEntities/Enums/ExpiryCheckTypeId.cs
> +    OneMonth = 1,
adjusted

2024-01-10 09:52 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanySsiDetailsRepository.cs
> +                                e.Version,
adjusted

2024-01-10 09:52 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanySsiDetailsRepository.cs
> +                                e.Version,
missed that. adjusted.

2024-01-10 09:52 UTC, Phil91 commented on src/externalsystems/Custodian.Library/CustodianService.cs
> +            detailData.Template!,
changed the version to non nullable and adjusted the validation in the businessLogic

2024-01-10 09:52 UTC, Phil91 commented on src/credentials/VerifiedCredential.App/ExpiryCheckService.cs
> +        if (!stoppingToken.IsCancellationRequested)
moved the cancellation to the asyncEnumerable

2024-01-10 09:52 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
> +        if (verifiedCredentialExternalTypeDetailId == null && detailVersionIds.Count() > 1)
adjusted to `detailVersionIds.Count() != 1`

2024-01-10 09:52 UTC, Phil91 commented on docker/notice-credential-service.md
> +DockerHub: [https://hub.docker.com/r/tractusx/portal-credential-service](https://hub.docker.com/r/tractusx/portal-maintenance-service)
adjusted

2024-01-10 09:52 UTC, Phil91 commented
> Looks good in general! Could you please provide the feedback to Gitguardian that the 4 discovered secrets are false positives? And one comment: For the overall consistency it might be better to call the project Credential.App (like it's called in most places) instead of VerifiedCredential.App.

done :)

2024-01-10 13:19 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
> +                                c.VerifiedCredentialExternalTypeDetailVersion.Version!,
as the trigger-constraint is technically not linked to this line of code (like definitions in an entity-class are) it might be altered changing the behavior of this code, but nobody would notice.
Behavior of code should always be well defined and never rely on assumptions that are beyond the scope of the local compilation unit. If it does such assumptions should be asserted properly. With nullability it's easy: if it's declared nullable but the assumption is the actual value is always non-null just add a simple non-null check like xxx ?? throw new UnexpectedConditionException("xxx should not be null here") and the code will notify you whenever the assumptions are no longer met.

2024-01-10 13:39 UTC, evegufy requested changes

2024-01-10 14:27 UTC, ntruchsess requested changes

2024-01-10 14:27 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanySsiDetailsRepository.cs
> +                    (x.ExpiryDate <= now.AddMonths(2) && x.ExpiryCheckTypeId == null)
what if ExpiryCheckTypeId is set to ONE_MONTH?

2024-01-10 14:27 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanySsiDetailsRepository.cs
> +                x.ExpiryDate!.Value,
either ExpiryDate != null must be added to the Where-condition, or CredentialExpiryDate.ExpiryDate must be declared as nullable.

2024-01-11 06:53 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanySsiDetailsRepository.cs
> +                x.ExpiryDate!.Value,
declared `CredentialExpiryDate.ExpiryDate` as nullable

2024-01-11 06:53 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanySsiDetailsRepository.cs
> +                    (x.ExpiryDate <= now.AddMonths(2) && x.ExpiryCheckTypeId == null)
adjusted the check

2024-01-11 06:53 UTC, Phil91 commented on .github/workflows/credential-service.yml
> +# Copyright (c) 2021, 2023 Contributors to the Eclipse Foundation
done :)

2024-01-11 18:10 UTC, ntruchsess requested changes

2024-01-12 08:25 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanySsiDetailsRepository.cs
> +    public IAsyncEnumerable<CredentialExpiryData> GetExpiryData(DateTimeOffset now, DateTimeOffset inactiveVcsToDelete, DateTimeOffset expiredVcsToDelete) =>
thanks, really like the implementation.
Adjusted

2024-01-12 13:35 UTC, ntruchsess submitted a review, later dismissed

2024-03-05 10:56 UTC, Phil91 commented
This PR will be closed since the implementation will happen in the sis-credential-issuer repository

2024-04-04 19:25 UTC, Phil91 commented
Closing this PR. The changes are included in the new [ssi-credential-issuer](https://github.com/eclipse-tractusx/ssi-credential-issuer) repo

2024-04-04 19:25 UTC, closed without merging