feat(errorhandling): error handling service account controller
eclipse-tractusx/portal-backend pull request #398
Opened 2024-01-05 11:38 UTC by AnuragNagpure

## Description

Implement new error handling for the service controller

## Why

Implement for all POST and PUT endpoints the new error handling.

## Issue

N/A Ref: CPLP-3589

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-01-07 09:30 UTC, Phil91 commented
@AnuragNagpure the target branch was set to `main` , please don't do that. I've changed it to the `dev` branch

2024-01-07 09:39 UTC, Phil91 requested changes

2024-01-07 09:39 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
> +using System.Xml;
can be removed

2024-01-07 09:39 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
> +
please remove empty line

2024-01-07 09:39 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
> +
please remove empty line

2024-01-07 09:39 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
> +
In line 91 we call `_serviceAccountCreation.CreateServiceAccountAsync` please adjust the error handling within this method to the new logic as well

2024-01-07 09:39 UTC, Phil91 commented on src/administration/Administration.Service/ErrorHandling/AdministrationServiceAccountErrorMessageContainer.cs
> +                { AdministrationServiceAccountErrors.SERVICE_NAME_EMPTY_ARGUMENT,"name must not be empty, {name}"},
please add a whitespace between the parameters, same applies for the following entries

2024-01-07 09:39 UTC, Phil91 commented on src/administration/Administration.Service/ErrorHandling/AdministrationServiceAccountErrorMessageContainer.cs
> +namespace Org.Eclipse.TractusX.Portal.Backend.Administration.ErrorHandling;
the namespace isn't correct. Please change to:

`Org.Eclipse.TractusX.Portal.Backend.Administration.Service.ErrorHandling

2024-01-09 05:33 UTC, AnuragNagpure commented on src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
> +using System.Xml;
removed

2024-01-09 05:33 UTC, AnuragNagpure commented on src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
> +
added required exception

2024-01-09 05:34 UTC, AnuragNagpure commented on src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
> +
removed

2024-01-09 05:34 UTC, AnuragNagpure commented on src/administration/Administration.Service/ErrorHandling/AdministrationServiceAccountErrorMessageContainer.cs
> +                { AdministrationServiceAccountErrors.SERVICE_NAME_EMPTY_ARGUMENT,"name must not be empty, {name}"},
added

2024-01-09 05:34 UTC, AnuragNagpure commented on src/administration/Administration.Service/ErrorHandling/AdministrationServiceAccountErrorMessageContainer.cs
> +namespace Org.Eclipse.TractusX.Portal.Backend.Administration.ErrorHandling;
changed as per mentioned above.

2024-01-11 14:52 UTC, Phil91 approved these changes

2024-01-11 14:53 UTC, merged