feat(conformity): enable conformity approval services
eclipse-tractusx/portal-backend pull request #399
Opened 2024-01-05 14:26 UTC by AnuragNagpure

## Description

db seeding data need to get enhanced.

## Why

Adding required db seeding data for further enhancement in table portal.agreements

## Issue

N/A Ref: CPLP-3580

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-01-07 09:42 UTC, Phil91 requested changes

2024-01-07 09:42 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Seeder/Data/agreements.json
> +
please remove the empty line

2024-01-07 09:43 UTC, Phil91 commented
@jjeroch is it correct that the new agreement isn't linked to a document and use case?

2024-01-07 19:19 UTC, jjeroch requested changes

2024-01-07 19:19 UTC, jjeroch commented on src/portalbackend/PortalBackend.Migrations/Seeder/Data/agreements.json
> +    "use_case_id": null,
useCaseId to be set to '1aacde78-35ec-4df3-ba1e-f988cddcbbd9'

2024-01-07 19:19 UTC, jjeroch commented
> @jjeroch is it correct that the new agreement isn't linked to a document and use case?

@Phil91  thanks for sharing, we need to set the useCaseId, the rest is fine. Comment for Anurag added

2024-01-08 05:36 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.Migrations/Seeder/Data/agreements.json
> +
removed

2024-01-08 05:36 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.Migrations/Seeder/Data/agreements.json
> +    "use_case_id": null,
useCaseId set

2024-01-08 09:17 UTC, Phil91 approved these changes

2024-01-08 09:23 UTC, merged