feat(apps & services)-get provided subscription status
eclipse-tractusx/portal-backend pull request #42
Opened 2023-05-19 11:16 UTC by qxz2mqe

## Description

Added Technical User flag for company service accounts

## Why

the FE to know if technical user setup is needed/relevant for the service/app or not for endpoint
GET: /api/apps/provided/subscription-status
GET: /api/services/provided/subscription-status

## Issue

[Link to Github issue](https://jira.catena-x.net/browse/CPLP-2661).

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

2023-05-22 06:03 UTC, Phil91 requested changes

2023-05-22 06:03 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
> +                                s.CompanyServiceAccounts.Any())),
Please add or adjust the current unit test to check whether the correct values are returned from the database

2023-05-22 06:05 UTC, Phil91 commented
@qxz2mqe please check the todos if completed or delete them if not applying

2023-05-22 09:50 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
> +                                s.CompanyServiceAccounts.Any())),
resolved

2023-05-22 22:28 UTC, ntruchsess requested changes

2023-05-22 22:28 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
> +                                s.Offer!.TechnicalUserProfiles.Any() && s.Offer!.TechnicalUserProfiles.All(tup => tup.UserRoles.Any()))),
from my understanding a technical user needs to be created and setup whenever at least one of those profiles has at least one user_role assigned.
the condition then would be:
`s.Offer!.TechnicalUserProfiles.Any(tup => tup.UserRoles.Any()))),`
@jjeroch: can you please confirm?
(I also raised that question in the ticket).

2023-05-22 22:28 UTC, ntruchsess commented on tests/portalbackend/PortalBackend.DBAccess.Tests/OfferSubscriptionRepositoryTest.cs
> +            results.Data.Should().AllBeOfType<OfferCompanySubscriptionStatusData>().Which.First().CompanySubscriptionStatuses.First().TechnicalUser.Should().Be(false);
please make sure an offerId that would return true is included in the set of offers passed as InlineData (hint: to do so with minimal changes to this test-method add the expected returnvalue of 'technicalUser' to the parameters of the test-method)

2023-05-22 22:33 UTC, ntruchsess commented
> ## Checklist
> 
> Please delete options that are not relevant.
> 
>     *
>- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
>- [ ] I have successfully tested my changes locally
>- [ ] I have added tests that prove my changes work
>- [ ] I have checked that new and existing tests pass locally with my changes
>- [ ] I have commented my code, particularly in hard-to-understand areas

2023-05-24 05:23 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
> +                                s.Offer!.TechnicalUserProfiles.Any() && s.Offer!.TechnicalUserProfiles.All(tup => tup.UserRoles.Any()))),
fixed

2023-05-24 05:23 UTC, qxz2mqe commented on tests/portalbackend/PortalBackend.DBAccess.Tests/OfferSubscriptionRepositoryTest.cs
> +            results.Data.Should().AllBeOfType<OfferCompanySubscriptionStatusData>().Which.First().CompanySubscriptionStatuses.First().TechnicalUser.Should().Be(false);
fixed

2023-05-24 06:40 UTC, ntruchsess commented on tests/portalbackend/PortalBackend.DBAccess.Tests/OfferSubscriptionRepositoryTest.cs
> +            results.Data.Should().AllBeOfType<OfferCompanySubscriptionStatusData>().Which.First().CompanySubscriptionStatuses.First().TechnicalUser.Should().Be(false);
this remark is still outstanding:
>please make sure an offerId that would return true is included in the set of offers passed as InlineData

2023-05-24 06:42 UTC, ntruchsess requested changes
please make sure the repository unit-test covers both cases (technicaluser being returned as 'true' is missing).

2023-05-25 06:58 UTC, qxz2mqe commented on tests/portalbackend/PortalBackend.DBAccess.Tests/OfferSubscriptionRepositoryTest.cs
> +            results.Data.Should().AllBeOfType<OfferCompanySubscriptionStatusData>().Which.First().CompanySubscriptionStatuses.First().TechnicalUser.Should().Be(false);
yes i tried that yesterday but it has not worked because data was not available for true condition. I think now philip has added that

2023-05-25 10:14 UTC, ntruchsess approved these changes

2023-05-25 10:15 UTC, merged