feat(user): save userid of ipd
eclipse-tractusx/portal-backend pull request #427
Opened 2024-01-23 06:46 UTC by Phil91

## Description

* save the userid for each idp for a specific the user
* add displayName to iamIdentityProvider
* return userid of an idp with the idps display name
* create new process to sync the display name of the iamIdentityProvider

## Why

to improve transparency
support the user in error cases 
allows us in future to also support "change" on the same

## Issue

N/A - Jira Refs: CPLP-3401

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-01-23 15:37 UTC, ntruchsess requested changes

2024-01-23 15:37 UTC, ntruchsess commented on src/processes/NetworkRegistration.Library/NetworkRegistrationHandler.cs
> +            userData.ProviderLinkData.Select(pld => pld.DisplayName ?? throw new UnexpectedConditionException("providerLinkData.DisplayName should never be null here"))));
as DisplayName currently is nullable on the database this is not guaranteed. A ConflictException would be appropriate in this case (or provide a reasonable fallback like company-name)

2024-01-24 08:02 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/IdentityProviderRepository.cs
> +    public IamIdentityProvider CreateIamIdentityProvider(Guid identityProviderId, string idpAlias, string displayName) =>
the problem is that runtime data can be created with a custom displayName which is set by the user via the POST: api/administration/identityprovider/owncompany/identityproviders endpoint, therefor we can't just take the company name in my opinion.

2024-01-24 08:02 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/UserRepository.cs
> +                .GroupBy(u => u.Id),
adjusted.

2024-01-24 18:22 UTC, ntruchsess approved these changes

2024-01-25 07:48 UTC, merged