feat(apps & services):- Post autosetup
eclipse-tractusx/portal-backend pull request #43
Opened 2023-05-22 10:05 UTC by qxz2mqe

## Description
Added technicalUserPermissions and clienturl in response body

## Why

to support the FE/user with additional information

## Issue

https://jira.catena-x.net/browse/CPLP-2665

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)

- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

2023-05-22 22:06 UTC, ntruchsess requested changes

2023-05-22 22:06 UTC, ntruchsess commented on src/marketplace/Offers.Library/Service/OfferSetupService.cs
> +        return (clientId, iamClient.Id, offerUrl);
What shall this be good for? there is no point in adding an unchanged parameter of a method to the return-values.

2023-05-22 22:06 UTC, ntruchsess commented on src/marketplace/Offers.Library/Service/OfferSetupService.cs
> +            var (clientId, iamClientId, clientUrl) = await CreateClient(data.OfferUrl, offerDetails.OfferId, true, userRolesRepository).ConfigureAwait(false);
clientUrl is the unchanged value of data.OfferUrl. There is no point in doing this assignment via a call to CreateClient.

2023-05-22 22:10 UTC, ntruchsess commented
> Please delete options that are not relevant.
> 
>     * [ ]  I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
> 
>     * [ ]  I have performed a self-review of my own code
> 
>     * [ ]  I have successfully tested my changes locally
> 
>     * [ ]  I have added tests that prove my changes work
> 
>     * [ ]  I have checked that new and existing tests pass locally with my changes
> 
>     * [ ]  I have commented my code, particularly in hard-to-understand areas

please make sure you mark the options that you confirm your PR does comply with. To do so replace the space enclosed by the square-brackets by the character 'X'. Like so
`* [X]  I have performed a self-review of my own code`
* [X]  I have performed a self-review of my own code
github will render this as a checked checkbox.

2023-05-25 08:40 UTC, qxz2mqe commented on src/marketplace/Offers.Library/Service/OfferSetupService.cs
> +        return (clientId, iamClient.Id, offerUrl);
fixed

2023-05-25 08:40 UTC, qxz2mqe commented on src/marketplace/Offers.Library/Service/OfferSetupService.cs
> +            var (clientId, iamClientId, clientUrl) = await CreateClient(data.OfferUrl, offerDetails.OfferId, true, userRolesRepository).ConfigureAwait(false);
fixed

2023-05-25 09:18 UTC, ntruchsess submitted a review, later dismissed

2023-05-25 09:56 UTC, ntruchsess approved these changes

2023-05-25 09:58 UTC, merged