feat(certificate): db enablement company certificates
eclipse-tractusx/portal-backend pull request #475
Opened 2024-02-01 09:00 UTC by AnuragNagpure

## Description

Enable companies to fetch their company certificates with the respective document status.

## Why

To ensure that the feature can get supported, first changes on db level are needed ++ seeding data adjustments. Tables added are mentioned below
CompanyCertificate
CompanyCertificateStatus
CompanyCertificateType
CompanyCertificateTypeDescription

## Issue

#471 

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-02-01 13:32 UTC, Phil91 requested changes
@jjeroch the implementation in this PR adds a `Id` field to the `company_certificates` table. That differentiate to the description in the issue and I couldn't find a discussion in the issue nor Jira. Main reason for that is if we don't have the field a company could only have one entry linked to company_certificate_type. Example `BMW` has an `ISO 9001`certificate which is inactive, they could never create a new one, only way to have an `ISO 9001` certificate is to update the inactive one, in my opinion we shouldn't do that, do you agree with that or should Anurag remove the Id field?

@AnuragNagpure one general thing I recognised, please use conventional commits not only for the PR title. Please use it for your commit messages as well

2024-02-01 13:32 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Migrations/20240201084412_CPLP-3642-company-certificates.Designer.cs
Please save this file as UTF-8. Currently it is saved as UTF-8 with BOM. You can do this by selecting the UTF-8 with BOM at the bottom of VS Code.

![image](https://github.com/eclipse-tractusx/portal-backend/assets/7672600/b3a221b3-b6ee-4740-abc4-fee211a8443f)

Than select the `Save with Encoding` option

![image](https://github.com/eclipse-tractusx/portal-backend/assets/7672600/8296dbb7-ee6e-40e3-b7c5-db18ff766839)

and select the `UTF-8` Encoding.

This also applies for the `PortalDbContextModelSnapshot` file

2024-02-01 13:32 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Migrations/PortalDbContextModelSnapshot.cs
> +﻿// <auto-generated />
Please readd the file header and see the comment on the file `20240201084412_CPLP-3642-company-certificates.Designer.cs`

2024-02-01 13:32 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/PortalBackend.Migrations.csproj
> +</Project>
please revert the changes in this file. seems there was nothing changed, but the empty line at the end of the file was removed.

2024-02-01 13:32 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Seeder/BatchInsertSeeder.cs
> +        await SeedTable<CompanyCertificateTypeDescription>("company_certificate_type_description", x => new { x.Id, x.ShortName, x.Description }, cancellationToken).ConfigureAwait(false);
please change the file name to `company_certificate_type_descriptions`

2024-02-01 13:32 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Seeder/Data/company_certificate_type_description.json
> +        "description": "Description will get added asap"
@jjeroch is it maybe possible to have the description before merging? If not no problem, but than we need an UpdateSeeder as well.

@AnuragNagpure /cc

2024-02-01 13:32 UTC, Phil91 commented on src/portalbackend/PortalBackend.Migrations/Seeder/Data/company_certificate_type_description.json
> +]
Please add a empty line at the end of the file

2024-02-01 13:32 UTC, Phil91 commented on src/portalbackend/PortalBackend.PortalEntities/Entities/CompanyCertificate.cs
> +
Please remove the empty line

2024-02-01 13:32 UTC, Phil91 commented on src/portalbackend/PortalBackend.PortalEntities/Entities/CompanyCertificate.cs
> +
Please remove the empty line

2024-02-01 13:32 UTC, Phil91 commented on src/portalbackend/PortalBackend.PortalEntities/Entities/CompanyCertificate.cs
> +    public Guid Id { get; set; }
please use `:this()` to call the private constructor and change the params `guid`to ìd` and `dateTimeOffset` to `validFrom` to have the constructor params matching with the properties of the entity. One general thing. Please take care of correct formatting, empty lines before curly brackets should be removed. Curly brackets should be followed by an empty line.


```suggestion
    public CompanyCertificate(Guid id, DateTimeOffset validFrom, CompanyCertificateTypeId companyCertificateTypeId, CompanyCertificateStatusId companyCertificateStatusId, Guid comapnyId, Guid documentId)
    :this()
    {
        Id = id;
        ValidFrom = validFrom;
        CompanyCertificateTypeId = companyCertificateTypeId;
        CompanyCertificateStatusId = companyCertificateStatusId;
        CompanyId = comapnyId;
        DocumentId = documentId;
    }

    public Guid Id { get; set; }
```

2024-02-01 13:32 UTC, Phil91 commented on src/portalbackend/PortalBackend.PortalEntities/Entities/CompanyCertificate.cs
> +    public DateTimeOffset ValidFrom { get; set; }
Can be changed to private set since we directly set the property in the constructor.

```suggestion
    public DateTimeOffset ValidFrom { get; private set; }
```

2024-02-01 13:32 UTC, Phil91 commented on src/portalbackend/PortalBackend.PortalEntities/Entities/CompanyCertificate.cs
> + * Copyright (c) 2021, 2023 BMW Group AG
This line can be removed

2024-02-01 13:32 UTC, Phil91 commented on src/portalbackend/PortalBackend.PortalEntities/Entities/CompanyCertificateStatus.cs
> + * Copyright (c) 2021, 2023 BMW Group AG
This line can be removed

2024-02-01 13:32 UTC, Phil91 commented on src/portalbackend/PortalBackend.PortalEntities/Entities/CompanyCertificateType.cs
> + * Copyright (c) 2021, 2023 BMW Group AG
This line can be removed

2024-02-01 13:32 UTC, Phil91 commented on src/portalbackend/PortalBackend.PortalEntities/Entities/CompanyCertificateTypeDescription.cs
> +    public CompanyCertificateTypeDescription(CompanyCertificateTypeId id, string shortName, string description)
Please use `:this()`to call the base constructor

2024-02-01 13:32 UTC, Phil91 commented on src/portalbackend/PortalBackend.PortalEntities/PortalDbContext.cs
> +using System.Runtime.CompilerServices;
Can be removed since it's unused

2024-02-02 07:37 UTC, jjeroch commented
> @jjeroch the implementation in this PR adds a `Id` field to the `company_certificates` table. That differentiate to the description in the issue and I couldn't find a discussion in the issue nor Jira. Main reason for that is if we don't have the field a company could only have one entry linked to company_certificate_type. Example `BMW` has an `ISO 9001`certificate which is inactive, they could never create a new one, only way to have an `ISO 9001` certificate is to update the inactive one, in my opinion we shouldn't do that, do you agree with that or should Anurag remove the Id field?
> 
> @AnuragNagpure one general thing I recognised, please use conventional commits not only for the PR title. Please use it for your commit messages as well

Hi @Phil91  & @AnuragNagpure  fully agree with your proposal. `BMW` must have the chance to have an `ISO 9001`certificate in status "INACTIVE" while a second is in status "ACTIVE"

2024-02-02 13:15 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.PortalEntities/PortalDbContext.cs
> +using System.Runtime.CompilerServices;
removed

2024-02-02 13:16 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.PortalEntities/Entities/CompanyCertificateType.cs
> + * Copyright (c) 2021, 2023 BMW Group AG
line removed

2024-02-02 13:16 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.PortalEntities/Entities/CompanyCertificateStatus.cs
> + * Copyright (c) 2021, 2023 BMW Group AG
line removed

2024-02-02 13:16 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.PortalEntities/Entities/CompanyCertificate.cs
> + * Copyright (c) 2021, 2023 BMW Group AG
line removed

2024-02-02 13:17 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.Migrations/Seeder/Data/company_certificate_type_description.json
> +        "description": "Description will get added asap"
script written in updateseeder file

2024-02-02 13:17 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.Migrations/Seeder/BatchInsertSeeder.cs
> +        await SeedTable<CompanyCertificateTypeDescription>("company_certificate_type_description", x => new { x.Id, x.ShortName, x.Description }, cancellationToken).ConfigureAwait(false);
changed

2024-02-02 13:17 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.Migrations/PortalBackend.Migrations.csproj
> +</Project>
reverted

2024-02-02 13:17 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.Migrations/Migrations/PortalDbContextModelSnapshot.cs
> +﻿// <auto-generated />
header added

2024-02-02 13:18 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.Migrations/Migrations/20240201084412_CPLP-3642-company-certificates.Designer.cs
changed to UTF-8

2024-02-05 20:01 UTC, jjeroch commented on src/portalbackend/PortalBackend.Migrations/Seeder/Data/company_certificate_type_description.json
> +        "description": "Description will get added asap"
@AnuragNagpure  & @Phil91  description added inside the sub-task issue https://github.com/eclipse-tractusx/portal-backend/issues/471

2024-02-06 01:44 UTC, ntruchsess approved these changes

2024-02-06 07:23 UTC, Phil91 approved these changes

2024-02-06 08:23 UTC, merged