feat(get): get company certificate types
eclipse-tractusx/portal-backend pull request #490
Opened 2024-02-07 20:01 UTC by AnuragNagpure

## Description

Static Data Endpoint to retrieve supported certificate types

## Why

Suggested API Endpoint: GET /api/administration/staticdata/certificateTypes

## Issue

#469

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-02-08 07:03 UTC, Phil91 requested changes
Please add a controller test as well

2024-02-08 07:03 UTC, Phil91 commented on src/administration/Administration.Service/Controllers/StaticDataController.cs
> +    [ProducesResponseType(typeof(IAsyncEnumerable<CompanyCertificateTypeData>), StatusCodes.Status200OK)]
Please change to IEnumerable, Swagger UI has problems with displaying IAsyncEnumerable as a ResponseType. 

```suggestion
    [ProducesResponseType(typeof(IEnumerable<CompanyCertificateTypeData>), StatusCodes.Status200OK)]
```

2024-02-08 07:03 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Models/CompanyCertificateTypeData.cs
> + * Copyright (c) 2021, 2023 Contributors to the Eclipse Foundation
Please adjust to 

```suggestion
 * Copyright (c) 2024 Contributors to the Eclipse Foundation
```

2024-02-08 07:03 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/StaticDataRepository.cs
> +                    certificate.Id.ToString(),
The CompanyCertificateId and Label are the same in this case, do we really need this?

2024-02-08 07:04 UTC, Phil91 commented
One minor thing I recognised. Please always add @ntruchsess as a Reviewer as well

2024-02-08 07:36 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.DBAccess/Repositories/StaticDataRepository.cs
> +                    certificate.Id.ToString(),
@jjeroch Do we need company_certificate_type.Id as only label is required to in frontend ?

cc @Phil91

2024-02-08 07:53 UTC, AnuragNagpure commented
> Please add a controller test as well

controller test added

2024-02-08 07:54 UTC, AnuragNagpure commented
> One minor thing I recognised. Please always add @ntruchsess as a Reviewer as well

Noted

2024-02-08 07:54 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.DBAccess/Models/CompanyCertificateTypeData.cs
> + * Copyright (c) 2021, 2023 Contributors to the Eclipse Foundation
added

2024-02-08 07:54 UTC, AnuragNagpure commented on src/administration/Administration.Service/Controllers/StaticDataController.cs
> +    [ProducesResponseType(typeof(IAsyncEnumerable<CompanyCertificateTypeData>), StatusCodes.Status200OK)]
replaced with IEnumerable

2024-02-08 07:55 UTC, Phil91 commented
I would wait for a response from Julia, but implementation wise the PR is ready to be approved and merged in my opinion

2024-02-08 08:15 UTC, ntruchsess requested changes

2024-02-08 08:15 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/StaticDataRepository.cs
> +                    (int)certificate.Id,
no cast here, please use the enum type as it is. There is no overhead. EF will query the int and pass on the enum-type.

2024-02-08 08:15 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/StaticDataRepository.cs
> +                    certificate.Label,
Label is redundant as this is defined in code being the string-value of the enum. Furthermore the controller will do the convertion to String on-the-fly, so usually one never needs to do an explicit convertion within the custom-code.

2024-02-08 10:47 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.DBAccess/Repositories/StaticDataRepository.cs
> +                    (int)certificate.Id,
Casting removed

2024-02-08 10:48 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.DBAccess/Repositories/StaticDataRepository.cs
> +                    certificate.Label,
Label field is removed as both Id and label are same

2024-02-08 10:48 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.DBAccess/Repositories/StaticDataRepository.cs
> +                    .Where(y => y.CompanyCertificateTypeId == certificate.Id)
filter with active status

2024-02-08 10:49 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.DBAccess/Models/CompanyCertificateTypeData.cs
> +public record CompanyCertificateTypeData(int companyCertificateId, string name, IEnumerable<CertificateTypeDescription> description);
companyCertificateId changed into enum type

2024-02-09 15:00 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/StaticDataRepository.cs
> +                    certificate.Id.ToString(),
I had a talk with Julia and adjusted the endpoint accodingly. We only include the enum-value being automatically translated to the string (which is the same as the label in the database).

2024-02-09 15:01 UTC, merged