feat(errorhandling): add common controller returning all errormessages
eclipse-tractusx/portal-backend pull request #494
Opened 2024-02-08 16:53 UTC by ntruchsess

## Description

Please include a summary of the change.

## Why

Please include an explanation of why this change is necessary as well as relevant motivation and context. List any dependencies that are required for this change.

## Issue

Link to Github issue.

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [ ] I have created and linked IP issues or requested their creation by a committer
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-02-09 08:35 UTC, Phil91 requested changes

2024-02-09 08:35 UTC, Phil91 commented on src/notifications/Notifications.Service/Properties/launchSettings.json
> +        "MVC_ROUTING_BASEPATH": "api/Notification",
could we please change that to lowercase, doesn't make a difference since it should be treated case insensitive but to have it similar to the other launch settings

2024-02-09 08:35 UTC, Phil91 commented on tests/shared/Tests.Shared/IntegrationTests/IntegrationTestFactory.cs
> +        Environment.SetEnvironmentVariable("MVC_ROUTING_BASEPATH", "/api/test");
Really love that we can set the urls to a specific value now!

2024-02-09 10:37 UTC, Phil91 reviewed
One thing I just noticed, since we said we want to update all packages you might revert the changes of the existing Directory.Build.props and execute the update_framework_versions.sh script

2024-02-09 11:32 UTC, ntruchsess commented on src/notifications/Notifications.Service/Properties/launchSettings.json
> +        "MVC_ROUTING_BASEPATH": "api/Notification",
changed

2024-02-10 19:05 UTC, ntruchsess commented
> One thing I just noticed, since we said we want to update all packages you might revert the changes of the existing Directory.Build.props and execute the update_framework_versions.sh script

done

2024-02-13 07:02 UTC, merged