fix(release): adjust release workflow
eclipse-tractusx/portal-backend pull request #498
Opened 2024-02-11 08:16 UTC by Phil91

## Description

do not run release workflow when a new framework version was published

## Why

When pushing a new framework tag the release workflow gets triggered which should not happen.

## Issue

Refs: CPLP-3400

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-02-12 08:23 UTC, evegufy approved these changes

2024-02-12 08:25 UTC, evegufy requested changes
Should also be added under [here](https://github.com/eclipse-tractusx/portal-backend/blob/bugfix/nuget-push/.github/workflows/release_release_candidate.yml#L26)

2024-02-13 07:22 UTC, Phil91 commented
> Should also be added under [here](https://github.com/eclipse-tractusx/portal-backend/blob/bugfix/nuget-push/.github/workflows/release_release_candidate.yml#L26)

done :)

2024-02-14 07:25 UTC, evegufy approved these changes

2024-02-14 07:27 UTC, merged