feat(document): get company certificate by document id
eclipse-tractusx/portal-backend pull request #519
Opened 2024-02-20 15:12 UTC by AnuragNagpure

## Description

Enable companies to fetch any company certificate(s) via the document ID
GET /api/administration/companydata/companyCertificates/documents/{documentId}

## Why

user can fetch documents of other companies as long as the document is "ACTIVE"
document type of the fetched document must be "Company_Certificate" (table documents.document_type)
Exception Cases / Error:
trying to fetch a document which does not exist
trying to fetch a document which is not in status "LOCKED"
trying to fetch a document of another document type

## Issue

#462 

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-02-28 07:34 UTC, Phil91 requested changes

2024-02-28 07:34 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyCertificateRepository.cs
> +                   x.DocumentStatusId == DocumentStatusId.LOCKED &&
You are selecting only locked documents, it'd be better to don't filter for the status here to or select a bool value which provides the information if the document is in status locked. if it isn't than please return a specific error message

2024-02-29 07:21 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyCertificateRepository.cs
> +                   x.DocumentStatusId == DocumentStatusId.LOCKED &&
filter for status removed and a bool check is added

2024-03-04 08:27 UTC, Phil91 requested changes

2024-03-04 08:27 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
> +            throw new ForbiddenException($"Document {documentId} status is not Locked");
please change to 
```suggestion
            throw new ForbiddenException($"Document {documentId} status is not locked");
```

2024-03-04 08:27 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
> +        if (!documentDetails.IsExists)
please rename to Exists
```suggestion
        if (!documentDetails.Exists)
```

2024-03-04 08:27 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyCertificateRepository.cs
> +            .Select(x => new ValueTuple<byte[], string, MediaTypeId, bool, bool>(x.DocumentContent, x.DocumentName, x.MediaTypeId, x.Id == documentId, x.DocumentStatusId == DocumentStatusId.LOCKED))
this can directly be set to true since we're having the filter on matching ids in the where clause. Please change to:

```suggestion
            .Select(x => new ValueTuple<byte[], string, MediaTypeId, bool, bool>(x.DocumentContent, x.DocumentName, x.MediaTypeId, true, x.DocumentStatusId == DocumentStatusId.LOCKED))
```

2024-03-04 08:27 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ICompanyCertificateRepository.cs
> +    Task<(byte[] Content, string FileName, MediaTypeId MediaTypeId, bool IsExists, bool IsStatusLocked)> GetCompanyCertificateDocumentDataAsync(Guid documentId, DocumentTypeId documentTypeId);
Please change to:

```suggestion
    Task<(byte[] Content, string FileName, MediaTypeId MediaTypeId, bool Exists, bool IsStatusLocked)> GetCompanyCertificateDocumentDataAsync(Guid documentId, DocumentTypeId documentTypeId);
```

2024-03-04 08:27 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyCertificateRepository.cs
> +    public Task<(byte[] Content, string FileName, MediaTypeId MediaTypeId, bool IsExists, bool IsStatusLocked)> GetCompanyCertificateDocumentDataAsync(Guid documentId, DocumentTypeId documentTypeId)
Please change to 
```suggestion
    public Task<(byte[] Content, string FileName, MediaTypeId MediaTypeId, bool Exists, bool IsStatusLocked)> GetCompanyCertificateDocumentDataAsync(Guid documentId, DocumentTypeId documentTypeId) =>
```

2024-03-04 08:30 UTC, Phil91 commented
@AnuragNagpure please do a rebase to the latest dev

2024-03-04 10:04 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyCertificateRepository.cs
> +    public Task<(byte[] Content, string FileName, MediaTypeId MediaTypeId, bool IsExists, bool IsStatusLocked)> GetCompanyCertificateDocumentDataAsync(Guid documentId, DocumentTypeId documentTypeId)
IsExists changed to Exists

2024-03-04 10:05 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ICompanyCertificateRepository.cs
> +    Task<(byte[] Content, string FileName, MediaTypeId MediaTypeId, bool IsExists, bool IsStatusLocked)> GetCompanyCertificateDocumentDataAsync(Guid documentId, DocumentTypeId documentTypeId);
changed required condition

2024-03-04 10:05 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyCertificateRepository.cs
> +            .Select(x => new ValueTuple<byte[], string, MediaTypeId, bool, bool>(x.DocumentContent, x.DocumentName, x.MediaTypeId, x.Id == documentId, x.DocumentStatusId == DocumentStatusId.LOCKED))
changed required condition

2024-03-04 10:06 UTC, AnuragNagpure commented on src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
> +        if (!documentDetails.IsExists)
IsExists changed to Exists

2024-03-04 10:06 UTC, AnuragNagpure commented on src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
> +            throw new ForbiddenException($"Document {documentId} status is not Locked");
changed message word

2024-03-04 10:15 UTC, Phil91 approved these changes

2024-03-04 10:16 UTC, merged