feat(logging): add structured logging
eclipse-tractusx/portal-backend pull request #52
Opened 2023-05-26 06:06 UTC by Phil91

## Description

Add structured logging to all applications.

## Why

To have better readability and searchability for grafana.

## Issue

N/A - Jira Issue: CPLP-1849

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [ ] I have created and linked IP issues or requested their creation by a committer
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

2023-06-19 13:37 UTC, Phil91 commented
The following license review requests have been created and been approved:

For nuget/nuget/-/Serilog.Settings.Configuration/3.4.0.
https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/8433.
For nuget/nuget/-/Serilog.Sinks.Console/4.1.0.
https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/8434.
For nuget/nuget/-/Serilog/2.12.0.
https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/8435.
For nuget/nuget/-/Serilog.Extensions.Hosting/5.0.1.
https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/8436.
For nuget/nuget/-/Serilog.AspNetCore/6.1.0.
https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/8437.
For nuget/nuget/-/xunit/2.4.1.
https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/8438.

2023-06-21 17:44 UTC, ntruchsess requested changes

2023-06-21 17:44 UTC, ntruchsess commented on src/framework/Framework.ErrorHandling.Web/GeneralHttpErrorHandler.cs
> +    private static readonly IReadOnlyDictionary<HttpStatusCode, MetaData> Metadata = new Dictionary<HttpStatusCode, MetaData>()
I suggest to transform the Dictionary to a really immutable object by calling .ToImmutableDictionary() (in namespace System.Collecions.Immutable) like so:
```
    private static readonly IReadOnlyDictionary<HttpStatusCode, MetaData> Metadata = new Dictionary<HttpStatusCode, MetaData>()
    {
        { HttpStatusCode.BadRequest, new MetaData("https://tools.ietf.org/html/rfc7231#section-6.5.1", "One or more validation errors occurred.") },
   ...
    }.ToImmutableDictionary();
```
(I recently did learn that just by accessing a instance of normal Dictionary by restricting to the IReadOnlyDictionary interface will not result in any benefit in terms of thread-synchronization as the underlying object is still writable. An ImmutableDictionary can be optimized by the compiler in terms of synchronization as it is guaranteed it will never change)

2023-06-21 17:44 UTC, ntruchsess commented on src/processes/Processes.Worker/Program.cs
> +    LoggingExtensions.EnsureInitialized();
shouldn't this be called before the 'try' (as in the other Program.cs)? than the consecutive calls to EnsureInitialized in Catch and Finally would be redundant, wouldn't they?

2023-06-21 17:44 UTC, ntruchsess commented on tests/shared/Tests.Shared/Extensions/HttpExtensions.cs
> +using Microsoft.AspNetCore.Http;
this using is redundant and can be removed

2023-06-21 20:39 UTC, Phil91 commented on tests/shared/Tests.Shared/Extensions/HttpExtensions.cs
> +using Microsoft.AspNetCore.Http;
removed.

2023-06-21 23:20 UTC, ntruchsess approved these changes

2023-06-21 23:23 UTC, merged