feat(companyid): get company certificate document by company userid
eclipse-tractusx/portal-backend pull request #522
Opened 2024-02-21 10:59 UTC by AnuragNagpure

## Description

Enable companies to fetch their company certificates via the document ID and company user ID
API Endpoint: GET /api/administration/companydata/companyCertificates/{documentId}

## Why

Can only fetch my companies documents
document type of the fetched document must be "Company_Certificate" (table documents.document_type)
the document status is irrelevant - reason: I am accessing my uploaded docus only; there shouldnt me any limitation on the document status

## Issue

#463 

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-02-28 08:16 UTC, Phil91 requested changes

2024-02-28 08:16 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyCertificateRepository.cs
> +               x.CompanyUserId == companyUserId &&
Please change the check to the Company of the companyUser instead of checking the companyUser directly

2024-02-28 08:16 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
> +            .GetCompanyCertificateDocumentByCompanyIdDataAsync(documentId, _identityData.IdentityId, DocumentTypeId.COMPANY_CERTIFICATE)
Please change the identityId to companyId

2024-02-28 08:16 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyCertificateRepository.cs
> +    public Task<(byte[] Content, string FileName, MediaTypeId MediaTypeId, bool IsExist)> GetCompanyCertificateDocumentByCompanyIdDataAsync(Guid documentId, Guid companyUserId, DocumentTypeId documen
Please change `IsExist` to `Exists`

2024-02-29 11:32 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyCertificateRepository.cs
> +               x.CompanyUserId == companyUserId &&
Company of companyUser check is implemented

2024-02-29 11:33 UTC, AnuragNagpure commented on src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
> +            .GetCompanyCertificateDocumentByCompanyIdDataAsync(documentId, _identityData.IdentityId, DocumentTypeId.COMPANY_CERTIFICATE)
changed to companyId

2024-03-01 10:43 UTC, Phil91 requested changes

2024-03-01 10:43 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyCertificateRepository.cs
> +        .Select(x => new ValueTuple<byte[], string, MediaTypeId, bool>(x.DocumentContent, x.DocumentName, x.MediaTypeId, x.Id == documentId))
The exists can always be set to true, no check needed because it's in the where clause.

```suggestion
        .Select(x => new ValueTuple<byte[], string, MediaTypeId, bool>(x.DocumentContent, x.DocumentName, x.MediaTypeId, true))
```

2024-03-01 10:56 UTC, Phil91 submitted a review, later dismissed

2024-03-01 10:56 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyCertificateRepository.cs
> +        .Select(x => new ValueTuple<byte[], string, MediaTypeId, bool>(x.DocumentContent, x.DocumentName, x.MediaTypeId, x.Id == documentId))
Id comparison removed and added status as true

2024-03-01 11:10 UTC, Phil91 approved these changes

2024-03-01 11:10 UTC, Phil91 submitted a review, later dismissed

2024-03-01 11:19 UTC, Phil91 submitted a review, later dismissed

2024-03-04 13:52 UTC, merged