feat(delete): delete company certificates
eclipse-tractusx/portal-backend pull request #536
Opened 2024-02-27 12:09 UTC by AnuragNagpure

## Description

DELETE Company Certificate.
 /api/administration/companydata/companyCertificate/document/{documentId}

## Why
While implementing the logic requirement mentioned below should be taken care.
When running the endpoint - first validate if the certificate is assigned to the same company_id as the acting user company_id

if yes, proceed (see below)
if no; stop and exception/error
Set the respective document inside the table portal.documents to "INACTIVE" and update the "last_date_changed" date as well as the "last_editor_id"

Afterwards set inside the table portal.company_certificates.status to "INACTIVE" 

## Issue

#467 

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-02-28 07:47 UTC, Phil91 requested changes

2024-02-28 07:47 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyCertificateRepository.cs
> +                    document.CompanyUserId == companyUserId))
With this check only the user who uploaded the certificate can delete it. Please change the check to the companyId of the CompanyUser and check with the companyID of the current logged in user.

2024-02-28 07:48 UTC, Phil91 requested changes

2024-02-28 07:48 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyCertificateRepository.cs
> +            .Select(document => ((Guid DocumentId, DocumentStatusId DocumentStatusId, Guid CompanyCertificateId, bool IsSameCompany))
```suggestion
            .Select(document => new ValueTuple<Guid, DocumentStatusId, Guid, bool>
```

2024-02-28 12:08 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyCertificateRepository.cs
> +            .Select(document => ((Guid DocumentId, DocumentStatusId DocumentStatusId, Guid CompanyCertificateId, bool IsSameCompany))
Value tuple added as per suggestion

2024-02-29 06:56 UTC, Phil91 requested changes

2024-02-29 06:56 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyCertificateRepository.cs
> +                    document.CompanyCertificates.Select(x => x.Id).SingleOrDefault(),
It seems like database wise it's possible to have multiple CompanyCertificates for one document... We should implement an error handling for the case we have multiple CompanyCertificates. With this logic when having multiple CompanyCertificates for one Document the user would receive an UnhandledServer Exception

2024-02-29 10:17 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyCertificateRepository.cs
> +                    document.CompanyCertificates.Select(x => x.Id).SingleOrDefault(),
changes for checking multiple company certificates is implemented

2024-03-01 08:52 UTC, Phil91 submitted a review, later dismissed

2024-03-01 09:01 UTC, Phil91 approved these changes

2024-03-01 09:02 UTC, merged