feat(email template): textual changes in new user external idp file
eclipse-tractusx/portal-backend pull request #537
Opened 2024-02-28 11:42 UTC by nidhigarg-bmw

## Description

Changed Filename and content change in file

## Why

Improvements

## Issue

https://github.com/eclipse-tractusx/portal-frontend/issues/476

## Checklist

Please delete options that are not relevant.

- [X] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [X] I have performed a self-review of my own code
- [X] I have successfully tested my changes locally

2024-03-05 11:29 UTC, Phil91 requested changes
A few open points:

- please change the name of the template in the `EmailTemplateType.cs` as well
- @jjeroch since we added a variable {idpAlias} we need to add the idp alias to the email process in the method `CreateOwnCompanyIdpUsersWithEmailAsync`in `UserUploadBusinessLogic`

2024-03-07 04:28 UTC, nidhigarg-bmw commented
> A few open points:
> 
> * please change the name of the template in the `EmailTemplateType.cs` as well
> * @jjeroch since we added a variable {idpAlias} we need to add the idp alias to the email process in the method `CreateOwnCompanyIdpUsersWithEmailAsync`in `UserUploadBusinessLogic`

@Phil91 Changed the filename to mentioned file as well

2024-03-15 13:24 UTC, ntruchsess approved these changes

2024-03-15 13:25 UTC, ntruchsess commented
> A few open points:
> 
>     * please change the name of the template in the `EmailTemplateType.cs` as well
> 
>     * @jjeroch since we added a variable {idpAlias} we need to add the idp alias to the email process in the method `CreateOwnCompanyIdpUsersWithEmailAsync`in `UserUploadBusinessLogic`

done

2024-03-15 13:33 UTC, Phil91 submitted a review, later dismissed

2024-03-15 17:03 UTC, ntruchsess approved these changes

2024-03-15 17:16 UTC, merged