feat(registration): post submit registration
eclipse-tractusx/portal-backend pull request #56
Opened 2023-05-30 08:25 UTC by qxz2mqe

endpoint 

## Description

validation for company , roles, documents,application status agreement and consent in endpoint api/registration/application/{applicationId}/submitRegistration

## Why

We need validation so that before submissions all the related mandatory filled should be available in database

## Issue

https://jira.catena-x.net/browse/CPLP-2736

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

2023-05-31 09:01 UTC, ntruchsess requested changes

2023-05-31 09:01 UTC, ntruchsess commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +            if (!applicationUserData.DocumentDatas.Select(x => x.TypeId).Contains(DocumentTypeId.COMMERCIAL_REGISTER_EXTRACT))
the mandatory documentTypeIds should be configurable.

2023-05-31 09:01 UTC, ntruchsess commented on tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
> +    /*[Fact]
no commented code must be left behind.

2023-06-13 09:19 UTC, ntruchsess requested changes

2023-06-13 09:19 UTC, ntruchsess commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +                throw new ControllerArgumentException($"At least one Document type Id must be COMMERCIAL_REGISTER_EXTRACT");
please refer to _settings.SubmitDocumentTypeIds instead of hardcoded literal COMMERCIAL_REGISTER_EXTRACT

2023-06-13 09:20 UTC, ntruchsess commented
please also fix failing formating check

2023-06-13 17:12 UTC, ntruchsess requested changes
I did rebase on latest dev adjusting the query and fixing the unit-tests (not the ones that are being masked as comment).
Please pull before proceeding.
don't forget to reactivate (and fix) the commented unit-tests

2023-06-13 17:12 UTC, ntruchsess commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +        if (companyApplicationDetails.CompanyData.Name is not null &&
as those 'not null' conditions are fulfilled by any whitespace-strings this condition does render below 'OrWhiteSpace'-checks obsolete.

2023-06-13 17:12 UTC, ntruchsess commented on src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +            throw new ControllerArgumentException($"Company Name must not be empty", nameof(companyApplicationDetails.CompanyData.Name));
as this is testing the database-results the appropriate exception-type is 'ConflictException'. (ControllerArgumentException is being used to indicate that arguments passed to the API are invalid)

2023-06-14 12:03 UTC, qxz2mqe commented on tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
> +    /*[Fact]
resolved

2023-06-14 14:58 UTC, ntruchsess approved these changes

2023-06-14 14:59 UTC, merged