Feature/cplp 2643 settings
eclipse-tractusx/portal-backend pull request #59
Opened 2023-05-31 11:46 UTC by Phil91

## Description

Changed the configuration validation to check IEnumerable<Enum> to only include valid enum values.
Changed configurations to remove case sensitivity

## Why

To remove one possible error when configuring the portal the case sensitivity was removed. All configuration keys are now case insensitive

## Issue

N/A - Jira Ticket: CPLP-2643, CPLP-2698

## Checklist

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

2023-06-13 20:12 UTC, ntruchsess requested changes

2023-06-13 20:12 UTC, ntruchsess commented on src/mailing/Mailing.Template/TemplateSettings.cs
> +        if (Templates.Select(x => x.Name).Distinct().Count() != Templates.Count())
=>
```if (Templates.DistinctBy(x => x.Name).Count() != Templates.Count())```
or maybe even better readable:
```if (Templates.GroupBy(x => x.Name).Any(x => x.Count() > 0))```

2023-06-13 20:12 UTC, ntruchsess commented on src/marketplace/Services.Service/ServiceSettings.cs
> +        if (settings.UploadServiceDocumentTypeIds.Select(x => x.DocumentTypeId).Distinct().Count() !=
see comment in TemplateSettings

2023-06-14 09:07 UTC, ntruchsess commented on src/mailing/Mailing.Template/TemplateSettings.cs
> +        if (Templates.Select(x => x.Name).Distinct().Count() != Templates.Count())
I going to add extension-Methods to the framework to the framework that solves this duplication-detection in a most efficient and generic way. Will have a signature like:
```
IEnumerable<T>.Duplicates(this IEnumerable<T>, IEnumerable<T>)
IEnumerable<T>.DuplicatesBy(this IEnumerable<T>, Func<T,S>, IEnumerable<T>)
```
to be used this way:
```
if (values.DuplicatesBy(x => x.Key).Any()) {...}
```
stay tuned ;-)

2023-06-14 10:00 UTC, ntruchsess commented on src/mailing/Mailing.Template/TemplateSettings.cs
> +        if (Templates.Select(x => x.Name).Distinct().Count() != Templates.Count())
@Phil91 : see https://github.com/eclipse-tractusx/portal-backend/pull/59/commits/1d41118e4d9bf163a12f75ad91bb66ce5c1b8b74

2023-06-14 10:10 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/InvitationBusinessLogic.cs
> +            roleDatas = await _userProvisioningService.GetRoleDatas(_settings.InvitedUserInitialRoles.ToDictionary(x => x.ClientId, x => x.UserRoleNames)).ToListAsync().ConfigureAwait(false);
changed

2023-06-14 10:10 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
> +            .GetUserRoleIdsUntrackedAsync(_settings.UserAdminRoles.ToDictionary(x => x.ClientId, x => x.UserRoleNames)).ToListAsync().ConfigureAwait(false);
changed

2023-06-14 10:10 UTC, Phil91 commented on src/framework/Framework.Models/Validation/SettingValidation.cs
> +        optionsBuilder.Services.AddSingleton<IValidateOptions<TOptions>>(new EnumEnumerableValidation<TOptions>(optionsBuilder.Name, section));
agree, i did change it to transient

2023-06-14 10:11 UTC, Phil91 commented on src/mailing/Mailing.Template/TemplateSettings.cs
> +        if (Templates.Select(x => x.Name).Distinct().Count() != Templates.Count())
thanks :) have added the new extension check

2023-06-16 18:45 UTC, ntruchsess approved these changes

2023-06-19 07:49 UTC, merged