fix: fixed isOwner filter
eclipse-tractusx/portal-backend pull request #597
Opened 2024-04-03 06:19 UTC by VPrasannaK94

## Description

fixed isOwner filter

## Why

when hitting GET: api/administration/serviceaccount/owncompany/serviceaccounts with isOwner flag as true it results
companyServiceAccountTypeIds as Managed Type records instead of showing only Own Type records, now it is fixed by adding additional check condition

## Issue

Ref : #563

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-04-03 07:13 UTC, ntruchsess approved these changes

2024-04-04 15:40 UTC, ntruchsess requested changes
As the ticket is not very clear about the expected semantics I did discuss with @jjeroch . We decided to put this PR on hold and check the semantics of view company_linked_service_account first.

2024-04-07 11:18 UTC, jjeroch commented
@ntruchsess  thanks.
I have validated the details and added the actual needed change in the ticket https://github.com/eclipse-tractusx/portal-backend/issues/563

2024-04-09 07:43 UTC, ntruchsess approved these changes

2024-04-26 09:12 UTC, closed without merging