fix: changed invitation processStepType order
eclipse-tractusx/portal-backend pull request #608
Opened 2024-04-05 06:31 UTC by VPrasannaK94

## Description

changed invitation processStepType order

## Why

to fix the invitation process work flow , changed the inviation processStepType execution order

## Issue

Ref : #579 

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-04-05 11:34 UTC, Phil91 submitted a review, later dismissed

2024-04-15 14:00 UTC, ntruchsess requested changes

2024-04-15 14:00 UTC, ntruchsess commented on src/portalbackend/PortalBackend.Migrations/Migrations/20240405044548_issue579-InvitationProcessStepTypes.Designer.cs
> +                .HasAnnotation("ProductVersion", "7.0.13")
incorrect tool version used. Must be dotnet 8 sdk

2024-04-15 14:00 UTC, ntruchsess commented on src/portalbackend/PortalBackend.Migrations/Migrations/20240405044548_issue579-InvitationProcessStepTypes.cs
> +                WITH retrigger_invitation_create_database_idp As(SELECT DISTINCT id from portal.process_steps where process_step_type_id = 420)
this ain't work for two reasons:

 - the data has been deleted before. (see line 34)
 - if it weren't deleted it would mix with existing 419 entries and be updated again with subsequent sql-statement. (see line 154)
 
subsequent sql-statements have equivalent issues

I suggest the following order of execution:

delete where 421
update 405 -> 421
update 402 -> 405
update 403 -> 402
update 421 -> 403
delete where 410
update 411 -> 410
update 412 -> 411
update 414 -> 412
update 415 -> 414
update 413 -> 415
update 416 -> 413
update 417 -> 416
update 418 -> 417
update 419 -> 418
update 420 -> 419

all to be done before data from portal.process_step_types is being deleted.

(in down() this must be done in reverse order)

also a simple 'UPDATE portal.process_steps SET process_step_type_id = xx WHERE process_step_type_id = yy' would do, the sql 'WITH' is unnecessary hard to understand

2024-04-15 14:34 UTC, merged