fix: Company Registration - Retrieve CompanyUniqueIdData
eclipse-tractusx/portal-backend pull request #609
Opened 2024-04-05 15:24 UTC by drhansbeck

## Description
Revert accidental change introduced from 1.6 -> 1.7. 
To GetCompanyWithAddressAsync: 
 * Use identifier.Value instead of repeating its type. 
 * Use CompanyUniqueIdData instead of UniqueIdentifierData 
Resolves issue with displaying identifier in /applicationrequests

Also extended tests. 

## Why
Frontend was not showing company identifier data in registration process due to this backend issue. See #606. 

## Issue
Closes #606 

## Checklist

Please delete options that are not relevant.
- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have not added or updated 3rd party libraries
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally and in Cofinity-X environments
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes

2024-04-05 16:05 UTC, drhansbeck commented
Hi @stephanbcbauer , @jjeroch ,

Can you maybe help with ECA here? 

https://accounts.eclipse.org/users/typecastcloud contributed to this PR. Their eclipse account email is 150006841+typecastcloud@users.noreply.github.com and ECA is signed. Still the checks here fail. Is there maybe sth wrong in the check with the 150006841+typecastcloud email format?? 

Best,
Hans

2024-04-08 07:27 UTC, evegufy commented
> Hi @stephanbcbauer , @jjeroch ,
> 
> Can you maybe help with ECA here?
> 
> https://accounts.eclipse.org/users/typecastcloud contributed to this PR. Their eclipse account email is [150006841+typecastcloud@users.noreply.github.com](mailto:150006841+typecastcloud@users.noreply.github.com) and ECA is signed. Still the checks here fail. Is there maybe sth wrong in the check with the 150006841+typecastcloud email format??
> 
> edit: https://bugs.eclipse.org/bugs/show_bug.cgi?id=517749 - thanks @typecastcloud for digging up this conversation. Anyone in Tractus-X experience with "share their Github ID with us"?
> 
> Best, Hans

Hi @drhansbeck,

the ECA signing check is successful by now. I assume @typecastcloud did add his GH account to his Eclipse account and that solved the issue.

2024-04-08 07:35 UTC, typecastcloud commented
> > Hi @stephanbcbauer , @jjeroch ,
> > Can you maybe help with ECA here?
> > https://accounts.eclipse.org/users/typecastcloud contributed to this PR. Their eclipse account email is [150006841+typecastcloud@users.noreply.github.com](mailto:150006841+typecastcloud@users.noreply.github.com) and ECA is signed. Still the checks here fail. Is there maybe sth wrong in the check with the 150006841+typecastcloud email format??
> > edit: https://bugs.eclipse.org/bugs/show_bug.cgi?id=517749 - thanks @typecastcloud for digging up this conversation. Anyone in Tractus-X experience with "share their Github ID with us"?
> > Best, Hans
> 
> Hi @drhansbeck,
> 
> the ECA signing check is successful by now. I assume @typecastcloud did add his GH account to his Eclipse account and that solved the issue.

It just took some time to fully onboard me (I guess). It didn't work for some time after adding the GitHub email. Thanks for the help.

Please tell us if we should add/fix something in the PR.

2024-04-08 15:27 UTC, ntruchsess requested changes
Thank you very much for your contribution. As we do development and bugfixing in branch dev this PR cannot be merged into main without causing additional efforts in backporting to dev. I therefore did rebase your commits on dev and created new PR https://github.com/eclipse-tractusx/portal-backend/pull/612 for target-branch. As long you don't want to add further commits to this PR you do not need to take further action.

2024-04-08 16:17 UTC, drhansbeck commented
Excellent, thanks @ntruchsess ! 
Let me close this PR and work continues in #612 .

2024-04-08 16:17 UTC, closed without merging