feat(connectors):- Delete Connector
eclipse-tractusx/portal-backend pull request #67
Opened 2023-06-07 06:26 UTC by qxz2mqe

## Description
Delete connector for scenarios like when daps,DS and statusid flag are false, true and active pending etc

## Why

For connector registrations where the daps registration was unsuccessful, the deletion is currently blocked.

## Issue
https://jira.catena-x.net/browse/CPLP-2780

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)

- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

2023-06-08 22:39 UTC, jjeroch requested changes

2023-06-08 22:39 UTC, jjeroch commented on src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
> -            throw new ConflictException("INACTIVE Connector can not be deleted");
@qxz2mqe is this exception now fully gone? I would still expect the exception to be thrown, in case the connector send for deletion is already in Status "INACTIVE"

2023-06-09 05:26 UTC, qxz2mqe commented on src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
> -            throw new ConflictException("INACTIVE Connector can not be deleted");
Julia this condition will not be met now because we have already added the condition that connector statusid is actve then only execute the existing implementation. i.e DAPS=true, SD=false and 
connector status = ACTIVE

2023-06-12 06:28 UTC, jjeroch commented on src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
> -            throw new ConflictException("INACTIVE Connector can not be deleted");
So what happens if the endpoint is getting triggered by an user where the connector has the status "INACTIVE"?

2023-06-12 06:33 UTC, qxz2mqe commented on src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
> -            throw new ConflictException("INACTIVE Connector can not be deleted");
In that case it will throw  throw new ConflictException($"Connector status does not match a deletion scenario. Deletion declined");

2023-06-12 09:19 UTC, jjeroch commented on src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
> -            throw new ConflictException("INACTIVE Connector can not be deleted");
ok thats fine.
@qxz2mqe you can make this more transparent in future, if you add such information in your first feedback (the feedback which you added three days ago). You can just state more details such as:
`"the error scenario "throw new ConflictException("INACTIVE Connector can not be deleted")" is already covered by the newly added exception "throw new ConflictException($"Connector status does not match a deletion scenario. Deletion declined")" `
That would make it directly transparent

2023-06-13 08:01 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
> +        if (SelfDescriptionDocumentid != null)
define selfDescriptionDocumentId as being non-nullable in the methods signature. That allows to remove this non-null check. The only place where this method is being called does validate it's non null before the call.

2023-06-13 08:05 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
> +                a => { a.DocumentStatusId = DocumentStatus!.Value; },
technically it's incorrect to use the !-operator here as there is no validation documentStatus is actually non-null. Please define documentStatus as non-nullable in the method signature and implement the required handling of null value in the calling code. I suggest to throw UnexpectedConditionException in case documentStatus is null while selfDesctiptionDocumentId is non-null. (If this ever happens it means either there is a bug in the query or the database-scheme had changed such that the query is no longer valid and needs to be adjusted).

2023-06-13 08:27 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
> +    private async Task DeleteUpdateConnectorDetail(Guid connectorId, string iamUserId, CancellationToken cancellationToken, string? DapsClientId, IConnectorsRepository connectorsRepository)
DapsClientId -> lowerCase

2023-06-13 12:51 UTC, qxz2mqe commented on src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
> +    private async Task DeleteConnector(Guid connectorId, string iamUserId, CancellationToken cancellationToken, string? DapsClientId, Guid? SelfDescriptionDocumentid, DocumentStatusId? DocumentStatus
resolved

2023-06-13 12:51 UTC, qxz2mqe commented on src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
> +        if (SelfDescriptionDocumentid != null)
resolved

2023-06-13 12:51 UTC, qxz2mqe commented on src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
> +                a => { a.DocumentStatusId = DocumentStatus!.Value; },
resolved

2023-06-13 12:51 UTC, qxz2mqe commented on src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
> +    private async Task DeleteUpdateConnectorDetail(Guid connectorId, string iamUserId, CancellationToken cancellationToken, string? DapsClientId, IConnectorsRepository connectorsRepository)
resolved

2023-06-13 18:48 UTC, ntruchsess approved these changes

2023-06-13 18:53 UTC, ntruchsess commented
@Phil91 : I did rebase on latest dev. Can you please double check both my and @qxz2mqe 's changes

2023-06-14 06:58 UTC, Phil91 requested changes
one minor cosmetic finding

2023-06-14 06:58 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
> +        _portalRepositories.GetInstance<IDocumentRepository>().RemoveDocument(selfDescriptionDocumentId!);
The `!` can be removed since the parameter isn't nullable

```suggestion
        _portalRepositories.GetInstance<IDocumentRepository>().RemoveDocument(selfDescriptionDocumentId);
```

2023-06-14 08:10 UTC, merged