fix(technicalUser): adjust dim technical user creation
eclipse-tractusx/portal-backend pull request #684
Opened 2024-04-25 09:31 UTC by Phil91

## Description

* adjust technical user process
* adjust authorisation policy type

## Why

To have a running service account creation process for dim users

## Issue

N/A

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-04-25 10:11 UTC, evegufy requested changes

2024-04-25 10:11 UTC, evegufy commented on src/portalbackend/PortalBackend.DBAccess/Models/SubscriptionData.cs
> + * Copyright (c) 2021, 2023 Contributors to the Eclipse Foundation
outdated year in header

2024-04-25 10:11 UTC, evegufy commented on src/portalbackend/PortalBackend.DBAccess/Models/ServiceAccountData.cs
> + * Copyright (c) 2021, 2023 Contributors to the Eclipse Foundation
outdated year in header

2024-04-26 07:28 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Models/SubscriptionData.cs
> + * Copyright (c) 2021, 2023 Contributors to the Eclipse Foundation
adjusted

2024-04-26 08:51 UTC, evegufy approved these changes

2024-04-26 08:55 UTC, merged