Feat(serviceaccount):- get owencompany service accounts
eclipse-tractusx/portal-backend pull request #72
Opened 2023-06-12 09:40 UTC by qxz2mqe

## Description

Add offer and connector data in response body of  technicaluser endpoint
## Why

Enahnce the existing endpoint to know whether service account has offer and connector data or not

## Issue

https://jira.catena-x.net/browse/CPLP-2785

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes

2023-06-13 20:55 UTC, ntruchsess requested changes
I did rebase on dev, please pull before proceeding.

2023-06-13 20:55 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
> +            result.ConnectorData!,
this is just wrong - please understand you must not use the !-operator if there is no guarantee the operand is actually non-null. Either declare CompanyServiceAccountDetailedData.Connector as nullable or add a check like
```if(result.ConnectorData == null) throw ConflictException($"serviceAccount {serviceAccountId} is not associated with any connector");```

2023-06-13 20:55 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
> +            result.OfferSubscroiptionsData!,
- !-operator: see before.
- OfferSubscroiptionsData => OfferSubscriptionData (typo)

2023-06-13 20:55 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Models/CompanyServiceAccountData.cs
> +    [property: JsonPropertyName("offer")] OfferResponseData? OfferSubscroiptionsData
OfferSubscroiptionsData => OfferSubscriptionData (typo)

2023-06-13 20:55 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Models/CompanyServiceAccountDetailedData.cs
> +    OfferResponseData? OfferSubscroiptionsData);
OfferSubscroiptionsData => OfferSubscriptionData (typo)

2023-06-13 20:55 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ServiceAccountRepository.cs
> +                    (serviceAccount!.OfferSubscription == null) ? null : new OfferResponseData(serviceAccount.OfferSubscription!.OfferId, serviceAccount.OfferSubscription!.Offer!.OfferTypeId, service
as before: any use of !-operator where it is not 100% guaranteed the operand is non-null at runtime is strictly forbidden.
Offer.Name is declared as nullable,
the result of the selection serviceAccount.OfferSubscription!.Offer!.Name therefore can be null at runtime. Just because the database would return null if the respective column is null. You cannot change or override this by suppressing the compiletime-warning.

2023-06-13 20:55 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ServiceAccountRepository.cs
> +                        (serviceAccount!.OfferSubscription == null) ? null : new OfferResponseData(serviceAccount.OfferSubscription!.OfferId, serviceAccount.OfferSubscription!.Offer!.OfferTypeId, ser
same as before: serviceAccount.OfferSubscription!.Offer!.Name can be null at runtime

2023-06-15 05:38 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ServiceAccountRepository.cs
> +                        (serviceAccount!.OfferSubscription == null) ? null : new OfferResponseData(serviceAccount.OfferSubscription!.OfferId, serviceAccount.OfferSubscription!.Offer!.OfferTypeId, ser
resolved

2023-06-15 05:39 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ServiceAccountRepository.cs
> +                    (serviceAccount!.OfferSubscription == null) ? null : new OfferResponseData(serviceAccount.OfferSubscription!.OfferId, serviceAccount.OfferSubscription!.Offer!.OfferTypeId, service
resolved

2023-06-15 05:39 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.DBAccess/Models/CompanyServiceAccountDetailedData.cs
> +    OfferResponseData? OfferSubscroiptionsData);
resolved

2023-06-15 05:39 UTC, qxz2mqe commented on src/portalbackend/PortalBackend.DBAccess/Models/CompanyServiceAccountData.cs
> +    [property: JsonPropertyName("offer")] OfferResponseData? OfferSubscroiptionsData
resolved

2023-06-15 05:39 UTC, qxz2mqe commented on src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
> +            result.OfferSubscroiptionsData!,
resolved

2023-06-15 05:39 UTC, qxz2mqe commented on src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
> +            result.ConnectorData!,
resolved

2023-06-15 07:35 UTC, ntruchsess approved these changes

2023-06-15 07:46 UTC, merged