chore: fix code quality findings
eclipse-tractusx/portal-backend pull request #786
Opened 2024-06-05 10:52 UTC by ntruchsess

## Description

Please include a summary of the change.

## Why

Please include an explanation of why this change is necessary as well as relevant motivation and context. List any dependencies that are required for this change.

#694

Link to Github issue.

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [ ] I have created and linked IP issues or requested their creation by a committer
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-06-14 17:11 UTC, Phil91 approved these changes

2024-06-14 17:18 UTC, evegufy requested changes
LGTM in general but dependencies file needs to get updated

2024-06-17 07:17 UTC, ntruchsess commented
> LGTM in general but dependencies file needs to get update
in fact the artifact attachted to that action contains an empty DEPENDENCIES file. Looks as if something went wrong here. Re-running the action was successful though.

2024-06-17 07:21 UTC, evegufy approved these changes

2024-06-17 07:55 UTC, merged