feat(technicalUser): adjust technical user to delete dim users
eclipse-tractusx/portal-backend pull request #804
Opened 2024-06-24 08:40 UTC by Phil91

## Description

adjust technical user delete to support deletion of dim users

## Why

To support the deletion of dim technical users

## Issue

N/A

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-06-27 21:10 UTC, ntruchsess requested changes

2024-06-27 21:10 UTC, ntruchsess commented on src/processes/DimUserProcess.Executor/DimUserBaseProcessTypeExecutor.cs
> +        [ProcessStepTypeId.CREATE_DIM_TECHNICAL_USER] :
is there any good reason to choose such a complicated design (having a shared base-class for to different process-types ?)

2024-06-28 07:24 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
> +            var process = processStepRepository.CreateProcess(ProcessTypeId.DELETE_DIM_TECHNICAL_USER);
adjusted to take the creation process

2024-06-28 07:24 UTC, Phil91 commented on src/processes/DimUserProcess.Executor/DimUserBaseProcessTypeExecutor.cs
> +    ProcessTypeId processTypeId)
removed the base implementation and aligned the process into one

2024-06-28 07:24 UTC, Phil91 commented on src/processes/DimUserProcess.Executor/DimUserBaseProcessTypeExecutor.cs
> +#pragma warning disable IDE0060
removed the base implementation and aligned the process into one

2024-06-28 07:24 UTC, Phil91 commented on src/portalbackend/PortalBackend.PortalEntities/Enums/ProcessTypeId.cs
> +    DELETE_DIM_TECHNICAL_USER = 10
removed

2024-06-28 07:25 UTC, Phil91 commented on src/processes/DimUserProcess.Executor/DimUserBaseProcessTypeExecutor.cs
> +        [ProcessStepTypeId.CREATE_DIM_TECHNICAL_USER] :
sometimes you don't see the woods because of all the trees :wink: simplified it :)

2024-07-19 17:19 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
> +                portalRepositories, () => $"externalId {result.ProcessId.Value}");
fixed

2024-07-19 17:20 UTC, ntruchsess commented on tests/administration/Administration.Service.Tests/BusinessLogic/ServiceAccountBusinessLogicTests.cs
> +        };
fixed

2024-07-22 07:27 UTC, evegufy requested changes
change is not going into the 2.1.0 version anymore, please change base branch to main

2024-07-26 10:50 UTC, Phil91 commented
> change is not going into the 2.1.0 version anymore, please change base branch to main

branch adjusted and rebase done

2024-08-02 07:58 UTC, ntruchsess commented
> change is not going into the 2.1.0 version anymore, please change base branch to main

done

2024-08-02 10:36 UTC, ntruchsess submitted a review, later dismissed

2024-08-02 11:30 UTC, ntruchsess approved these changes

2024-08-05 11:20 UTC, ntruchsess approved these changes

2024-08-05 11:26 UTC, merged