feat(clearinghouse): add comments to process step and application checklist
eclipse-tractusx/portal-backend pull request #847
Opened 2024-07-18 13:25 UTC by Phil91

## Description

enhance application checklist with a comment of the skipped self description step

## Why

To give the user an overview why the step was skipped

## Issue

Refs: #837

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-07-25 17:07 UTC, evegufy reviewed
Please change to main branch, milestone was already adjusted

2024-07-26 09:06 UTC, Phil91 commented
> Please change to main branch, milestone was already adjusted

rebase to main done.

2024-08-05 17:11 UTC, evegufy approved these changes

2024-08-05 17:11 UTC, evegufy commented
@Phil91 I noticed that a conflict needs to get resolved

2024-08-06 07:53 UTC, Phil91 commented
> @Phil91 I noticed that a conflict needs to get resolved

@evegufy conflict is resolved :)

2024-08-06 14:57 UTC, evegufy requested changes

2024-08-06 14:57 UTC, evegufy commented on src/administration/Administration.Service/appsettings.json
> +    "ClearinghouseConnectDisabled": false
as you added the value in the administration service here, does it make sense to also add it to the processes worker?: https://github.com/eclipse-tractusx/portal-backend/blob/v2.1.0-RC2/src/processes/Processes.Worker/appsettings.json#L326
issue https://github.com/eclipse-tractusx/portal-backend/issues/888

2024-08-06 15:02 UTC, Phil91 commented on src/administration/Administration.Service/appsettings.json
> +    "ClearinghouseConnectDisabled": false
added

2024-08-06 15:11 UTC, evegufy commented on src/administration/Administration.Service/appsettings.json
> +    "ClearinghouseConnectDisabled": false
@Phil91 could you please also add it under ApplicationChecklist__SdFactory?
https://github.com/eclipse-tractusx/portal/blob/b5caed1cc33aefadc33c9c634b6b700f239be35b/charts/portal/templates/deployment-backend-administration.yaml#L179

2024-08-06 15:20 UTC, ntruchsess approved these changes

2024-08-06 15:57 UTC, Phil91 commented on src/administration/Administration.Service/appsettings.json
> +    "ClearinghouseConnectDisabled": false
I've added it: https://github.com/eclipse-tractusx/portal-backend/blob/51834cb2977be614b125748bfaffa589f971420c/src/administration/Administration.Service/appsettings.json#L321 or am I missing something?

2024-08-07 07:05 UTC, evegufy approved these changes

2024-08-07 07:07 UTC, merged