feat(apps):-get active subscription details
eclipse-tractusx/portal-backend pull request #85
Opened 2023-06-16 14:41 UTC by qxz2mqe

## Description

Add Tenant URl in response body of endpoint apps/{appId}/subscription/{subscriptionId}/provider

## Why

To add URl for appsubscription in front end.

## Issue

https://jira.catena-x.net/browse/CPLP-2492

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

2023-06-19 08:07 UTC, Phil91 requested changes

2023-06-19 08:07 UTC, Phil91 commented on tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
>      [Theory]
This can be a Fact instead of a Theory since you only have one specific case (OfferTypeId.SERVICE) you want to test.
Please adjust the following methods as well

2023-06-19 08:07 UTC, Phil91 commented on tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
> +    #region GetAppSubscriptionDetailForProvider
This can be a Fact instead of a Theory since you only have one specific case (OfferTypeId.APP) you want to test.
Please adjust the following methods as well

2023-06-19 10:03 UTC, qxz2mqe commented on tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
> +    #region GetAppSubscriptionDetailForProvider
fixed

2023-06-19 10:04 UTC, qxz2mqe commented on tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
>      [Theory]
fixed

2023-06-19 16:42 UTC, Phil91 approved these changes
lgtm

2023-06-20 20:05 UTC, ntruchsess approved these changes

2023-06-20 20:06 UTC, Phil91 approved these changes
Other than a small question, cosmetic thing, I really like the implementation!

2023-06-20 20:06 UTC, Phil91 commented on src/marketplace/Offers.Library/Service/OfferService.cs
> +    private async Task<R> GetOfferSubscriptionDetailsInternal<R>(Guid offerId, Guid subscriptionId, Guid companyId,
Is there a reason why the generic parameter is R? Just a personal favor to use T, since most MS framework code uses T for the first parameter

2023-06-20 20:07 UTC, merged