fix(OSP Invite): Handle theme for shared realm
eclipse-tractusx/portal-backend pull request #852
Opened 2024-07-19 11:09 UTC by dhiren-singh-007

## Description

Added a model to get the Identity provider type
Modified the `GetCompanyAndApplicationDetailsForApprovalAsync` method to get Identity provider type 
Added condition on setting up shared theme for shared IDP only

## Why

Earlier if we use Managed idp(eg using Azure AD) then application activation was failing because code was trying to set theme on shared realm, which don't exist.

## Issue

[Issue 848](https://github.com/eclipse-tractusx/portal-backend/issues/848)

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have checked that new and existing tests pass locally with my changes

2024-07-29 10:45 UTC, evegufy requested changes
v2.1.0 is closed (for everything more than a typo ;)), please change to main

2024-07-31 20:49 UTC, Phil91 requested changes

2024-07-31 20:49 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Models/IdentityProvider.cs
> + * Copyright (c) 2022 Contributors to the Eclipse Foundation
Please remove this line and change the copyright year to the current year.

```suggestion
 * Copyright (c) 2024 Contributors to the Eclipse Foundation
```

2024-07-31 20:49 UTC, Phil91 commented on src/registration/ApplicationActivation.Library/ApplicationActivationService.cs
> +        foreach (var iamIdp in iamIdps)
please change to and remove the if statement
```suggestion
        foreach (var iamIdp in iamIdps.Where(i => i.IdentityProviderType == IdentityProviderTypeId.SHARED))
```

2024-08-02 14:02 UTC, typecastcloud commented
@Phil91 @ntruchsess @MaximilianHauer

This is also a breaking issue for OSP. Only keycloak as idp worked for us.

We tested with Azure Entra and it tries to set theme, which it is not able to do.

Was this setting the theme of the OSP keycloak client before? Might also not be a good idea to overwrite OSP themes.

2024-08-05 07:34 UTC, Phil91 approved these changes

2024-08-05 08:07 UTC, evegufy commented
Hi @dhiren-singh-007 thank you for the contribution!
@ntruchsess could you please review as well?

2024-08-06 09:21 UTC, Phil91 submitted a review, later dismissed

2024-08-08 11:49 UTC, Phil91 requested changes

2024-08-08 11:49 UTC, Phil91 commented on src/registration/ApplicationActivation.Library/ApplicationActivationService.cs
> +        var (companyId, companyName, businessPartnerNumber, iamIdp, applicationTypeId, networkRegistrationProcessId) = result;
please change to iamIdps since it's an enumerable

```suggestion
        var (companyId, companyName, businessPartnerNumber, iamIdps, applicationTypeId, networkRegistrationProcessId) = result;
```

2024-08-08 13:00 UTC, Phil91 approved these changes

2024-08-13 12:20 UTC, ntruchsess requested changes

2024-08-13 12:20 UTC, ntruchsess commented on src/registration/ApplicationActivation.Library/ApplicationActivationService.cs
> +        foreach (var iamIdp in iamIdps.Where(i => i.IdentityProviderType == IdentityProviderTypeId.SHARED))
please revert this method-change: as the aliases are not used for anything else the Where-condition should be executed on the database

2024-08-13 12:20 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
> +    public Task<(Guid CompanyId, string CompanyName, string? BusinessPartnerNumber, IEnumerable<IdentityProviderForTheme> IamIdps, CompanyApplicationTypeId ApplicationTypeId, Guid? NetworkRegistratio
```suggestion
public Task<(Guid CompanyId, string CompanyName, string? BusinessPartnerNumber, IEnumerable<string> SharedIdpAliase, CompanyApplicationTypeId ApplicationTypeId, Guid? NetworkRegistrationProcessId)> GetCompanyAndApplicationDetailsForApprovalAsync(Guid applicationId) =>
```

2024-08-13 12:20 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
> +            .Select(ca => new ValueTuple<Guid, string, string?, IEnumerable<IdentityProviderForTheme>, CompanyApplicationTypeId, Guid?>(
```suggestion
            .Select(ca => new ValueTuple<Guid, string, string?, IEnumerable<string>, CompanyApplicationTypeId, Guid?>(
```

2024-08-13 12:20 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
> +                ca.Company.IdentityProviders.Select(x => new IdentityProviderForTheme(x.IamIdentityProvider!.IamIdpAlias, x.IamIdentityProvider!.IdentityProvider!.IdentityProviderTypeId)),
as the aliases are only used to set the valid shared idp themes the selection of aliases should be restricted to precisely those:
```suggestion
                ca.Company.IdentityProviders.Where(x => x.IdentityProviderTypeId == IdentityProviderTypeId.SHARED && x.IamIdentityProvider != null).Select(x => x.IamIdentityProvider!.IamIdpAlias),

```

2024-08-13 12:20 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Models/IdentityProvider.cs
> +/********************************************************************************
delete this file

2024-08-13 12:20 UTC, ntruchsess commented on src/registration/ApplicationActivation.Library/ApplicationActivationService.cs
> +        var (companyId, companyName, businessPartnerNumber, iamIdps, applicationTypeId, networkRegistrationProcessId) = result;
```suggestion
        var (companyId, companyName, businessPartnerNumber, sharedIdpAliase, applicationTypeId, networkRegistrationProcessId) = result;
```

2024-08-13 12:20 UTC, ntruchsess commented on src/registration/ApplicationActivation.Library/ApplicationActivationService.cs
> +        await SetTheme(iamIdps).ConfigureAwait(ConfigureAwaitOptions.None);
```suggestion
        await SetTheme(sharedIdpAliase).ConfigureAwait(ConfigureAwaitOptions.None);
```

2024-08-13 15:20 UTC, dhiren-singh-007 commented
Thanks @ntruchsess for the suggestion and giving more insights . I reverted all the commits and implemented the suggestion . Please re-review .

2024-08-14 07:37 UTC, ntruchsess approved these changes

2024-08-14 07:55 UTC, evegufy approved these changes

2024-08-14 07:56 UTC, Phil91 approved these changes

2024-08-14 07:57 UTC, merged