feat(legal entity): extended legal entity length
eclipse-tractusx/portal-backend pull request #860
Opened 2024-07-23 07:42 UTC by typecastcloud

## Description

BE adjustment for: [portal-frontend-registration:216](https://github.com/eclipse-tractusx/portal-frontend-registration/pull/216)

Extended pattern with additional currency characters and length adjustment.

Min length: 1
Max lenth: 160

Allows " (double quote \x22) to follow back-end implementation.
Allows £$€¥¢ to allow some additional currency symbols that are used in existing companies.

## Why

Much longer company names exist than currently allowed.

Example:
https://find-and-update.company-information.service.gov.uk/company/03249311 
88 characters

## Issue

Refs: eclipse-tractusx/portal#360

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-07-23 07:46 UTC, typecastcloud commented
TODO:
- Tests are missing
- Check with @Phil91 or @ntruchsess if central error messages should be done in a different way.

2024-07-23 14:47 UTC, evegufy submitted a review, later dismissed
@typecastcloud thank you for the contribution!
2.1.0 is closed for feature changes, could you please rebase to main?

2024-07-26 06:23 UTC, Phil91 requested changes
Besides my nuget package comment no further changes are required in my opinion.

2024-07-26 06:23 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
> +            throw new ControllerArgumentException($"Issuer: {ValidationExpressionErrorMessages.CompanyError}", nameof(data.Issuer));
Rather optional, but currently we're switching to translatable error messages. If you like to you could introduce them here as well.

As a reference you could have a look at:

[ControllerArgumentException](https://github.com/eclipse-tractusx/portal-backend/blob/53a4369ad1e25dd2d313353c7f95f2b9ffb399be/src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs#L180)

it's also totally fine to keep it like that as well

2024-07-26 06:23 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/InvitationBusinessLogic.cs
> +            throw new ControllerArgumentException($"OrganisationName: {ValidationExpressionErrorMessages.CompanyError}", "organisationName");
same as above, could be changed to the new exception logic:

[ControllerArgumentException](https://github.com/eclipse-tractusx/portal-backend/blob/53a4369ad1e25dd2d313353c7f95f2b9ffb399be/src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs#L180)

2024-07-26 06:23 UTC, Phil91 commented on src/framework/Framework.Models/Directory.Build.props
> +    <VersionPrefix>2.4.1</VersionPrefix>
when updating a framework package please make sure to use the [update_framework_versions.sh](https://github.com/eclipse-tractusx/portal-backend/blob/main/scripts/update_framework_versions.sh). more information can be found here https://github.com/eclipse-tractusx/portal-backend/blob/main/docs/nuget/update-nuget-packages.md

we're currently updating all nuget package versions even if only one changed because of the dependencies which must be updated as well. E.g. all packages which have Framework.Models as dependency have to be updated to don't have a mismatch, and packages with those as dependencies need to be updated as well and so on. therefor we decided to just update all packages for now.

2024-07-26 13:19 UTC, dhiren-singh-007 commented
> Besides my nuget package comment no further changes are required in my opinion.

Thanks @Phil91 for your review and suggestions.
I also think that it is good to change exception message with the new approach so I have changed my code accordingly.
Also i updated the packages by using script , please review it again.

2024-08-05 10:22 UTC, evegufy commented
Hi @dhiren-singh-007 @Phil91 pre-checks for nuget packages are failing https://github.com/eclipse-tractusx/portal-backend/actions/runs/10199854820/job/28336547514?pr=860

2024-08-05 12:17 UTC, dhiren-singh-007 commented
> Hi @dhiren-singh-007 @Phil91 pre-checks for nuget packages are failing https://github.com/eclipse-tractusx/portal-backend/actions/runs/10199854820/job/28336547514?pr=860

Thanks @evegufy , i rebased the main and updated the packages. Now its running fine

2024-08-06 09:14 UTC, Phil91 approved these changes

2024-08-06 09:17 UTC, Phil91 requested changes

2024-08-06 09:17 UTC, Phil91 commented on src/framework/Framework.Models/ValidationExpressionsValidator.cs
> + * Copyright (c) 2022 Contributors to the Eclipse Foundation
Please change date to 2024 since its the creation date of the file

```suggestion
 * Copyright (c) 2024 Contributors to the Eclipse Foundation
```

2024-08-06 09:17 UTC, Phil91 commented on tests/framework/Framework.Models.Tests/ValidationExpressionsTests.cs
> + * Copyright (c) 2023 Contributors to the Eclipse Foundation
Please change date to 2024 since its the creation date of the file

```suggestion
 * Copyright (c) 2024 Contributors to the Eclipse Foundation
```

2024-08-06 13:20 UTC, Phil91 submitted a review, later dismissed

2024-08-12 12:05 UTC, ybidois commented
@MaximilianHauer thanks for setting this with higher priority! We really need it. Is it possible to approve it before Thursday?

2024-08-13 06:35 UTC, Phil91 approved these changes
lgtm. Thanks for changing the error handling to the new translatable method 👍

2024-08-13 06:58 UTC, MaximilianHauer commented
@evegufy  will review today . @nicoprow  please provide feedback if this is fine from BPDM perspective.

2024-08-13 11:35 UTC, ntruchsess requested changes

2024-08-13 11:35 UTC, ntruchsess commented on src/framework/Framework.Models/ValidationExpressionsValidator.cs
> +using System.Text.RegularExpressions;
this is redundant
```suggestion
```

2024-08-13 11:35 UTC, ntruchsess commented on src/framework/Framework.Models/ValidationExpressionsValidator.cs
> +    public static bool IsValidCompanyName(string companyName)
I suggest to define this as extension-method:
```suggestion
    public static bool IsValidCompanyName(this string companyName)
```
this way it can be used like so:
```
using Org.Eclipse.TractusX.Portal.Backend.Framework.Models;

var companyName = "Acme Corp";
if (!companyName.IsValidCompanyName())
{
}

2024-08-13 11:35 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
> +        if (!string.IsNullOrEmpty(data.Issuer) && !ValidationExpressionsValidator.IsValidCompanyName(data.Issuer))
```suggestion
        if (data.Issuer != null && !data.Issuer.IsValidCompanyName())
```
(see suggested change of IsValidCompanyName into a static extension-method)

2024-08-13 11:35 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/NetworkBusinessLogic.cs
> +        if (!ValidationExpressionsValidator.IsValidCompanyName(data.Name))
```suggestion
        if (!data.Name.IsValidCompanyName())
```

2024-08-13 12:26 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
> +            throw new ControllerArgumentException($"Issuer: {ValidationExpressionErrorMessages.CompanyError}", nameof(data.Issuer));
100% agree - ControllerArgumentException.Create(...) is the way to go :-)

2024-08-13 12:33 UTC, ntruchsess requested changes

2024-08-13 12:33 UTC, ntruchsess commented on src/framework/Framework.Models/ValidationExpressionsValidator.cs
> +{
```suggestion
{
    public static readonly Regex CompanyRegex = new(Company, RegexOptions.Compiled | RegexOptions.CultureInvariant | RegexOptions.ExplicitCapture, TimeSpan.FromSeconds(1));
```

2024-08-13 12:33 UTC, ntruchsess commented on src/framework/Framework.Models/ValidationExpressionsValidator.cs
> +        return ValidationExpressions.CompanyRegex.IsMatch(companyName);
```suggestion
        return CompanyRegex.IsMatch(companyName);
```

2024-08-13 15:48 UTC, dhiren-singh-007 commented
Thanks @ntruchsess for your review and suggestions . I applied the suggestions . Can you please re-review

2024-08-13 15:49 UTC, dhiren-singh-007 commented on src/framework/Framework.Models/ValidationExpressionsValidator.cs
> +{
I applied this suggestion manually but i am not sure why it is not showing outdated

2024-08-14 01:26 UTC, nicoprow reviewed
The changes are compatible to the BPDM API as far as I can tell. Refer to [here](https://github.com/eclipse-tractusx/portal/issues/360#issuecomment-2287647267) for more details.

2024-08-14 05:39 UTC, MaximilianHauer commented
@ntruchsess  / @evegufy you can proceed as soon as your findings are solved.

2024-08-14 07:18 UTC, ntruchsess approved these changes

2024-08-14 07:31 UTC, ntruchsess commented
@evegufy technically the PR is fine, but there is an issue with ECA-check, can you please check https://api.eclipse.org/git/eca/status/gh/eclipse-tractusx/portal-backend/860

2024-08-14 07:36 UTC, evegufy commented
> @dhiren-singh-007 @evegufy technically the PR is fine, but there is an issue with ECA-check, can you please check https://api.eclipse.org/git/eca/status/gh/eclipse-tractusx/portal-backend/860

see https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4897

2024-08-14 07:42 UTC, dhiren-singh-007 commented
Thanks @evegufy and @ntruchsess . Now ECA check is passed

2024-08-14 08:41 UTC, merged