feat(osp): endpoint to get onboarding osp companies details
eclipse-tractusx/portal-backend pull request #866
Opened 2024-07-24 09:46 UTC by AnuragNagpure

## Description

      GET endpoint should be accessible at /api/administration/registration/network/companies.
      Paginated response with max 20 records per page along with sorting, filtering and authorisation is required.

## Why

Need this api  to retrieve a list of all Onboarded OSP (Onboarding Service Provider) companies along with their current ### status

## Issue

#808

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-07-24 10:08 UTC, evegufy requested changes
https://github.com/eclipse-tractusx/portal-backend/issues/808 is flagged with milestone 2.1.0 (24.08), if that one is still valid directing the pull request to main is wrong, and it should go to the release branch, could you please clarify?

2024-07-24 11:08 UTC, AnuragNagpure commented
> #808 is flagged with milestone 2.1.0 (24.08), if that one is still valid directing the pull request to main is wrong, and it should go to the release branch, could you please clarify?

sure will directing to release branch

2024-07-24 12:28 UTC, Phil91 commented
@AnuragNagpure please rebase to release/v2.1.0-RC2 and make sure you synched to the latest version before. it seems like there are 8 commits in that shouldn't be in

2024-07-25 10:20 UTC, ntruchsess commented
I just removed the unwanted commits by doing an interactive rebase

2024-07-25 13:14 UTC, ntruchsess approved these changes

2024-07-25 14:26 UTC, ntruchsess commented
I did fix all of my review-findings

2024-07-25 17:20 UTC, evegufy requested changes
testing for 24.08 ends officially in less than 24h, please don't merge without me confirming but the change will very likely not go into the 2.1.0 release anymore, I'll let you know tomorrow

2024-07-26 09:01 UTC, Phil91 submitted a review, later dismissed

2024-07-29 10:43 UTC, evegufy commented
confirmed: v.2.1.0 is closed, please change to main

2024-07-30 06:53 UTC, Phil91 requested changes
One minor finding

2024-07-30 06:53 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
> +                        application.Company.Identities.Where(x => x.CompanyUser!.Identity!.UserStatusId != UserStatusId.DELETED).Count()))
This can be changed to

```suggestion
                        application.Company.Identities.Count(x => x.CompanyUser!.Identity!.UserStatusId != UserStatusId.DELETED)))
```

2024-07-31 06:18 UTC, Phil91 approved these changes

2024-08-04 17:15 UTC, MaximilianHauer commented
@evegufy  can you please approve that we can merge.

2024-08-05 06:25 UTC, merged