fix(appRoles): User is allowed to upload duplicate app roles
eclipse-tractusx/portal-backend pull request #877
Opened 2024-07-26 14:07 UTC by tfjanjua

## Description

- eliminate duplicate role values from api: /api/apps/appreleaseprocess/{appId}/role & /api/apps/AppChange/{appId}/role/activeapp
- added new api to batch delete recently uploaded app roles: /api/apps/appreleaseprocess/{appId}/roles:batchDelete

## Why

An app should have unique roles, duplicate roles are causing issue while assigning app roles to any company user.

## Issue

[Ref: #868](https://github.com/eclipse-tractusx/portal-backend/issues/868)

## Checklist

Please delete options that are not relevant.

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-08-05 10:18 UTC, evegufy submitted a review, later dismissed
Hi @tfjanjua thank you for the contribution! could you please resolve the remaining codeQL findings "Useless assignment to local variable"?

2024-08-05 11:19 UTC, tfjanjua commented on src/portalbackend/PortalBackend.DBAccess/Repositories/UserRolesRepository.cs
> +                        .ToList()
value of uniqueRoles variable has been used or read at line# 55 and 57

2024-08-05 11:19 UTC, tfjanjua commented on src/portalbackend/PortalBackend.DBAccess/Repositories/UserRolesRepository.cs
> +            uniqueRoles = appIdRoles.Select(x => new UserRole(Guid.NewGuid(), x.Role, x.AppId)).ToList();
value of uniqueRoles variable has been used or read at line# 55 and 57

2024-08-05 11:19 UTC, tfjanjua commented
> Hi @tfjanjua thank you for the contribution! could you please resolve the remaining codeQL findings "Useless assignment to local variable"?

Hi @evegufy , its resolved

2024-08-05 12:16 UTC, evegufy commented
Hi @ntruchsess @Phil91 could you please review?

2024-08-05 14:57 UTC, ntruchsess requested changes

2024-08-05 14:57 UTC, ntruchsess commented on src/marketplace/Apps.Service/Extensions/AppExtensions.cs
> +            userRolesRepository.CreateAppUserRoles(userRoles.Select(x => (appId, x.Role)).Distinct()),
applying Distinct only to the right side of Zip will produce incorrect results. Zip relies on both sides having the same number of elements, both being in the intended order.

2024-08-05 14:57 UTC, ntruchsess commented on src/marketplace/Apps.Service/Extensions/AppExtensions.cs
> +                    var appUserRoleDescriptions = userRoles.First(x => userRole.UserRoleText == x.Role);
this attempt to fix the incorrect results of Zip is redundant if Zip is applied correctly.

2024-08-05 14:57 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/UserRolesRepository.cs
> +        var appRoles = _dbContext.UserRoles.Where(w => appIdRoles.Select(a => a.AppId).Contains(w.OfferId))
This logic does not belong into the repository, it belongs to the business-logic. Repository should only contain linq-queries that more or less directly translate into sql. The businessLogic would call a suitable query to determine which roles should actually be created, deleted or updated and call the respective repository-methods.

2024-08-05 14:57 UTC, ntruchsess commented on src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +        var (OfferStatus, IsProviderCompanyUser, RoleIds) = await _portalRepositories.GetInstance<IOfferRepository>().GetAppUserRolesAsync(appId, companyId, OfferStatusId.CREATED, roleIds).ConfigureA
being local variables offerStatus, isProviderCompanyUser, roleIds should be lowercase.

2024-08-06 09:31 UTC, evegufy commented
merge_postponed as a decision about the endpoint semantics need be made, @MaximilianHauer could you please provide your feedback?

2024-08-07 07:50 UTC, tfjanjua commented on src/marketplace/Apps.Service/Extensions/AppExtensions.cs
> +            userRolesRepository.CreateAppUserRoles(userRoles.Select(x => (appId, x.Role)).Distinct()),
Agreed, I tweaked this method a little bit and I tested and it was working fine but the purpose of Zip method got disturbed.
I have reverted this method as it was before.

2024-08-07 07:50 UTC, tfjanjua commented on src/marketplace/Apps.Service/Extensions/AppExtensions.cs
> +                    var appUserRoleDescriptions = userRoles.First(x => userRole.UserRoleText == x.Role);
I have reverted this method as it was before.

2024-08-07 07:51 UTC, tfjanjua commented on src/portalbackend/PortalBackend.DBAccess/Repositories/UserRolesRepository.cs
> +        var appRoles = _dbContext.UserRoles.Where(w => appIdRoles.Select(a => a.AppId).Contains(w.OfferId))
I have reverted this method as it was before and moved this logic to business-logic.

2024-08-07 07:51 UTC, tfjanjua commented on src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
> +        var (OfferStatus, IsProviderCompanyUser, RoleIds) = await _portalRepositories.GetInstance<IOfferRepository>().GetAppUserRolesAsync(appId, companyId, OfferStatusId.CREATED, roleIds).ConfigureA
variables has been changed

2024-08-12 09:29 UTC, tfjanjua commented
> merge_postponed as a decision about the endpoint semantics need be made, @MaximilianHauer could you please provide your feedback?

Hi @evegufy , do you think we can merge this PR (if all looks good) and then frontend will take their part as per their capacity? because it will not break any frontend functionality but it would be nice if frontend would also work on it and resolve their part (Please check the Proposed Solution heading: https://github.com/eclipse-tractusx/portal-backend/issues/868)
I ask this because we need bug fix from this PR (stopping user from uploading duplicate app user roles) and implementation of new API (to bulk delete recently added App User Roles) is good to have but not urgent.

I can also separate bug (stopping user from uploading duplicate app user roles bug fix) and new API (to bulk delete recently added Roles) in separate PRs so, we could have bug fix quickly available.

Just FYI: we already have frontend capacity available to work on frontend part related to resolving the bug (stopping user from uploading duplicate app user roles bug fix) and implementing the new API (to bulk delete recently added Roles)
https://github.com/eclipse-tractusx/portal-frontend/issues/969

cc: @ybidois | @MaximilianHauer | @ntruchsess | @Phil91

2024-08-12 13:34 UTC, evegufy commented
> > merge_postponed as a decision about the endpoint semantics need be made, @MaximilianHauer could you please provide your feedback?
> 
> Hi @evegufy , do you think we can merge this PR (if all looks good) and then frontend will take their part as per their capacity? because it will not break any frontend functionality but it would be nice if frontend would also work on it and resolve their part (Please check the Proposed Solution heading: #868) I ask this because we need bug fix from this PR (stopping user from uploading duplicate app user roles) and implementation of new API (to bulk delete recently added App User Roles) is good to have but not urgent.
> 
> I can also separate bug (stopping user from uploading duplicate app user roles bug fix) and new API (to bulk delete recently added Roles) in separate PRs so, we could have bug fix quickly available.
> 
> Just FYI: we already have frontend capacity available to work on frontend part related to resolving the bug (stopping user from uploading duplicate app user roles bug fix) and implementing the new API (to bulk delete recently added Roles) [eclipse-tractusx/portal-frontend#969](https://github.com/eclipse-tractusx/portal-frontend/issues/969)
> 
> cc: @ybidois | @MaximilianHauer | @ntruchsess | @Phil91

Hi @tfjanjua,

afaik, @ntruchsess @MaximilianHauer where discussing about the implementation approach with the batch delete...
So yes, I think separating the bug and the new API, would help to get the bugfix in sooner.
Before you do that, please wait for feedback from @ntruchsess and @MaximilianHauer.

2024-08-13 07:11 UTC, ntruchsess requested changes

2024-08-13 07:11 UTC, ntruchsess commented on src/marketplace/Apps.Service/Extensions/AppExtensions.cs
> +            userRoles = userRoles.Where(w => !existingRoles.Contains(w.Role));
this is reimplementing Linq 'ExceptBy'

2024-08-13 07:11 UTC, ntruchsess commented on src/marketplace/Apps.Service/Extensions/AppExtensions.cs
> +        return userRoles.GroupBy(g => g.Role).Select(s => s.First());
this is not exactly reimplementing 'DistinctBy' but I guess this is what you intent to mimic

2024-08-13 08:38 UTC, tfjanjua commented on src/marketplace/Apps.Service/Extensions/AppExtensions.cs
> +    public static async Task<IEnumerable<AppRoleData>> CreateUserRolesWithDescriptions(IUserRolesRepository userRolesRepository, Guid appId, IEnumerable<AppUserRole> userRoles)
Thanks for your suggestion @ntruchsess but do you think it make sense to upload Duplicate Roles (like 'Manager' role more than 1 time) with different description? I mean if there are 2 Managers then those should be defined by their proper role name.

2024-08-13 10:28 UTC, tfjanjua commented
Hi @evegufy, I discussed with @ntruchsess and he explained the business behind this App User Roles and as per his explanation, it makes sense to replace all the App User Roles when user re-upload them and keep only the new ones instead of all roles (like previously uploaded and recently added from Add Roles option of any Active app) and just ignore the duplicate roles.

So, I have removed the implementation of new API (to delete recently uploaded App User Roles) from this PR and now this PR only has a fix to stop users to upload duplicate roles and we need this fix for our release and later (as we can see @Phil91 has added this PR in release 24.12) we can implement/change the existing API of Upload App User Roles as per @ntruchsess 's explanation.

So, please let me know if this PR can be merge OR should I close this PR and create another one? that new PR will also have 'Stop user to upload duplicate roles' fix.

cc: @ybidois | @MaximilianHauer

2024-08-13 17:14 UTC, evegufy commented
> Hi @evegufy, I discussed with @ntruchsess and he explained the business behind this App User Roles and as per his explanation, it makes sense to replace all the App User Roles when user re-upload them and keep only the new ones instead of all roles (like previously uploaded and recently added from Add Roles option of any Active app) and just ignore the duplicate roles.
> 
> So, I have removed the implementation of new API (to delete recently uploaded App User Roles) from this PR and now this PR only has a fix to stop users to upload duplicate roles and we need this fix for our release because if user uploads duplicate roles from any screen (App Onboarding->Technical Integration screen OR Load Additional Roles) so, later ending up encountering 409 conflict errors while assigning those duplicated App User Roles to a Company Users.
> 
> Later (as we can see @Phil91 has added this PR in release 24.12) we can implement/change the existing API of Upload App User Roles as per @ntruchsess 's explanation but this fix will stop users to upload duplicate roles till r24.12.
> 
> So, please let me know if this PR can be merge OR should I close this PR and create another one? that new PR will also have 'Stop user to upload duplicate roles' fix.
> 
> cc: @ybidois | @MaximilianHauer

@tfjanjua good, if it only contains the fix to stop users from uploading duplicate roles, I'll change the milestone to 2.2.0 and the base to the according release branch.
could you please still update the PR description so that it reflects only the fix? Please also update the PR title to a more conventional commit aligned message, like `fix(appRoles): don't allowed to upload duplicate app roles`
@ntruchsess could you please also confirm that this change is fine for you by approving?

2024-08-14 07:53 UTC, ntruchsess approved these changes

2024-08-14 08:55 UTC, evegufy approved these changes

2024-08-14 08:57 UTC, merged