fix(bpdm): allow null values for geographic coordinates
eclipse-tractusx/portal-backend pull request #882
Opened 2024-07-29 08:59 UTC by typecastcloud

## Description

Nullable double for coordinates allowed. Test case adjusted.

## Why

Null altitude breaks onboarding.

## Issue

Refs: #881

## Checklist

- [ ] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [ ] I have created and linked IP issues or requested their creation by a committer
- [ ] I have performed a self-review of my own code
- [ ] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

2024-07-29 09:15 UTC, typecastcloud commented
@evegufy @Phil91 please tell me if I should rebase against a different branch

2024-07-29 11:28 UTC, evegufy commented
> @evegufy @Phil91 please tell me if I should rebase against a different branch

@typecastcloud main is the correct one 👍

2024-07-29 13:21 UTC, Phil91 submitted a review, later dismissed

2024-07-31 15:17 UTC, evegufy requested changes
The change makes sense to me regarding alti
```
longitude* | number($float)Longitude coordinate
-- | --
latitude* | number($float)Latitude coordinate
altitude | number($float)Altitude, if applicable
```

2024-07-31 15:17 UTC, evegufy commented on src/externalsystems/Bpdm.Library/Models/BpdmLegalEntityData.cs
> +    double? Latitude,
Thank you for taking this up and the change makes sense to me regarding altitude but longitude and latitude aren't nullable according BPDM interface specification:

```
longitude* | number($float)Longitude coordinate
latitude* | number($float)Latitude coordinate
altitude | number($float)Altitude, if applicable
```

Why do you want to set them to nullable as well?

2024-08-01 07:25 UTC, typecastcloud commented on src/externalsystems/Bpdm.Library/Models/BpdmLegalEntityData.cs
> +    double? Latitude,
Hi, I didn't know about this specification. I will remove this for latitude and longitude.

2024-08-01 07:32 UTC, typecastcloud commented on src/externalsystems/Bpdm.Library/Models/BpdmLegalEntityData.cs
> +    double? Latitude,
@Phil91 @evegufy change applied and issue adjusted.

Only thing I found is that orchestrator also allows null for latitude and longitude here:
https://github.com/eclipse-tractusx/bpdm/blob/3579e50d6200b6a7ce2a9da811475cff4cbffe06/bpdm-orchestrator/src/main/kotlin/org/eclipse/tractusx/bpdm/orchestrator/entity/PostalAddressDb.kt#L132-L139

2024-08-01 08:21 UTC, evegufy approved these changes

2024-08-01 08:23 UTC, merged