feat(admin): validating bpn before adding to companyUser
eclipse-tractusx/portal-backend pull request #902
Opened 2024-08-06 11:39 UTC by Phil91

## Description

validating bpn before adding to companyUser

## Why

Added validation for BPN before adding to it companyUser

## Issue

Refs : #901

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-08-13 18:01 UTC, evegufy requested changes
<img width="447" alt="image" src="https://github.com/user-attachments/assets/6c970043-1833-44c5-868a-d73f1d3a23e9">

2024-08-14 10:53 UTC, Phil91 commented on src/externalsystems/Bpdm.Library/BpnAccess.cs
> +        var result = await _httpClient.GetAsync($"legal-entities/{businessPartnerNumber}?idType=BPN", cancellationToken)
escaping re added

2024-08-14 10:53 UTC, Phil91 commented on src/externalsystems/Bpdm.Library/BpnAccess.cs
> +    private readonly HttpClient _httpClient = httpFactory.CreateClient(nameof(BpnAccess));
adjusted.

2024-08-14 10:53 UTC, Phil91 commented
> <img alt="image" width="447" src="https://private-user-images.githubusercontent.com/46191613/357519037-6c970043-1833-44c5-868a-d73f1d3a23e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MzI3MjAsIm5iZiI6MTcyMzYzMjQyMCwicGF0aCI6Ii80NjE5MTYxMy8zNTc1MTkwMzctNmM5NzAwNDMtMTgzMy00NGM1LTg2OGEtZDczZjFkM2EyM2U5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDEwNDcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4ZmE4NDBkZDZkZjkwNGMyOWVmNWUwMDc2M2YyNTIyY2YzMTU2NTYzZWFiMjY5NDdkMTEzMTdhNWE2YTdhMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KPZvkso9TjO8YDoC8wqw63OY_I_-6bb-1x7SrDQ7ZzM">

fixed

2024-09-10 16:07 UTC, ntruchsess submitted a review, later dismissed

2024-09-11 06:28 UTC, evegufy requested changes

2024-09-11 06:28 UTC, evegufy commented on src/administration/Administration.Service/appsettings.json
> +    "BPN_Address": "",
regarding this config value, is a change in the helm chart needed as well?

2024-09-11 06:28 UTC, evegufy commented on src/administration/Administration.Service/appsettings.json
> +    "BaseAddress": "https://test.example.org"
regarding this config value, is a change in the helm chart needed as well?
And here a default value is set but [there](https://github.com/eclipse-tractusx/portal-backend/pull/902/files#diff-3903fca82639e0d29843b71bbe862434365acd6ba90ef1a8fb8981dd783eb321R39) no default is set, is that inconsistency necessary?
If there needs to be a default value, may it could be more of an example of the intended value, like in the cases where the default value `https://portal.example.org` or `https://semantic.example.org` are set.

2024-09-11 07:04 UTC, Phil91 commented on src/administration/Administration.Service/appsettings.json
> +    "BaseAddress": "https://test.example.org"
I've adjusted the config to be matching and created a pr on portal:

https://github.com/eclipse-tractusx/portal/pull/426

2024-09-11 07:04 UTC, Phil91 commented on src/administration/Administration.Service/appsettings.json
> +    "BPN_Address": "",
adjusted

2024-09-11 07:41 UTC, evegufy approved these changes

2024-09-11 07:47 UTC, merged