feat(bpdm): add sharing state ready toggle
eclipse-tractusx/portal-backend pull request #905
Opened 2024-08-08 09:08 UTC by Phil91

## Description

add toggle to disable the set sharing state ready call of the bpdm service

## Why

Bpdm has a toggle to set the sharing state automatically to ready, for that purpose its useful to have a toggle on the portal side as well.

## Issue

Refs: #845

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-08-08 13:13 UTC, evegufy commented
@gomezbc fyi, maybe you want to review as well :)

2024-08-08 13:59 UTC, gomezbc commented
> @gomezbc fyi, maybe you want to review as well :)

It looks nice to me :)

2024-08-13 18:25 UTC, evegufy approved these changes

2024-08-14 08:10 UTC, ntruchsess requested changes

2024-08-14 08:10 UTC, ntruchsess commented on src/externalsystems/Bpdm.Library/BpdmServiceSettings.cs
> +    public bool StartAsReady { get; set; }
shouldn't this be 'TriggerSharingState'?

2024-09-11 07:05 UTC, ntruchsess approved these changes

2024-09-11 07:07 UTC, merged