feat(ssi): add submit endpoints
eclipse-tractusx/portal-backend pull request #91
Opened 2023-06-21 12:54 UTC by Phil91

## Description

add endpoints to submit usecaseparticipation and ssi certificates

## Why

To be able to submit use case participations a endpoint was needed, same for an ssi certificate

## Issue

N/A - Jira Issue: CPLP-2854

## Corresponding CD PR

[#34](https://github.com/eclipse-tractusx/portal-cd/pull/34)

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2023-06-23 06:47 UTC, Phil91 commented
waiting for #84 to be merged, since this PR builds upon the code

2023-06-26 11:00 UTC, Phil91 commented
> #### ⚠️ GitGuardian has uncovered 2 secrets following the scan of your pull request.
> Please consider investigating the findings and remediating the incidents. Failure to do so may lead to compromising the associated services or software components.
> 
> 🔎 Detected hardcoded secrets in your pull request
> 🛠 Guidelines to remediate hardcoded secrets
> 🦉 [GitGuardian](https://dashboard.gitguardian.com/auth/login/?utm_medium=checkruns&utm_source=github&utm_campaign=cr1) detects secrets in your source code to help developers and security teams secure the modern development process. You are seeing this because you or someone else with access to this repository has authorized GitGuardian to scan your pull request.Our GitHub checks need improvements? [Share your feedbacks](https://050127dayho.typeform.com/to/KmeAPTMk)!

The finding are only uuid's used for tests, don't know why gitGuardian is marking them as security issue (secret).
I've already shared my feedback

2023-06-27 21:55 UTC, ntruchsess requested changes

2023-06-27 21:55 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
> +    public async Task CreateUseCaseParticipation((Guid UserId, Guid CompanyId) identity, UseCaseParticipationCreationData data, CancellationToken cts)
please rename the CancellationToken to 'cancellationToken' as it is being done in all the standard apis. (do so in all other methods that have a CancellationToken parameter)

2023-06-27 21:55 UTC, ntruchsess commented on src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
> +            hash, document.ContentType.ParseMediaTypeId(), DocumentTypeId.PRESENTATION, x =>
as the mediaTypeId is already being parsed be the caller it shall be passed to the method as parameter.

2023-06-27 21:55 UTC, ntruchsess commented on src/marketplace/Apps.Service/BusinessLogic/AppChangeBusinessLogic.cs
> +        var documentContentType = MediaTypeIdExtensions.ParseMediaTypeId(document.ContentType);
please use the extension way of calling 'document.ContentType.ParseMediaTypeId()'. Then use the new extension-method 'CheckDocumentContent' to validate.

2023-06-28 06:41 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
> +    public async Task CreateUseCaseParticipation((Guid UserId, Guid CompanyId) identity, UseCaseParticipationCreationData data, CancellationToken cts)
done

2023-06-28 06:41 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
> +            hash, document.ContentType.ParseMediaTypeId(), DocumentTypeId.PRESENTATION, x =>
done

2023-06-28 06:41 UTC, Phil91 commented on src/marketplace/Apps.Service/BusinessLogic/AppChangeBusinessLogic.cs
> +        var documentContentType = MediaTypeIdExtensions.ParseMediaTypeId(document.ContentType);
changed

2023-07-03 14:18 UTC, ntruchsess approved these changes

2023-07-03 14:26 UTC, ntruchsess requested changes

2023-07-03 14:26 UTC, ntruchsess commented on src/portalbackend/PortalBackend.PortalEntities/Entities/UseCaseParticipationStatus.cs
> +public class UseCaseParticipationStatus
this class doesn't have any references?

2023-07-03 20:11 UTC, Phil91 commented on src/portalbackend/PortalBackend.PortalEntities/Entities/UseCaseParticipationStatus.cs
> +public class UseCaseParticipationStatus
that was kinda odd... my rider wasn't showing the file at all. i did remove it.

2023-07-03 20:43 UTC, ntruchsess approved these changes

2023-07-03 20:51 UTC, ntruchsess requested changes

2023-07-03 20:51 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ICompanyCredentialDetailsRepository.cs
> +using Org.Eclipse.TractusX.Portal.Backend.PortalBackend.DBAccess.Models;
just noticed this file seems to be redundant too.

2023-07-03 20:54 UTC, ntruchsess requested changes

2023-07-03 20:54 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Models/UseCaseParticipation.cs
> +public record UseCaseParticipation
this file seems to be redundant as well. It's only referenced by ICompanyCredentialDetailsRepository.cs (which seems to be redundant).

2023-07-03 21:14 UTC, ntruchsess approved these changes
This PR now seems to be fine, but CD-PR https://github.com/eclipse-tractusx/portal-cd/pull/34 is still draft?

2023-07-04 06:23 UTC, Phil91 commented
> This PR now seems to be fine, but CD-PR [eclipse-tractusx/portal-cd#34](https://github.com/eclipse-tractusx/portal-cd/pull/34) is still draft?

Sorry i set i to active

2023-07-04 13:46 UTC, ntruchsess approved these changes

2023-07-04 14:21 UTC, merged