Feature/438 keycloak seeding
eclipse-tractusx/portal-backend pull request #910
Opened 2024-08-08 21:39 UTC by ntruchsess

## Description

This new PR is opened as the original PR #800 was closed due to retirement of catenax-ng org.

The keycloak-seeder has been changed to (optionaly) read multiple json-files per realm and seeding-data from it's settings and merge this additional data with the one that is read from json before writing changes to keycloak. This allows to both separate seeding-data of different domains and override values in the keycloak-json by settings being passed as environment-variables (which can be defined via helm-chart). 
The following client-properties can now be updated: RootUrl, BaseUrl, AdminUrl, RedirectUrls, Secret. (Before the change those values could only be initially set on creation of the respective entity)
KeecloakSeederSettings have been adjusted accordingly:
```
  "KeycloakSeeding": {
    "Realms": [
      {
        "Realm": "CX-Central",
        "InstanceName": "test",
        "DataPathes": [
          "realms/CX-Central-realm.json"
        ]
       "Id": "realms internal id",
       "DisplayName" "realms display name",
       ..... further realm configuration
       "Clients": [
       ],
       "IdentityProviders": [
       ],
       .... even further realm configuration...
      }
    ]
  }
```

## Why

seeding e.g. secrets from json-files would uncover confidential data. It also is unflexible - settings defined by environment-variables can e.g. be defined in kubernetes secrets.

## Issue

#438

## Checklist

Please delete options that are not relevant.

- [X] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [X] I have performed a self-review of my own code
- [X] I have successfully tested my changes locally
- [X] I have added tests that prove my changes work
- [X] I have checked that new and existing tests pass locally with my changes
- [X] I have commented my code, particularly in hard-to-understand areas

2024-09-13 14:18 UTC, MaximilianHauer commented
@ntruchsess could you check the quality gate ?

2024-09-17 11:40 UTC, Phil91 reviewed
Beside of the package version adjustment the pr looks good from my side (without testing the seeding itself)

2024-09-17 11:40 UTC, Phil91 commented on src/framework/Framework.Async/Directory.Build.props
> +    <VersionPrefix>2.8.0</VersionPrefix>
The version needs to be updated due to an update on the dev branch

2024-09-17 13:53 UTC, ntruchsess commented on src/framework/Framework.Async/Directory.Build.props
> +    <VersionPrefix>2.8.0</VersionPrefix>
done

2024-09-17 14:20 UTC, evegufy requested changes
Hi @ntruchsess I just test again and I'm encountering an unhandled expection:
`System.NullReferenceException: Object reference not set to an instance of an object.`

[logs.log](https://github.com/user-attachments/files/17029717/logs-from-centralidp-keycloak-realm-seeding-in-centralidp-keycloak-realm-seeding-2-ct522.log)

2024-09-19 06:14 UTC, Phil91 approved these changes

2024-09-19 08:38 UTC, evegufy requested changes

2024-09-19 08:38 UTC, evegufy commented on src/keycloak/Keycloak.Seeding/appsettings.json
> +    "Realms": []
```suggestion
    "Realms": [
      {
        "Realm": "",
        "InstanceName": "",
        "DataPaths": []
      }
    ]
```

2024-09-19 08:38 UTC, evegufy commented on src/keycloak/Keycloak.Seeding/BusinessLogic/SeedDataHandler.cs
> +        _keycloakRealm = (await realmSettings.DataPathes
remove typo:
```suggestion
        _keycloakRealm = (await realmSettings.DataPaths
```

2024-09-19 08:59 UTC, evegufy requested changes
During testing, I noticed an unhandled exception with status code 500 (Internal Server Error) during the deletion of assigned default client scopes:

```
"Exception":"Org.Eclipse.TractusX.Portal.Backend.Framework.ErrorHandling.ServiceException: Internal Server Error: http://sharedidp-keycloak/auth/admin/realms/master/clients/34e015a5-b944-46d8-a9f3-4bc8e856a727/default-client-scopes/ff556da8-6b2b-4fe3-97cf-4a9c93ffc3c1\n ---> Flurl.Http.FlurlHttpException: Call failed with status code 500 (Internal Server Error): DELETE http://sharedidp-keycloak/auth/admin/realms/master/clients/34e015a5-b944-46d8-a9f3-4bc8e856a727/default-client-scopes/ff556da8-6b2b-4fe3-97cf-4a9c93ffc3c1\n
```

Scenario:

-  master-realm is created and to default clients `admin-cli`, `account` and `security-admin-console` the default client scope `acr` is assigned
- seeding job uses a json file for the master realm where the default client  scope `acr` is not assigned to default clients `admin-cli`, `account` and `security-admin-console`
- seeding job runs into the exception above BUT only after successfully removing the assignments of the default client scope `acr` from default clients `admin-cli`, `account` and `security-admin-console`

Why is this exception thrown if the deletion is successful?

2024-09-19 09:04 UTC, ntruchsess commented on src/keycloak/Keycloak.Seeding/BusinessLogic/SeedDataHandler.cs
> +        _keycloakRealm = (await realmSettings.DataPathes
Plural of path is pathes (see https://en.wiktionary.org/wiki/path )

2024-09-20 07:01 UTC, ntruchsess commented on src/keycloak/Keycloak.Seeding/BusinessLogic/SeedDataHandler.cs
> +        _keycloakRealm = (await realmSettings.DataPathes
adjusted: https://github.com/eclipse-tractusx/portal-backend/pull/910/commits/43af89b15371c72b752b29a73723a2cde65d7a5e

2024-09-20 07:01 UTC, ntruchsess commented on src/keycloak/Keycloak.Seeding/appsettings.json
> +    "Realms": []
adjusted: https://github.com/eclipse-tractusx/portal-backend/pull/910/commits/43af89b15371c72b752b29a73723a2cde65d7a5e

2024-09-26 16:22 UTC, evegufy approved these changes
I created https://github.com/eclipse-tractusx/portal-backend/issues/1039 to follow up on  https://github.com/eclipse-tractusx/portal-backend/pull/910#pullrequestreview-2314893821

2024-09-26 18:42 UTC, merged