feat(offers): remove provider from offer
eclipse-tractusx/portal-backend pull request #911
Opened 2024-08-09 06:27 UTC by Phil91

## Description

instead of having a separate property for the provider the providing company name is used

## Why

The provider is kind of duplicated, since the offer is linked to a company which represents the provider the name of the company is better

## Issue

Refs: #811

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-09-11 08:48 UTC, ybidois commented
@ntruchsess @evegufy any timeline for reviewing this? We're very interested in cherry-picking it.

2024-09-11 12:07 UTC, ntruchsess commented
> @ntruchsess @evegufy any timeline for reviewing this? We're very interested in cherry-picking it.
@ybidois : I've returned from vacation and doing the review right now. Looks as if the change needs some adjusments but that shouldn't take too long.

2024-09-12 08:42 UTC, ntruchsess submitted a review, later dismissed

2024-09-12 09:25 UTC, evegufy requested changes
please take care of the codeql findings

2024-09-12 11:00 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
> +public class OfferRepository(PortalDbContext dbContext) : IOfferRepository
fixed

2024-09-12 11:00 UTC, ntruchsess commented on src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
> +public class OfferSubscriptionsRepository(PortalDbContext dbContext) : IOfferSubscriptionsRepository
fixed

2024-09-12 11:00 UTC, ntruchsess commented
> please take care of the codeql findings

both fixed

2024-09-12 11:02 UTC, ntruchsess approved these changes

2024-09-12 11:24 UTC, evegufy approved these changes

2024-09-12 12:23 UTC, merged