feat(processes): adjust retriggers
eclipse-tractusx/portal-backend pull request #915
Opened 2024-08-12 10:04 UTC by Phil91

## Description

* add missing endpoints to retrigger failed steps
* add retrigger steps and endpoints for process steps which miss a retrigger step

## Why

There are retrigger steps without an endpoint to retrigger them and some processes are missing a retrigger step.

## Issue

Refs: #912

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-08-14 06:41 UTC, evegufy reviewed
Did you notice the 4 new issues by sonarcloud?
Can they, or some of them, be addressed?

2024-08-14 06:42 UTC, Phil91 commented
> Did you notice the 4 new issues by sonarcloud? Can they, or some of them, be addressed?

@evegufy yes, did saw them and had a look at them, those are all because of the migration. I wouldn't address them. But I mark them as won't do on sonar with an appropriate comment

2024-09-12 09:32 UTC, evegufy requested changes

2024-09-12 09:32 UTC, evegufy commented on src/processes/Processes.Library/RetriggerExtensions.cs
please add file header

2024-09-12 13:44 UTC, ntruchsess commented on src/processes/Processes.Library/RetriggerExtensions.cs
done

2024-09-12 16:12 UTC, ntruchsess approved these changes

2024-09-12 16:15 UTC, merged