fix(connectors): connectors with right provider added
eclipse-tractusx/portal-backend pull request #946
Opened 2024-08-21 11:55 UTC by AnuragNagpure

## Description

When creating a managed connector via POST: /api/administration/connectors/managed the host company is set as the provider and the provider company is set as the host

## Why

The correct provider and host should be set.

## Issue

#944 

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-08-21 13:19 UTC, Phil91 requested changes

2024-08-21 13:19 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
> +        var connectorRequestModel = new ConnectorRequestModel(name, connectorUrl, ConnectorTypeId.CONNECTOR_AS_A_SERVICE, location, companyId, result.CompanyId, technicalUserId);
Wondering that no unit tests are failing. Please adjust the existing unit tests accordingly to test that the correct provider / host is set

2024-08-23 11:25 UTC, AnuragNagpure commented
Hi @Phil91 am cancelling this pull request as it is pointing towards main branch instead release/v2.2.0-RC3. Also updated code for review comments is added in new pull request which is pointing towards release/v2.2.0-RC3

2024-08-23 11:25 UTC, closed without merging

2024-08-23 11:25 UTC, AnuragNagpure commented
Hi @Phil91 am cancelling this pull request as it is pointing towards main branch instead release/v2.2.0-RC3. Also updated code for review comments is added in new pull request which is pointing towards release/v2.2.0-RC3