feat(clearinghouse): add auto retrigger for END_CLEARINGHOUSE
eclipse-tractusx/portal-backend pull request #958
Opened 2024-08-28 13:14 UTC by Phil91

## Description

enable maintenance worker to retrigger the clearinghouse process

## Why

To enable an auto retrigger for the clearinghouse process if the END_CLEARINGHOUSE is on TODO for a certain time.

## Issue

Refs: #810

## Corresponding CD PR

https://github.com/eclipse-tractusx/portal/pull/418

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-09-12 13:44 UTC, evegufy requested changes
Please take care of codeql findings

2024-09-12 13:44 UTC, evegufy commented on src/maintenance/Maintenance.App/DependencyInjection/MaintenanceServiceExtensions.cs
please add file header

2024-09-12 13:44 UTC, evegufy commented on src/maintenance/Maintenance.App/DependencyInjection/BatchDeleteServiceSettings.cs
please add file header

2024-09-12 13:44 UTC, evegufy commented on src/administration/Administration.Service/Extensions/CompanyApplicationStatusFilterExtensions.cs
Please add file header

2024-09-13 06:15 UTC, Phil91 commented on src/administration/Administration.Service/Extensions/CompanyApplicationStatusFilterExtensions.cs
added

2024-09-13 06:15 UTC, Phil91 commented on src/maintenance/Maintenance.App/DependencyInjection/BatchDeleteServiceSettings.cs
added

2024-09-13 06:15 UTC, Phil91 commented on src/maintenance/Maintenance.App/DependencyInjection/MaintenanceServiceExtensions.cs
added

2024-09-16 20:22 UTC, ntruchsess requested changes
I've refactored some hard to read code, removed some reduncancy and moved code to where it belongs (calls on dbcontext into repo).
remark: not all scanner findings give good guidance to create better understandable code - e.g. implicitly selecting (cause of async lambda) into into a task in the foreach-loop where that task is awaited at a different location might not be understud by every developer at the first glance. I did add a new factory-method that turns IEnumerable<Task<X>> into IAsyncEnumerable<X> which allows to await the tasks directly in the foreach.
There is one comment you should check (new unreferenced setting) and 4 scanner-findings I leave up to you to resolve ;-)

2024-09-16 20:22 UTC, ntruchsess commented on src/administration/Administration.Service/Extensions/CompanyApplicationStatusFilterExtensions.cs
> +    public static IEnumerable<CompanyApplicationStatusId> GetCompanyApplicationStatusIds(this CompanyApplicationStatusFilter? companyApplicationStatusFilter) =>
Even if it doesn't belong to this ticket - as I like this extension better then the private method I've refactored RegistrationBusinessLogic accordingly.

2024-09-17 07:11 UTC, ntruchsess commented
@Phil91 : had to replace END_CLEARINGHOUSE by AWAIT_CLEARING_HOUSE_RESPONSE as per rebase on main. From my understanding that should just have been a rename without semantic changes?

2024-09-17 09:56 UTC, Phil91 commented on src/administration/Administration.Service/DependencyInjection/PartnerRegistrationSettings.cs
> +    public int ApplicationsMaxPageSize { get; set; }
seems like I've added that by mistake, removed it.

2024-09-17 10:00 UTC, Phil91 commented
> @Phil91 : had to replace END_CLEARINGHOUSE by AWAIT_CLEARING_HOUSE_RESPONSE as per rebase on main. From my understanding that should just have been a rename without semantic changes?

@ntruchsess correct :)

2024-09-17 10:16 UTC, ntruchsess approved these changes

2024-09-17 10:20 UTC, merged