feat(invitation): added invitation id and api for invitation details
eclipse-tractusx/portal-backend pull request #959
Opened 2024-08-28 13:44 UTC by dhiren-singh-007

## Description

Added Invitation Id in response of ExecuteInvitation api i.e `POST: api/administration/invitation`
Created a new api to get the application id and company id by using invitation id i.e `GET: api/administration/invitation/{invitationId}`

## Why

In automation and CRM for self registration (Hubspot) there was no reference id to track the Invitation .
So now by this invitation Id they can call the newly created api to get the Application id and Company Id

## Issue

#834 

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-08-29 09:08 UTC, Phil91 requested changes

2024-08-29 09:08 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyInvitationRepository.cs
> +            ))
You can change the return type to directly return `CompanyInvitationDetails`

```suggestion
    public Task< CompanyInvitationDetails?> GetInvitationCompanyAndApplicationId(Guid invitationId) =>
        _context.CompanyInvitations
            .Where(x => x.Id == invitationId)
            .Select(x => new CompanyInvitationDetails(
                x.ApplicationId,
                x.Application!.CompanyId
            ))
```

2024-08-29 09:08 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ICompanyInvitationRepository.cs
> +    Task<(Guid? ApplicationId, Guid? CompanyId)> GetInvitationCompanyAndApplicationId(Guid invitationId);
See my comment in CompanyInvitationRepository

2024-08-29 09:08 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/InvitationBusinessLogic.cs
> +        var companyInvitation = await _portalRepositories.GetInstance<ICompanyInvitationRepository>().GetInvitationCompanyAndApplicationId(invitationId);
In my opinion there is some error handling missing.

1. CompanyInvitation does not exist for the given id - should result in a NotFoundException (404)
2. this one might be discussable - If applicationId and companyId is null why return it? In my opinion we should return a 400 Exception here. At least the applicationId should always be set.

@MaximilianHauer what's your opinion the point 2?

2024-08-30 08:52 UTC, dhiren-singh-007 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyInvitationRepository.cs
> +            ))
@Phil91 : Actually this Record is created in Admin Service so i don't think we should reference the Admin service in repository

2024-08-30 08:58 UTC, dhiren-singh-007 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyInvitationRepository.cs
> +            ))
or shall i create a model in DB.Access library?

2024-09-02 13:31 UTC, Phil91 commented
@dhiren-singh-007 I think we can close this PR because of the merge of: #963 correct?

2024-09-05 12:25 UTC, closed without merging