feat(connector): adjust connector deletion
eclipse-tractusx/portal-backend pull request #968
Opened 2024-09-03 12:32 UTC by Phil91

## Description

* add flag to define whether a linked service account should be deleted
* adjust deletion logic for service accounts when deleting a connector

## Why

The deletion logic for connectors currently doesn't support the deletion process of external service accounts

## Issue

Refs: #966 #967

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-09-09 14:58 UTC, evegufy requested changes

2024-09-09 14:58 UTC, evegufy commented on tests/administration/Administration.Service.Tests/BusinessLogic/ServiceAccountManagementTests.cs
file header missing

2024-09-10 05:43 UTC, Phil91 commented on tests/administration/Administration.Service.Tests/BusinessLogic/ServiceAccountManagementTests.cs
added

2024-09-10 09:15 UTC, evegufy approved these changes

2024-09-10 09:19 UTC, merged