feat(app): adjust status query param for subscription-status
eclipse-tractusx/portal-backend pull request #969
Opened 2024-09-03 12:56 UTC by Phil91

## Description

* added query param `name` to endpoint `GET: /api/apps/subscribed/subscription-status` to filter for app names
* added query param `name` to endpoint `GET: /api/services/subscribed/subscription-status` to filter for service names
* changed query param `statusId` to `status` of endpoint `GET: /api/apps/subscribed/subscription-status`

## Why

To be able to search for specific apps

## Issue

Refs: #592

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-09-09 13:16 UTC, evegufy requested changes

2024-09-09 13:16 UTC, evegufy commented on src/marketplace/Apps.Service/Controllers/AppsController.cs
> +    /// <param name="status">Filter for the offer subscription status. If not set all elements will be returned</param>
```suggestion
    /// <param name="status">Filter for the offer subscription status. If not set, all elements will be returned</param>
```

2024-09-09 13:16 UTC, evegufy commented on src/marketplace/Services.Service/Controllers/ServicesController.cs
> +    /// <param name="status">Filter for the offer subscription status. If not set all elements will be returned</param>
```suggestion
    /// <param name="status">Filter for the offer subscription status. If not set, all elements will be returned</param>
```

2024-09-09 13:18 UTC, evegufy commented
@MaximilianHauer @Phil91 is the milestone 24.12 correct for https://github.com/eclipse-tractusx/portal-backend/issues/592?

2024-09-09 13:34 UTC, Phil91 commented on src/marketplace/Services.Service/Controllers/ServicesController.cs
> +    /// <param name="status">Filter for the offer subscription status. If not set all elements will be returned</param>
adjusted

2024-09-09 13:34 UTC, Phil91 commented
> @MaximilianHauer @Phil91 is the milestone 24.12 correct for #592?

@evegufy in my opinion it isn't

2024-09-10 00:20 UTC, ntruchsess approved these changes

2024-09-10 00:21 UTC, merged