feat(technicaluser): new parameters for api expansion for technical user data added
eclipse-tractusx/portal-backend pull request #997
Opened 2024-09-16 10:28 UTC by AnuragNagpure

## Description

Add Parameter usertype and authentication_service_url in below mentioned api
GET: api/administration/serviceaccount/owncompany/serviceaccounts/{GetServiceAccountId}

## Why

For checking user_type internal or external and valid authenticatio_service_url for specific technical user 

## Issue

#976 

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-09-16 10:54 UTC, Phil91 commented
@AnuragNagpure please solve the codeQl findings

2024-09-16 12:11 UTC, Phil91 requested changes

2024-09-16 12:11 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
> +            result.DimServiceAccountData!.AuthenticationServiceUrl,
This will fail if the user is an internal user since DimServiceAccountData is null. The authticattionServiceUrl for internal users should point to the centralIdp instead.
 Please make sure to add a unit test that fails with the current implementation for internal users. And than fix the code afterwards

2024-09-18 08:56 UTC, AnuragNagpure commented on src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
> +            result.DimServiceAccountData!.AuthenticationServiceUrl,
Changes as per mentioned in ticket for internal user type added

2024-09-18 09:50 UTC, Phil91 requested changes
Please link the corresponding PR for the portal repo for the settings adjustments.

2024-09-18 09:50 UTC, Phil91 commented on src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
> +        var AuthServiceUrl = (result.CompanyServiceAccountKindId == CompanyServiceAccountKindId.INTERNAL) ? _settings.AuthServiceUrl : result.DimServiceAccountData!.AuthenticationServiceUrl;
Please don‘t use the `!` operator without checking the value to not be null. This would throw an unhandled exception if for some reason DimServiceAccountData is null for an external service account.

A better way would be to be to set the AuthServiceUrl to the settings value and overwrite it in the `if (result.DimServiceAccountData != null)`

also please change `AuthServiceUrl` to `authServiceUrl`since its a local variable

2024-09-18 09:50 UTC, Phil91 commented on src/administration/Administration.Service/Models/ServiceAccountConnectorOfferData.cs
> +    [property: JsonPropertyName("subscriptionId")] Guid? SubscriptionId = null
I don't anything mentioning adding the subscriptionId in the issue, was there anything discussed besides the ticket description? If not please remove

2024-09-18 09:50 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Models/CompanyServiceAccountDetailedData.cs
> +    Guid? SubscriptionId,
same as above

2024-09-18 09:50 UTC, Phil91 commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ServiceAccountRepository.cs
> +                x.ServiceAccount.OfferSubscriptionId,
same as above

2024-09-18 09:50 UTC, Phil91 commented on tests/administration/Administration.Service.Tests/BusinessLogic/ServiceAccountBusinessLogicTests.cs
> +            .With(x => x.DimServiceAccountData, default(DimServiceAccountData?))
Please change to null

2024-09-18 09:50 UTC, Phil91 commented on tests/administration/Administration.Service.Tests/BusinessLogic/ServiceAccountBusinessLogicTests.cs
> +            .With(x => x.DimServiceAccountData, default(DimServiceAccountData?))
Please change to an instance of dimServiceAccountData with fake data

2024-09-18 13:52 UTC, AnuragNagpure commented
> Please link the corresponding PR for the portal repo for the settings adjustments.

https://github.com/eclipse-tractusx/portal/pull/432

2024-09-18 13:52 UTC, AnuragNagpure commented on tests/administration/Administration.Service.Tests/BusinessLogic/ServiceAccountBusinessLogicTests.cs
> +            .With(x => x.DimServiceAccountData, default(DimServiceAccountData?))
changed

2024-09-18 13:53 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.DBAccess/Repositories/ServiceAccountRepository.cs
> +                x.ServiceAccount.OfferSubscriptionId,
removed

2024-09-18 13:53 UTC, AnuragNagpure commented on tests/administration/Administration.Service.Tests/BusinessLogic/ServiceAccountBusinessLogicTests.cs
> +            .With(x => x.DimServiceAccountData, default(DimServiceAccountData?))
as DimServiceAccountData is set as default it is already coming as null

2024-09-18 13:53 UTC, AnuragNagpure commented on src/portalbackend/PortalBackend.DBAccess/Models/CompanyServiceAccountDetailedData.cs
> +    Guid? SubscriptionId,
removed

2024-09-18 13:53 UTC, AnuragNagpure commented on src/administration/Administration.Service/Models/ServiceAccountConnectorOfferData.cs
> +    [property: JsonPropertyName("subscriptionId")] Guid? SubscriptionId = null
removed

2024-09-18 13:54 UTC, AnuragNagpure commented on src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
> +        var AuthServiceUrl = (result.CompanyServiceAccountKindId == CompanyServiceAccountKindId.INTERNAL) ? _settings.AuthServiceUrl : result.DimServiceAccountData!.AuthenticationServiceUrl;
changes added

2024-09-19 05:49 UTC, Phil91 approved these changes

2024-09-19 05:58 UTC, Phil91 approved these changes

2024-09-19 06:04 UTC, merged