feat(processWorker): create process worker package
eclipse-tractusx/portal-backend pull request #998
Opened 2024-09-16 10:39 UTC by Phil91

## Description

* create packages for the process worker library
* adjusting code to use the new library

## Why

To provide the process worker functionality to other products as well

## Issue

N/A

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

2024-09-27 14:20 UTC, Phil91 commented on src/framework/Framework.Processes.Library/Entities/Process.cs
> +        ProcessSteps = new HashSet<ProcessStep<TProcessTypeId, TProcessStepTypeId>>();
Needed for ef

2024-09-27 14:20 UTC, Phil91 commented on src/framework/Framework.Processes.Library/Entities/ProcessStepStatus.cs
> +        ProcessSteps = new HashSet<ProcessStep<TProcessTypeId, TProcessStepTypeId>>();
Needed for ef

2024-09-27 14:20 UTC, Phil91 commented on src/portalbackend/PortalBackend.PortalEntities/Entities/ProcessStepType.cs
> +        ProcessSteps = new HashSet<ProcessStep<ProcessTypeId, ProcessStepTypeId>>();
Needed for ef

2024-09-27 14:20 UTC, Phil91 commented on src/portalbackend/PortalBackend.PortalEntities/Entities/ProcessType.cs
> +        Processes = new HashSet<Process<ProcessTypeId, ProcessStepTypeId>>();
Needed for ef

2025-01-07 08:40 UTC, typecastcloud submitted a review, later dismissed
As far as I can see everything works like before and my tests succeeded.

Some code changes were reviewed by me (not 13k) and look fine. Please test jobs after deployment.

2025-01-07 17:18 UTC, ntruchsess requested changes
Generaly speaking as c# inheritance is limited to a single base-type it is not advisable to mandatory enforce inheritance from a framework type. Instead interfaces should be used.
In respect to EF using concrete entity-types and dbcontext base class defines hardcoded table-names that cannot be adjusted by the framework-using code. It implies an application cannot have more than a single process/process-step table within a given db-schema. In addition to that it also disallows to define any other custom base-class for the dbcontext.
Instead the framework should define interfaces to be implemented by the concrete entities (Process, ProcessStep and ProcessStepStatus) and those interfaces should be used within the framework code.
Concrete Entity-classes implementing those interfaces and dbcontext base class may still be provided (in a separate implementation package) but the use of those should be optional.

2025-01-22 19:21 UTC, ntruchsess approved these changes

2025-01-23 08:17 UTC, ntruchsess approved these changes

2025-01-23 11:16 UTC, merged